-- ¿MIN o MAX de FECHA_AUTORIZ por CCMN? Y ¿por que 174 autorizaciones "despues" de la orden?
SET NOCOUNT ON;

-- A. Multiplicidad: cuantos SEC_CUADRO por CCMN
SELECT 'A_multiplicidad' AS q,
       COUNT(*) AS ccmn,
       SUM(CASE WHEN n = 1 THEN 1 ELSE 0 END) AS con_1_cuadro,
       SUM(CASE WHEN n > 1 THEN 1 ELSE 0 END) AS con_varios,
       MAX(n) AS max_cuadros
FROM (
    SELECT NRO_CONS_PAAC, TIPO_BIEN, COUNT(*) AS n
    FROM SIG_CUADRO_ADQUISICION
    WHERE ANO_EJE = 2026 AND SEC_EJEC = 300687
    GROUP BY NRO_CONS_PAAC, TIPO_BIEN
) t;

-- B. Con MIN(FECHA_AUTORIZ): orden temporal vs primera orden del CCMN
WITH ca AS (
    SELECT TIPO_BIEN, NRO_CONS_PAAC,
           MIN(FECHA_AUTORIZ) AS F_MIN, MAX(FECHA_AUTORIZ) AS F_MAX
    FROM SIG_CUADRO_ADQUISICION
    WHERE ANO_EJE = 2026 AND SEC_EJEC = 300687
    GROUP BY TIPO_BIEN, NRO_CONS_PAAC
),
ord_ccmn AS (
    SELECT o.TIPO_BIEN, x.NRO_CONS_PAAC, MIN(o.FECHA_ORDEN) AS FECHA_ORDEN
    FROM SIG_ORDEN_ADQUISICION o
    JOIN SIG_CUADRO_ADQUISICION x
      ON x.ANO_EJE = o.ANO_EJE AND x.SEC_EJEC = o.SEC_EJEC
     AND x.TIPO_BIEN = o.TIPO_BIEN AND x.SEC_CUADRO = o.SEC_CUADRO
    WHERE o.ANO_EJE = 2026 AND o.SEC_EJEC = 300687
    GROUP BY o.TIPO_BIEN, x.NRO_CONS_PAAC
)
SELECT 'B_min_vs_orden' AS q,
       COUNT(*) AS ccmn_con_orden,
       SUM(CASE WHEN ca.F_MIN <= o.FECHA_ORDEN THEN 1 ELSE 0 END) AS min_antes_orden,
       SUM(CASE WHEN ca.F_MIN > o.FECHA_ORDEN THEN 1 ELSE 0 END) AS min_despues_orden,
       SUM(CASE WHEN ca.F_MAX <= o.FECHA_ORDEN THEN 1 ELSE 0 END) AS max_antes_orden,
       SUM(CASE WHEN ca.F_MAX > o.FECHA_ORDEN THEN 1 ELSE 0 END) AS max_despues_orden
FROM ca
JOIN ord_ccmn o ON o.TIPO_BIEN = ca.TIPO_BIEN AND o.NRO_CONS_PAAC = ca.NRO_CONS_PAAC;

-- C. Muestra de casos donde MIN(FECHA_AUTORIZ) > FECHA_ORDEN (anomalia)
WITH ca AS (
    SELECT TIPO_BIEN, NRO_CONS_PAAC, MIN(FECHA_AUTORIZ) AS F_MIN
    FROM SIG_CUADRO_ADQUISICION
    WHERE ANO_EJE = 2026 AND SEC_EJEC = 300687
    GROUP BY TIPO_BIEN, NRO_CONS_PAAC
),
ord_ccmn AS (
    SELECT o.TIPO_BIEN, x.NRO_CONS_PAAC, MIN(o.FECHA_ORDEN) AS FECHA_ORDEN
    FROM SIG_ORDEN_ADQUISICION o
    JOIN SIG_CUADRO_ADQUISICION x
      ON x.ANO_EJE = o.ANO_EJE AND x.SEC_EJEC = o.SEC_EJEC
     AND x.TIPO_BIEN = o.TIPO_BIEN AND x.SEC_CUADRO = o.SEC_CUADRO
    WHERE o.ANO_EJE = 2026 AND o.SEC_EJEC = 300687
    GROUP BY o.TIPO_BIEN, x.NRO_CONS_PAAC
)
SELECT TOP 10 'C_anomalias' AS q, ca.TIPO_BIEN, ca.NRO_CONS_PAAC,
       CONVERT(varchar(10), ca.F_MIN, 120) AS f_autoriz_min,
       CONVERT(varchar(10), o.FECHA_ORDEN, 120) AS f_orden,
       DATEDIFF(day, o.FECHA_ORDEN, ca.F_MIN) AS dias_diff
FROM ca
JOIN ord_ccmn o ON o.TIPO_BIEN = ca.TIPO_BIEN AND o.NRO_CONS_PAAC = ca.NRO_CONS_PAAC
WHERE ca.F_MIN > o.FECHA_ORDEN
ORDER BY dias_diff DESC;

-- D. Testigo 5/B (bolsa 933 -> CCMN 2240): fechas con MIN
SELECT 'D_testigo_2240' AS q, TIPO_BIEN, NRO_CONS_PAAC, SEC_CUADRO,
       CONVERT(varchar(10), FECHA_CUADRO, 120) AS f_cuadro,
       CONVERT(varchar(10), FECHA_AUTORIZ, 120) AS f_autoriz,
       CONVERT(varchar(10), FECHA_COMPRA, 120) AS f_compra
FROM SIG_CUADRO_ADQUISICION
WHERE ANO_EJE = 2026 AND SEC_EJEC = 300687 AND NRO_CONS_PAAC = 2240;
