-- ¿Como se detecta ejecucion/devengado de BIENES? (SEC_EJEC=300687, 2026)
SET NOCOUNT ON;

-- A. Ordenes de bienes con entrada de almacen (SIG_MOVIM_ALMACEN.NRO_ORDEN)
SELECT 'A_entrada_almacen' AS q,
       COUNT(*) AS ordenes_bienes,
       SUM(CASE WHEN ma.NRO_ORDEN IS NOT NULL THEN 1 ELSE 0 END) AS con_entrada,
       SUM(CASE WHEN o.ESTADO_SIAF = '2' THEN 1 ELSE 0 END) AS estado_siaf_2
FROM SIG_ORDEN_ADQUISICION o
LEFT JOIN (
    SELECT DISTINCT ANO_EJE, SEC_EJEC, NRO_ORDEN
    FROM SIG_MOVIM_ALMACEN
    WHERE ANO_EJE = 2026 AND SEC_EJEC = 300687
      AND TIPO_MOVIMTO = 'I' AND TIPO_TRANSAC = 1 AND NRO_ORDEN IS NOT NULL
) ma ON ma.ANO_EJE = o.ANO_EJE AND ma.SEC_EJEC = o.SEC_EJEC
    AND ma.NRO_ORDEN = o.NRO_ORDEN
WHERE o.ANO_EJE = 2026 AND o.SEC_EJEC = 300687 AND o.TIPO_BIEN = 'B';

-- B. Distribucion de ESTADO_SIAF en ordenes por tipo
SELECT 'B_estado_siaf' AS q, TIPO_BIEN, ESTADO_SIAF, COUNT(*) AS n
FROM SIG_ORDEN_ADQUISICION
WHERE ANO_EJE = 2026 AND SEC_EJEC = 300687
GROUP BY TIPO_BIEN, ESTADO_SIAF
ORDER BY TIPO_BIEN, ESTADO_SIAF;

-- C. TIPO_OPERACION en SIG_EXP_SIGA_DOCU (¿hay fase devengado con fecha?)
SELECT 'C_tipo_operacion' AS q, TIPO_OPERACION, COUNT(*) AS n,
       SUM(CASE WHEN FECHA_INTERFASE IS NOT NULL THEN 1 ELSE 0 END) AS con_interfase
FROM SIG_EXP_SIGA_DOCU
WHERE ANO_EJE = 2026 AND SEC_EJEC = 300687
GROUP BY TIPO_OPERACION
ORDER BY TIPO_OPERACION;

-- D. ¿SIG_MOVIM_ALMACEN entrada trae fecha? cobertura de FECHA_MOVIMTO
SELECT 'D_fechas_entrada' AS q,
       COUNT(*) AS entradas,
       SUM(CASE WHEN FECHA_MOVIMTO IS NOT NULL THEN 1 ELSE 0 END) AS con_fecha,
       SUM(CASE WHEN NRO_ORDEN IS NOT NULL THEN 1 ELSE 0 END) AS con_orden
FROM SIG_MOVIM_ALMACEN
WHERE ANO_EJE = 2026 AND SEC_EJEC = 300687
  AND TIPO_MOVIMTO = 'I' AND TIPO_TRANSAC = 1;

-- E. Salidas (pecosa): ¿referencian orden tambien?
SELECT 'E_salidas' AS q,
       COUNT(*) AS salidas,
       SUM(CASE WHEN NRO_ORDEN IS NOT NULL THEN 1 ELSE 0 END) AS con_orden,
       SUM(CASE WHEN FECHA_MOVIMTO IS NOT NULL THEN 1 ELSE 0 END) AS con_fecha
FROM SIG_MOVIM_ALMACEN
WHERE ANO_EJE = 2026 AND SEC_EJEC = 300687
  AND TIPO_MOVIMTO = 'S' AND TIPO_TRANSAC = 1;

-- F. Conformidad de BIENES: ¿existe SIG_MOVIM_CONFOR para bienes o tabla equivalente?
SELECT 'F_confor_bienes' AS q, TIPO_BIEN, COUNT(*) AS n
FROM SIG_MOVIM_CONFOR_SERVICIO
WHERE ANO_ORDEN = 2026 AND SEC_EJEC = 300687
GROUP BY TIPO_BIEN;
