-- ¿El despacho PECOSA de una O/C se puede recuperar via el pedido de atencion ('1')?
SET NOCOUNT ON;

-- A. Pedidos '1' 2026: ¿el motivo nombra la O/C?
SELECT 'A_motivo_nombra_oc' AS q,
       COUNT(*) AS pedidos_1,
       SUM(CASE WHEN CAST(MOTIVO_PEDIDO AS VARCHAR(2000)) LIKE '%O/C%' THEN 1 ELSE 0 END) AS nombra_oc,
       SUM(CASE WHEN CAST(MOTIVO_PEDIDO AS VARCHAR(2000)) LIKE '%ORDEN%' THEN 1 ELSE 0 END) AS nombra_orden
FROM SIG_PEDIDOS
WHERE ANO_EJE = 2026 AND SEC_EJEC = 300687 AND TIPO_PEDIDO = '1';

-- B. Muestra de motivos
SELECT TOP 8 'B_muestra' AS q, NRO_PEDIDO,
       LEFT(CAST(MOTIVO_PEDIDO AS VARCHAR(200)), 90) AS motivo
FROM SIG_PEDIDOS
WHERE ANO_EJE = 2026 AND SEC_EJEC = 300687 AND TIPO_PEDIDO = '1'
ORDER BY NRO_PEDIDO DESC;

-- C. ¿Los items del pedido '1' tienen NRO_PECOSA y esta cruza con salida de almacen?
SELECT 'C_items_1' AS q,
       COUNT(*) AS items,
       SUM(CASE WHEN dp.NRO_PECOSA > 0 THEN 1 ELSE 0 END) AS con_pecosa,
       SUM(CASE WHEN ma.NRO_MOVIMTO IS NOT NULL THEN 1 ELSE 0 END) AS pecosa_en_almacen
FROM SIG_DETALLE_PEDIDOS dp
LEFT JOIN (
    SELECT DISTINCT ANO_EJE, SEC_EJEC, NRO_MOVIMTO
    FROM SIG_MOVIM_ALMACEN
    WHERE ANO_EJE = 2026 AND SEC_EJEC = 300687
      AND TIPO_MOVIMTO = 'S' AND TIPO_TRANSAC = 1
) ma ON ma.ANO_EJE = dp.ANO_EJE AND ma.SEC_EJEC = dp.SEC_EJEC
    AND ma.NRO_MOVIMTO = dp.NRO_PECOSA
WHERE dp.ANO_EJE = 2026 AND dp.SEC_EJEC = 300687 AND dp.TIPO_PEDIDO = '1';
