-- Caso pedido 286 (B y S) + CCMN 2530
SET NOCOUNT ON;

-- A. Cabecera cruda: ¿los campos "vacios" estan vacios en SIGA?
SELECT 'A_cabecera' AS q, TIPO_BIEN, TIPO_PEDIDO, ESTADO,
       CONVERT(varchar(10), FECHA_PEDIDO, 120) AS f_pedido,
       CONVERT(varchar(10), FECHA_APROB, 120) AS f_aprob,
       CONVERT(varchar(10), FECHA_ATENC, 120) AS f_atenc,
       LTRIM(RTRIM(NOMBRE_EMPLEADO)) AS solicitante,
       LTRIM(RTRIM(FUENTE_FINANC)) AS fuente,
       LTRIM(RTRIM(EMPLEADO)) AS empleado_cod
FROM SIG_PEDIDOS
WHERE ANO_EJE = 2026 AND SEC_EJEC = 300687 AND NRO_PEDIDO = 286;

-- B. Cobertura global de esos campos en pedidos de compra vivos
SELECT 'B_cobertura' AS q, COUNT(*) AS pedidos,
       SUM(CASE WHEN FECHA_APROB IS NOT NULL THEN 1 ELSE 0 END) AS con_f_aprob,
       SUM(CASE WHEN FECHA_ATENC IS NOT NULL THEN 1 ELSE 0 END) AS con_f_atenc,
       SUM(CASE WHEN NOMBRE_EMPLEADO IS NOT NULL AND LTRIM(RTRIM(NOMBRE_EMPLEADO)) <> '' THEN 1 ELSE 0 END) AS con_solicitante,
       SUM(CASE WHEN FUENTE_FINANC IS NOT NULL AND LTRIM(RTRIM(FUENTE_FINANC)) <> '' THEN 1 ELSE 0 END) AS con_fuente,
       SUM(CASE WHEN EMPLEADO IS NOT NULL THEN 1 ELSE 0 END) AS con_empleado_cod
FROM SIG_PEDIDOS
WHERE ANO_EJE = 2026 AND SEC_EJEC = 300687 AND TIPO_PEDIDO = '2'
  AND ESTADO IN ('0','1','7');

-- C. ¿El CCMN 2530 (B) tiene cuadro de adquisicion y orden?
SELECT 'C_ccmn_2530' AS q, ca.SEC_CUADRO,
       CONVERT(varchar(10), ca.FECHA_AUTORIZ, 120) AS f_autoriz,
       o.NRO_ORDEN, CONVERT(varchar(10), o.FECHA_ORDEN, 120) AS f_orden,
       o.TOTAL_FACT_SOLES, o.NRO_CERTIFICA, o.EXP_SIAF
FROM SIG_CUADRO_ADQUISICION ca
LEFT JOIN SIG_ORDEN_ADQUISICION o
    ON o.ANO_EJE = ca.ANO_EJE AND o.SEC_EJEC = ca.SEC_EJEC
   AND o.TIPO_BIEN = ca.TIPO_BIEN AND o.SEC_CUADRO = ca.SEC_CUADRO
WHERE ca.ANO_EJE = 2026 AND ca.SEC_EJEC = 300687
  AND ca.TIPO_BIEN = 'B' AND ca.NRO_CONS_PAAC = 2530;

-- D. Ordenes del 286/S encontradas por composite: ¿tienen SEC_CUADRO?
SELECT 'D_ordenes_286S' AS q, NRO_ORDEN, SEC_CUADRO, NRO_CERTIFICA,
       CONVERT(varchar(10), FECHA_ORDEN, 120) AS f_orden
FROM SIG_ORDEN_ADQUISICION
WHERE ANO_EJE = 2026 AND SEC_EJEC = 300687 AND TIPO_BIEN = 'S'
  AND NRO_ORDEN IN (238, 239, 240, 261, 608, 610);

-- E. Cobertura global de SEC_CUADRO en ordenes
SELECT 'E_sec_cuadro' AS q, TIPO_BIEN, COUNT(*) AS n,
       SUM(CASE WHEN SEC_CUADRO IS NOT NULL THEN 1 ELSE 0 END) AS con_sec_cuadro
FROM SIG_ORDEN_ADQUISICION
WHERE ANO_EJE = 2026 AND SEC_EJEC = 300687
GROUP BY TIPO_BIEN;
