-- ¿Que cadena tiene cada candidato del 286/B y 286/S?
SET NOCOUNT ON;

-- A. Cadena de los candidatos B (2530 y 3472): cotizacion, cuadro, orden
SELECT 'A_candidatos_B' AS q, pc.NRO_CONSOLID,
       CONVERT(varchar(10), pc.FECHA_CONS, 120) AS f_consolid,
       cot.F_COT, ca.SEC_CUADRO,
       CONVERT(varchar(10), ca.FECHA_AUTORIZ, 120) AS f_autoriz,
       o.NRO_ORDEN, CONVERT(varchar(10), o.FECHA_ORDEN, 120) AS f_orden
FROM SIG_PAAC_CONSOLIDADO pc
LEFT JOIN (
    SELECT NRO_CONSOLID, CONVERT(varchar(10), MIN(FECHA_REG), 120) AS F_COT
    FROM SIG_SOLICITUD_COTIZACION
    WHERE ANO_EJE = 2026 AND SEC_EJEC = 300687 AND tipo_bien = 'B'
    GROUP BY NRO_CONSOLID
) cot ON cot.NRO_CONSOLID = pc.NRO_CONSOLID
LEFT JOIN SIG_CUADRO_ADQUISICION ca
    ON ca.ANO_EJE = pc.ANO_EJE AND ca.SEC_EJEC = pc.SEC_EJEC
   AND ca.TIPO_BIEN = pc.TIPO_BIEN AND ca.NRO_CONS_PAAC = pc.NRO_CONSOLID
LEFT JOIN SIG_ORDEN_ADQUISICION o
    ON o.ANO_EJE = pc.ANO_EJE AND o.SEC_EJEC = pc.SEC_EJEC
   AND o.TIPO_BIEN = pc.TIPO_BIEN AND o.SEC_CUADRO = ca.SEC_CUADRO
WHERE pc.ANO_EJE = 2026 AND pc.SEC_EJEC = 300687
  AND pc.TIPO_BIEN = 'B' AND pc.NRO_CONSOLID IN (2530, 3472);

-- B. CCMN de cada orden composite del 286/S + cadena del declarado 3272
SELECT 'B_ordenes_S_ccmn' AS q, o.NRO_ORDEN, ca.NRO_CONS_PAAC
FROM SIG_ORDEN_ADQUISICION o
LEFT JOIN SIG_CUADRO_ADQUISICION ca
    ON ca.ANO_EJE = o.ANO_EJE AND ca.SEC_EJEC = o.SEC_EJEC
   AND ca.TIPO_BIEN = o.TIPO_BIEN AND ca.SEC_CUADRO = o.SEC_CUADRO
WHERE o.ANO_EJE = 2026 AND o.SEC_EJEC = 300687 AND o.TIPO_BIEN = 'S'
  AND o.NRO_ORDEN IN (238, 239, 240, 261, 608, 610);

SELECT 'C_ccmn_3272' AS q, ca.SEC_CUADRO,
       CONVERT(varchar(10), ca.FECHA_AUTORIZ, 120) AS f_autoriz,
       o.NRO_ORDEN, CONVERT(varchar(10), o.FECHA_ORDEN, 120) AS f_orden
FROM SIG_CUADRO_ADQUISICION ca
LEFT JOIN SIG_ORDEN_ADQUISICION o
    ON o.ANO_EJE = ca.ANO_EJE AND o.SEC_EJEC = ca.SEC_EJEC
   AND o.TIPO_BIEN = ca.TIPO_BIEN AND o.SEC_CUADRO = ca.SEC_CUADRO
WHERE ca.ANO_EJE = 2026 AND ca.SEC_EJEC = 300687
  AND ca.TIPO_BIEN = 'S' AND ca.NRO_CONS_PAAC = 3272;

-- D. ¿Existe maestro de personal para resolver EMPLEADO -> nombre?
SELECT 'D_personal' AS q, TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME LIKE '%PERSONAL%' OR TABLE_NAME LIKE '%EMPLEAD%';

-- E. Fuente de financiamiento: ¿en que tablas/columnas vive?
SELECT 'E_cols_fuente' AS q, TABLE_NAME, COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE (COLUMN_NAME LIKE '%FUENTE%' OR COLUMN_NAME LIKE '%FTE%')
  AND TABLE_NAME IN ('SIG_PEDIDOS','SIG_DETALLE_PEDIDOS','SIG_ORDEN_ADQUISICION',
                     'SIG_ORDEN_PRESUPUESTO','SIG_CERTIFICACION','SIG_CERTIFICACION_FASE',
                     'SIG_PAAC_CONSOLIDADO','SIG_CUADRO_ADQUISICION','META')
ORDER BY TABLE_NAME, COLUMN_NAME;

-- F. Seguimiento del 286/B: ¿hay estados con fecha (VB, aprobado)?
SELECT 'F_seguimiento_286B' AS q, s.TIPO_TRANSACCION, se.SEC_ESTADO,
       se.ESTADO_SEGUIMIENTO,
       CONVERT(varchar(16), se.FECHA_ESTADO, 120) AS f_estado,
       LTRIM(RTRIM(s.SOLICITANTE)) AS solicitante,
       LTRIM(RTRIM(se.CUSER_ID)) AS usuario
FROM SIG_SEGUIMIENTO s
JOIN SIG_SEGUIMIENTO_ESTADO se
  ON se.ANO_EJE = s.ANO_EJE AND se.SEC_EJEC = s.SEC_EJEC
 AND se.TIPO_TRANSACCION = s.TIPO_TRANSACCION AND se.NRO_ORIGEN = s.NRO_ORIGEN
WHERE s.ANO_EJE = 2026 AND s.SEC_EJEC = 300687
  AND s.NRO_PEDIDO = '000286' AND s.TIPO_BIEN = 'B'
ORDER BY se.FECHA_ESTADO;

-- G. Estados de atencion en los items del 286/B (tipo '2')
SELECT 'G_items_286B' AS q, SECUENCIA, ESTADO_PED, ESTADO_ATEND, ESTADO_CONFOR,
       ESTADO_COMPRA, NRO_PECOSA, SEC_CUA_MOD_SAL
FROM SIG_DETALLE_PEDIDOS
WHERE ANO_EJE = 2026 AND SEC_EJEC = 300687 AND TIPO_BIEN = 'B'
  AND TIPO_PEDIDO = '2' AND NRO_PEDIDO = 286;
