-- =====================================================================
-- Sesión 5 · Script 04
-- Reconstrucción de la cadena completa del testigo 232/S usando los
-- puentes descubiertos vía FKs:
--
--   SIG_DETALLE_PEDIDOS (SEC_CUADRO=1, SEC_ITEM=61, ANNO_PROG=2026)
--     → SIG_CUADRO_MODIFICADO_DET   (¿confirma?)
--     → SIG_CUADRO_MODIFICADO_SALDO (SEC_CUA_MOD_SAL=11553)
--
--   SIG_PAAC_CONSOLIDADO (NRO_CONSOLID=2266, TIPO_CONSOLID=?)
--     ├── sec_cuadro_ini      → 131 esperado
--     ├── NRO_CERTIFICA       → 182 esperado
--     ├── EXP_SIGA            → 152 esperado
--     ├── EXP_SIAF            → 316 esperado
--     ├── PROVEEDOR           → 1650 esperado
--     └── NRO_EST_MDO         → ¿263? (candidato al "EM 263")
--
--   SIG_ORDEN_SECUENCIA (NRO_ORDEN=132, TIPO_BIEN='S')
--     → timeline de fases presupuestales
-- =====================================================================

PRINT '=== 4.1 SIG_CUADRO_MODIFICADO_DET vinculado al detalle del pedido 232/S ===';
SELECT ANNO_EJEC, SEC_CUADRO, SEC_ITEM, ANNO_PROG, CENTRO_COSTO,
       ESTADO, PROCEDENCIA, FLAG_MODIFICADO, FLAG_SOLICITUD,
       CLASIFICADOR, TIPO_BIEN,
       GRUPO_BIEN, CLASE_BIEN, FAMILIA_BIEN, ITEM_BIEN,
       PRECIO_UNIT, CANT_TOTAL, MNTO_TOTAL,
       SEC_CUA_MOD_SAL, SEC_FUNC
FROM SIG_CUADRO_MODIFICADO_DET
WHERE SEC_EJEC=300687 AND ANNO_EJEC=2026
  AND SEC_CUADRO=1 AND SEC_ITEM=61 AND ANNO_PROG=2026;

PRINT '';
PRINT '=== 4.2 SIG_PAAC_CONSOLIDADO cabecera del CCMN 2266 ===';
SELECT TIPO_CONSOLID, NRO_CONSOLID, TIPO_GENERACION, ESTADO,
       FECHA_CONS, TIPO_BIEN, NRO_PAAC, FLAG_PAAC,
       TIPO_PROCESO, MODAL_COMPRA,
       sec_cuadro_ini, NRO_EST_MDO, FECHA_EST_MDO, ESTADO_EST_MDO,
       NRO_CERTIFICA, EXP_SIGA, EXP_SIAF, PROVEEDOR,
       NRO_CONSOLID_ORG, VALOR_PLAN, FLAG_CONCLUIDO
FROM SIG_PAAC_CONSOLIDADO
WHERE ANO_EJE=2026 AND SEC_EJEC=300687
  AND TIPO_BIEN='S' AND NRO_CONSOLID=2266;

PRINT '';
PRINT '=== 4.3 SIG_PAAC_ITEM detalle del CCMN 2266 ===';
SELECT TOP 10 TIPO_CONSOLID, NRO_CONSOLID, TIPO_GENERACION, TIPO_BIEN,
       SEC_CONSOLID, SEC_RESUMEN, SECUENCIA,
       GRUPO_BIEN, CLASE_BIEN, FAMILIA_BIEN, ITEM_BIEN,
       CANTIDAD, UNIDAD_MEDIDA, PRECIO_UNIT, VALOR
FROM SIG_PAAC_ITEM
WHERE ANO_EJE=2026 AND SEC_EJEC=300687
  AND NRO_CONSOLID=2266;

PRINT '';
PRINT '=== 4.4 SIG_ORDEN_SECUENCIA timeline de la orden 132/S ===';
SELECT SEC_ORDEN, ANO_SECUENCIA, MES_SECUENCIA,
       FASE_ORDEN, ESTADO_FASE, FECHA_ESTADO,
       DOCUMTO_SIAF, NRO_DOCUMTO, FLAG_COMPROMETIDO,
       FECHA_REG, CUSER_ID
FROM SIG_ORDEN_SECUENCIA
WHERE ANO_EJE=2026 AND SEC_EJEC=300687
  AND TIPO_BIEN='S' AND NRO_ORDEN=132
ORDER BY SEC_ORDEN;

PRINT '';
PRINT '=== 4.5 SIG_DEVENGADO vinculado a la orden 132/S ===';
SELECT NRO_DEVENGADO, NRO_ORDEN, TIPO_BIEN, TIPO_PPTO,
       FECHA_REG, CUSER_ID
FROM SIG_DEVENGADO
WHERE ANO_EJE=2026 AND SEC_EJEC=300687
  AND TIPO_BIEN='S' AND NRO_ORDEN=132
ORDER BY NRO_DEVENGADO;

PRINT '';
PRINT '=== 4.6 SIG_EXP_SIGA_DOCU documentos del expediente 152 ===';
SELECT EXP_SIGA_DOC, TIPO_DOCUMENTO, NRO_DOCUMENTO, FECHA_DOCUMENTO,
       TIPO_OPERACION, MODAL_COMPRA, FASE_CONTRACTUAL,
       EXP_SIAF, FECHA_INTERFASE, FECHA_REG
FROM SIG_EXP_SIGA_DOCU
WHERE ANO_EJE=2026 AND SEC_EJEC=300687
  AND EXP_SIGA=152
ORDER BY EXP_SIGA_DOC;

PRINT '';
PRINT '=== 4.7 SIG_EXP_SIGA_PPTO detalle presupuestal del expediente 152 ===';
SELECT EXP_SIGA_DOC, EXP_SIGA_SECU, EXP_SIGA_PPTO,
       SEC_FUNC, CLASIFICADOR, ID_CLASIFICADOR,
       VALOR_SOLES, MNTO_SOLES, EXPEDIENTE
FROM SIG_EXP_SIGA_PPTO
WHERE ANO_EJE=2026 AND SEC_EJEC=300687
  AND EXP_SIGA=152
ORDER BY EXP_SIGA_DOC, EXP_SIGA_SECU, EXP_SIGA_PPTO;
