-- =====================================================================
-- Sesión 5 · Script 06
-- Verificar tablas candidatas a ser puente pedido ↔ PAAC en el testigo.
-- =====================================================================

PRINT '=== 6.1 Columnas de SIG_PAAC_CENTRO_COSTO ===';
SELECT ORDINAL_POSITION AS pos, COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'SIG_PAAC_CENTRO_COSTO'
ORDER BY ORDINAL_POSITION;

PRINT '';
PRINT '=== 6.2 Fill rate SIG_PAAC_CENTRO_COSTO en 2026/300687 ===';
SELECT COUNT(*) AS filas,
       COUNT(NRO_CONSOLID) AS con_consolid,
       COUNT(NRO_PEDIDO)   AS con_pedido,
       SUM(CASE WHEN NRO_PEDIDO IS NOT NULL AND LTRIM(RTRIM(NRO_PEDIDO))<>'' THEN 1 ELSE 0 END) AS pedido_no_vacio
FROM SIG_PAAC_CENTRO_COSTO
WHERE ANO_EJE=2026 AND SEC_EJEC=300687;

PRINT '';
PRINT '=== 6.3 SIG_PAAC_CENTRO_COSTO donde NRO_CONSOLID=2266 ===';
SELECT TOP 30 *
FROM SIG_PAAC_CENTRO_COSTO
WHERE ANO_EJE=2026 AND SEC_EJEC=300687
  AND NRO_CONSOLID=2266;

PRINT '';
PRINT '=== 6.4 SIG_PAAC_CENTRO_COSTO donde NRO_PEDIDO=232 (con cualquier padding) ===';
SELECT TOP 30 *
FROM SIG_PAAC_CENTRO_COSTO
WHERE ANO_EJE=2026 AND SEC_EJEC=300687
  AND (NRO_PEDIDO IN ('232','0232','00232','000232') OR TRY_CAST(NRO_PEDIDO AS INT)=232);

PRINT '';
PRINT '=== 6.5 Columnas de SIG_DETALLE_CUADRO_ANUAL ===';
SELECT ORDINAL_POSITION AS pos, COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'SIG_DETALLE_CUADRO_ANUAL'
ORDER BY ORDINAL_POSITION;

PRINT '';
PRINT '=== 6.6 Fill rate SIG_DETALLE_CUADRO_ANUAL en 2026/300687 ===';
SELECT COUNT(*) AS filas,
       COUNT(nro_consolid) AS con_consolid,
       COUNT(NRO_PEDIDO)   AS con_pedido
FROM SIG_DETALLE_CUADRO_ANUAL
WHERE ANO_EJE=2026 AND SEC_EJEC=300687;

PRINT '';
PRINT '=== 6.7 SIG_DETALLE_CUADRO_ANUAL donde nro_consolid=2266 O NRO_PEDIDO~232 ===';
SELECT TOP 20 *
FROM SIG_DETALLE_CUADRO_ANUAL
WHERE ANO_EJE=2026 AND SEC_EJEC=300687
  AND (nro_consolid=2266
    OR NRO_PEDIDO IN ('232','0232','00232','000232')
    OR TRY_CAST(NRO_PEDIDO AS INT)=232);
