-- =====================================================================
-- Sesión 5 · Script 09
-- Verificar puentes nuevos contra el testigo 232/S:
--   - SIG_CUADRO_MODIFICADO_CMN (SEC_CUA_MOD_SAL=11553 y/o NRO_CONSOLID=2266)
--   - SIG_CONTRATOS (NRO_CONSOLID=2266)
--   - SIG_ORDEN_ITEM / SIG_ORDEN_ITEM_PPTO / SIG_ORDEN_PRESUPUESTO (NRO_ORDEN=132)
--   - SIG_PAAC_METAS (NRO_CONSOLID=2266)
--   - SIG_PAAC_DET (NRO_CONSOLID=2266)
--   - SIG_PAAC_SECUENCIA (NRO_CONSOLID=2266)
--   - SIG_SOLICITUD_ESPECIFICACIONES (NRO_CONSOLID=2266)
--   - SIG_CERTIFICACION_OPER_FUENTE (NRO_CERTIFICA=182)
-- =====================================================================

PRINT '=== 9.1 SIG_CUADRO_MODIFICADO_CMN: puente SEC_CUA_MOD_SAL ↔ NRO_CONSOLID ===';
PRINT '  9.1.a) Por SEC_CUA_MOD_SAL=11553 (partida del pedido 232/S):';
SELECT * FROM SIG_CUADRO_MODIFICADO_CMN
WHERE SEC_EJEC=300687 AND ANNO_EJEC=2026
  AND SEC_CUA_MOD_SAL=11553;

PRINT '  9.1.b) Por NRO_CONSOLID=2266 (CCMN del testigo):';
SELECT * FROM SIG_CUADRO_MODIFICADO_CMN
WHERE SEC_EJEC=300687 AND ANNO_EJEC=2026
  AND NRO_CONSOLID=2266;

PRINT '';
PRINT '=== 9.2 SIG_CONTRATOS del CCMN 2266 ===';
SELECT * FROM SIG_CONTRATOS
WHERE ANO_EJE=2026 AND SEC_EJEC=300687
  AND (NRO_CONSOLID=2266 OR NRO_CERTIFICA=182);

PRINT '';
PRINT '=== 9.3 SIG_ORDEN_ITEM de la orden 132/S ===';
SELECT * FROM SIG_ORDEN_ITEM
WHERE ANO_EJE=2026 AND SEC_EJEC=300687
  AND TIPO_BIEN='S' AND NRO_ORDEN=132;

PRINT '';
PRINT '=== 9.4 SIG_ORDEN_ITEM_PPTO de la orden 132/S ===';
SELECT * FROM SIG_ORDEN_ITEM_PPTO
WHERE ANO_EJE=2026 AND SEC_EJEC=300687
  AND TIPO_BIEN='S' AND NRO_ORDEN=132;

PRINT '';
PRINT '=== 9.5 SIG_ORDEN_PRESUPUESTO de la orden 132/S ===';
SELECT * FROM SIG_ORDEN_PRESUPUESTO
WHERE ANO_EJE=2026 AND SEC_EJEC=300687
  AND TIPO_BIEN='S' AND NRO_ORDEN=132;

PRINT '';
PRINT '=== 9.6 SIG_PAAC_METAS del CCMN 2266 ===';
SELECT * FROM SIG_PAAC_METAS
WHERE ANO_EJE=2026 AND sec_ejec=300687
  AND NRO_CONSOLID=2266;

PRINT '';
PRINT '=== 9.7 SIG_PAAC_DET del CCMN 2266 ===';
SELECT * FROM SIG_PAAC_DET
WHERE ANO_EJE=2026 AND SEC_EJEC=300687
  AND NRO_CONSOLID=2266;

PRINT '';
PRINT '=== 9.8 SIG_PAAC_SECUENCIA del CCMN 2266 ===';
SELECT * FROM SIG_PAAC_SECUENCIA
WHERE ANO_EJE=2026 AND SEC_EJEC=300687
  AND NRO_CONSOLID=2266
ORDER BY FECHA_REG;

PRINT '';
PRINT '=== 9.9 SIG_SOLICITUD_ESPECIFICACIONES del CCMN 2266 ===';
SELECT * FROM SIG_SOLICITUD_ESPECIFICACIONES
WHERE ANO_EJE=2026 AND SEC_EJEC=300687
  AND NRO_CONSOLID=2266;

PRINT '';
PRINT '=== 9.10 SIG_CERTIFICACION_OPER_FUENTE de la cert 182 ===';
SELECT * FROM SIG_CERTIFICACION_OPER_FUENTE
WHERE ANO_EJE=2026 AND SEC_EJEC=300687
  AND NRO_CERTIFICA=182;
