-- =====================================================================
-- Sesión 5 · Script 11
-- Recontacto con SIG_SEGUIMIENTO (el doc original la descartó a 0 filas,
-- pero el script 10 encontró 7 filas para NRO_PEDIDO=232) y volcado de
-- las tablas nuevas de la familia PAAC_DET_*.
-- =====================================================================

PRINT '=== 11.1 SIG_SEGUIMIENTO — todo lo que apunta al pedido 232 ===';
SELECT *
FROM SIG_SEGUIMIENTO
WHERE ANO_EJE=2026 AND SEC_EJEC=300687
  AND TRY_CAST(NRO_PEDIDO AS INT)=232;

PRINT '';
PRINT '=== 11.2 SIG_SEGUIMIENTO — todo lo que apunta al CCMN 2266 (por NRO_CONSOLID) ===';
SELECT *
FROM SIG_SEGUIMIENTO
WHERE ANO_EJE=2026 AND SEC_EJEC=300687
  AND NRO_CONSOLID=2266;

PRINT '';
PRINT '=== 11.3 SIG_PAAC_DET_DEPE ===';
SELECT * FROM SIG_PAAC_DET_DEPE
WHERE ANO_EJE=2026 AND SEC_EJEC=300687
  AND NRO_CONSOLID=2266;

PRINT '';
PRINT '=== 11.4 SIG_PAAC_DET_PPTAL ===';
SELECT * FROM SIG_PAAC_DET_PPTAL
WHERE ANO_EJE=2026 AND SEC_EJEC=300687
  AND NRO_CONSOLID=2266;

PRINT '';
PRINT '=== 11.5 SIG_PAAC_DET_SECUENCIA ===';
SELECT * FROM SIG_PAAC_DET_SECUENCIA
WHERE ANO_EJE=2026 AND SEC_EJEC=300687
  AND NRO_CONSOLID=2266
ORDER BY FECHA_REG;

PRINT '';
PRINT '=== 11.6 SIG_CERTIFICACION_DOC de la cert 182 ===';
SELECT * FROM SIG_CERTIFICACION_DOC
WHERE ANO_EJE=2026 AND SEC_EJEC=300687
  AND NRO_CERTIFICA=182;

PRINT '';
PRINT '=== 11.7 SIG_EXP_SIGA para el CCMN 2266 (aparece en §10.2 con 1 fila) ===';
SELECT * FROM SIG_EXP_SIGA
WHERE ANO_EJE=2026 AND SEC_EJEC=300687
  AND NRO_CONSOLID=2266;
