-- =====================================================================
-- Sesión 5 · Script 12
-- Testigo 005/B (bien cerrado): pedido 005/B, cuadro 4/B, orden 003/B,
-- cert 79, cert SIAF 106, EXP_SIGA 59, EXP_SIAF 179, NRO_PECOSA=4,
-- proveedor 2217, monto 5.805.
--
-- Aplicar la misma cadena descubierta con el 232/S y añadir el flujo
-- pecosa que en bienes es la etapa final crítica.
-- =====================================================================

PRINT '=== 12.1 Cabecera pedido 005/B ===';
SELECT NRO_PEDIDO, TIPO_PEDIDO, TIPO_BIEN, ESTADO,
       FECHA_PEDIDO, CENTRO_COSTO, SEC_FUNC
FROM SIG_PEDIDOS
WHERE ANO_EJE=2026 AND SEC_EJEC=300687
  AND TIPO_BIEN='B' AND CAST(NRO_PEDIDO AS INT)=5;

PRINT '';
PRINT '=== 12.2 Detalle pedido 005/B (con NRO_PECOSA, NRO_ORDEN, SEC_CUA_MOD_SAL) ===';
SELECT SECUENCIA, GRUPO_BIEN, CLASE_BIEN, FAMILIA_BIEN, ITEM_BIEN,
       CANT_SOLICITADA, CANT_ATENDIDA, PRECIO_UNIT, VALOR_TOTAL,
       NRO_PECOSA, NRO_ORDEN,
       SEC_CUADRO, SEC_ITEM, ANNO_PROG, SEC_CUA_MOD_SAL,
       CLASIFICADOR, CENTRO_COSTO, FECHA_APROB, FECHA_PECOSA
FROM SIG_DETALLE_PEDIDOS
WHERE ANO_EJE=2026 AND sec_ejec=300687
  AND TIPO_BIEN='B' AND CAST(NRO_PEDIDO AS INT)=5
ORDER BY SECUENCIA;

PRINT '';
PRINT '=== 12.3 SIG_SEGUIMIENTO del pedido 005/B (esperado: 5-7 filas, no 0 como decía el doc) ===';
SELECT TIPO_TRANSACCION, NRO_ORIGEN, NRO_PEDIDO, NRO_CONSOLID,
       NRO_TRANSACCION, TIPO_BIEN, TIPO_PEDIDO, TIPO_CONSOLID,
       CENTRO_COSTO, FECHA_TRANSACCION, ESTADO_TRANSACCION,
       CUSER_ID, FECHA_REG, sec_transaccion
FROM SIG_SEGUIMIENTO
WHERE ANO_EJE=2026 AND SEC_EJEC=300687
  AND TRY_CAST(NRO_PEDIDO AS INT)=5 AND TIPO_BIEN='B'
ORDER BY FECHA_REG;

PRINT '';
PRINT '=== 12.4 Puente pedido 005/B → PAAC via SIG_CUADRO_MODIFICADO_CMN ===';
SELECT DISTINCT cmn.SEC_CUA_MOD_SAL, cmn.TIPO_CONSOLID, cmn.NRO_CONSOLID,
       pc.FECHA_CONS, pc.NRO_EST_MDO, pc.NRO_CERTIFICA,
       pc.VALOR_PLAN, pc.FLAG_CONCLUIDO, pc.PROVEEDOR
FROM SIG_DETALLE_PEDIDOS dp
INNER JOIN SIG_CUADRO_MODIFICADO_CMN cmn
    ON cmn.SEC_EJEC=dp.sec_ejec
   AND cmn.ANNO_EJEC=dp.ANO_EJE
   AND cmn.SEC_CUA_MOD_SAL=dp.SEC_CUA_MOD_SAL
   AND cmn.TIPO_BIEN=dp.TIPO_BIEN
LEFT JOIN SIG_PAAC_CONSOLIDADO pc
    ON pc.ANO_EJE=cmn.ANNO_EJEC AND pc.SEC_EJEC=cmn.SEC_EJEC
   AND pc.TIPO_CONSOLID=cmn.TIPO_CONSOLID
   AND pc.NRO_CONSOLID=cmn.NRO_CONSOLID
   AND pc.TIPO_BIEN=cmn.TIPO_BIEN
WHERE dp.ANO_EJE=2026 AND dp.sec_ejec=300687
  AND dp.TIPO_BIEN='B' AND CAST(dp.NRO_PEDIDO AS INT)=5;

PRINT '';
PRINT '=== 12.5 Cuadro adquisición 4/B ===';
SELECT SEC_CUADRO, TIPO_BIEN, NRO_CONS_PAAC, FECHA_CUADRO,
       TIPO_GENERACION, FLAG_ORIGEN, FLAG_PROCESO, TIPO_PROCESO
FROM SIG_CUADRO_ADQUISICION
WHERE ANO_EJE=2026 AND SEC_EJEC=300687
  AND TIPO_BIEN='B' AND SEC_CUADRO=4;

PRINT '';
PRINT '=== 12.6 Orden 003/B ===';
SELECT NRO_ORDEN, TIPO_BIEN, SEC_CUADRO, NRO_CERTIFICA,
       EXP_SIGA, EXP_SIAF, TOTAL_FACT_SOLES, PROVEEDOR,
       FECHA_ORDEN, ESTADO_SIAF
FROM SIG_ORDEN_ADQUISICION
WHERE ANO_EJE=2026 AND SEC_EJEC=300687
  AND TIPO_BIEN='B' AND NRO_ORDEN=3;

PRINT '';
PRINT '=== 12.7 SIG_ORDEN_ITEM de la orden 003/B (con descripción libre) ===';
SELECT SEC_ORDEN, SEC_ITEM,
       GRUPO_BIEN, CLASE_BIEN, FAMILIA_BIEN, ITEM_BIEN,
       CANT_ITEM, UNIDAD_MEDIDA, PREC_TOT_SOLES,
       CANT_RECIBIDA, FECHA_RECEP,
       LEFT(CAST(ESPECIFICACIONES AS varchar(400)), 400) AS especificaciones
FROM SIG_ORDEN_ITEM
WHERE ANO_EJE=2026 AND SEC_EJEC=300687
  AND TIPO_BIEN='B' AND NRO_ORDEN=3
ORDER BY SEC_ORDEN, SEC_ITEM;

PRINT '';
PRINT '=== 12.8 Timeline fases orden 003/B ===';
SELECT SEC_ORDEN, ANO_SECUENCIA, MES_SECUENCIA,
       FASE_ORDEN, ESTADO_FASE, FECHA_ESTADO,
       DOCUMTO_SIAF, NRO_DOCUMTO, FLAG_COMPROMETIDO,
       FECHA_REG, CUSER_ID
FROM SIG_ORDEN_SECUENCIA
WHERE ANO_EJE=2026 AND SEC_EJEC=300687
  AND TIPO_BIEN='B' AND NRO_ORDEN=3
ORDER BY SEC_ORDEN;

PRINT '';
PRINT '=== 12.9 Certificación 79/B ===';
SELECT NRO_CERTIFICA, NRO_CERTIFICA_SIAF, ESTADO_CERTIFICA_SIAF,
       FECHA, TIPO_CERTIFICACION, CONCLUIDO
FROM SIG_CERTIFICACION
WHERE ANO_EJE=2026 AND SEC_EJEC=300687
  AND NRO_CERTIFICA=79;

PRINT '';
PRINT '=== 12.10 Fases certificación 79 ===';
SELECT SECUENCIA_FASE, SEC_FASE, NRO_ORDEN, TIPO_BIEN,
       NRO_CONSOLID, TIPO_CONSOLID, TIPO_GENERACION,
       VALOR_SOLES, NRO_CERTIFICA_SIAF, ESTADO_CERTIFICA_SIAF,
       FLAG_COMPROMETIDO, FECHA_REG
FROM SIG_CERTIFICACION_FASE
WHERE ANO_EJE=2026 AND SEC_EJEC=300687
  AND NRO_CERTIFICA=79
ORDER BY SECUENCIA_FASE;

PRINT '';
PRINT '=== 12.11 SIG_CERTIFICACION_OPER_FUENTE cert 79 (timeline por usuario) ===';
SELECT SECUENCIA_FASE, SECUENCIA_OPERA, SECUENCIA_DET,
       FUENTE_FINANC, VALOR_SOLES, FECHA_REG, CUSER_ID,
       SEC_INTF_SIAF, ESTADO_SIAF
FROM SIG_CERTIFICACION_OPER_FUENTE
WHERE ANO_EJE=2026 AND SEC_EJEC=300687
  AND NRO_CERTIFICA=79
ORDER BY SECUENCIA_FASE, SECUENCIA_OPERA;

PRINT '';
PRINT '=== 12.12 Expediente SIGA 59 ===';
SELECT EXP_SIGA, EXP_SIAF, TIPO_FASE, ESTADO,
       TIPO_CONSOLID, NRO_CONSOLID, PROVEEDOR,
       TIPO_DOCUMENTO, NRO_DOCUMENTO, FECHA_DOCUMENTO,
       FECHA_REG, CUSER_ID
FROM SIG_EXP_SIGA
WHERE ANO_EJE=2026 AND SEC_EJEC=300687
  AND EXP_SIGA=59;

PRINT '';
PRINT '=== 12.13 SIG_EXP_SIGA_DOCU del EXP_SIGA=59 ===';
SELECT EXP_SIGA_DOC, TIPO_DOCUMENTO, NRO_DOCUMENTO, FECHA_DOCUMENTO,
       TIPO_OPERACION, MODAL_COMPRA, FASE_CONTRACTUAL,
       EXP_SIAF, FECHA_INTERFASE, FECHA_REG
FROM SIG_EXP_SIGA_DOCU
WHERE ANO_EJE=2026 AND SEC_EJEC=300687
  AND EXP_SIGA=59
ORDER BY EXP_SIGA_DOC;
