-- =====================================================================
-- Sesión 5 · Script 13 (corregido con estructura real)
-- Flujo pecosa para el testigo 005/B.
-- =====================================================================

PRINT '=== 13.1 Tablas con NRO_PECOSA ===';
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME LIKE '%PECOSA%'
  AND TABLE_NAME NOT LIKE 'TEMP_%'
  AND TABLE_NAME NOT LIKE 'tmp%'
  AND TABLE_NAME NOT LIKE 'V_%'
  AND TABLE_NAME NOT LIKE 'SGE_%'
ORDER BY TABLE_NAME, COLUMN_NAME;

PRINT '';
PRINT '=== 13.2 SIG_MOVIM_ALMACEN de la orden 003/B ===';
SELECT SEC_ALMACEN, TIPO_MOVIMTO, TIPO_TRANSAC, NRO_MOVIMTO,
       ANO_ORDEN, NRO_ORDEN, PROVEEDOR,
       FECHA_ENTRADA, FECHA_MOVIMTO, MES_MOVIMTO,
       INDI_CONFOR, ESTADO_KARDEX, ESTADO_DEVENG,
       EXPEDIENTE_SIAF, SECUENCIA_SIAF,
       TIPO_DOCUMTO, NRO_GUIA, NRO_FACTURA,
       FECHA_REG, CUSER_ID
FROM SIG_MOVIM_ALMACEN
WHERE ANO_EJE=2026 AND SEC_EJEC=300687
  AND NRO_ORDEN=3 AND TIPO_BIEN='B'
ORDER BY FECHA_MOVIMTO, TIPO_MOVIMTO;

PRINT '';
PRINT '=== 13.3 SIG_DETALLE_PECOSA para pedido 005/B ===';
SELECT * FROM SIG_DETALLE_PECOSA
WHERE ANO_EJE=2026 AND sec_ejec=300687
  AND TIPO_BIEN='B' AND CAST(NRO_PEDIDO AS INT)=5
ORDER BY SECUENCIA;

PRINT '';
PRINT '=== 13.4 Tipos de movimiento almacén (catálogo) ===';
SELECT TIPO_MOVIMTO, TIPO_TRANSAC, NOMBRE_MOVIMTO, ABREV_MOVIMTO,
       IND_ALMACEN, IND_ACTIVO, IND_SALIDA
FROM SIG_TIPO_MOVIMIENTO
ORDER BY TIPO_MOVIMTO, TIPO_TRANSAC;

PRINT '';
PRINT '=== 13.5 SIG_DETALLE_MOVIM_ALMACEN de movimientos orden 3/B ===';
SELECT dma.TIPO_MOVIMTO, dma.TIPO_TRANSAC, dma.NRO_MOVIMTO,
       dma.SECUENCIA, dma.SEC_DETALLE, dma.SEC_ITEM,
       dma.CENTRO_COSTO, dma.CLASIFICADOR,
       dma.GRUPO_BIEN, dma.CLASE_BIEN, dma.FAMILIA_BIEN, dma.ITEM_BIEN,
       dma.CANT_ADQUIRIDO, dma.CANT_RECIBIDO, dma.CANT_ATENDIDA,
       dma.PRECIO_UNIT, dma.VALOR_TOTAL,
       dma.FECHA_MOVIMTO, dma.MES_PROCESO
FROM SIG_DETALLE_MOVIM_ALMACEN dma
INNER JOIN SIG_MOVIM_ALMACEN ma
    ON ma.SEC_EJEC=dma.sec_ejec AND ma.ANO_EJE=dma.ANO_EJE
   AND ma.TIPO_MOVIMTO=dma.TIPO_MOVIMTO AND ma.TIPO_TRANSAC=dma.TIPO_TRANSAC
   AND ma.NRO_MOVIMTO=dma.NRO_MOVIMTO AND ma.TIPO_BIEN=dma.TIPO_BIEN
WHERE ma.ANO_EJE=2026 AND ma.SEC_EJEC=300687
  AND ma.NRO_ORDEN=3 AND ma.TIPO_BIEN='B'
ORDER BY dma.FECHA_MOVIMTO, dma.SECUENCIA, dma.SEC_ITEM;

PRINT '';
PRINT '=== 13.6 Pedido 010/B (que aparece en descripción de orden 003/B) ===';
SELECT NRO_PEDIDO, TIPO_PEDIDO, TIPO_BIEN, ESTADO,
       FECHA_PEDIDO, CENTRO_COSTO, SEC_FUNC
FROM SIG_PEDIDOS
WHERE ANO_EJE=2026 AND SEC_EJEC=300687
  AND TIPO_BIEN='B' AND CAST(NRO_PEDIDO AS INT)=10;

PRINT '';
PRINT '=== 13.7 Detalle pedido 010/B ===';
SELECT SECUENCIA, GRUPO_BIEN, CLASE_BIEN, FAMILIA_BIEN, ITEM_BIEN,
       VALOR_TOTAL, NRO_PECOSA, NRO_ORDEN,
       SEC_CUADRO, SEC_ITEM, ANNO_PROG, SEC_CUA_MOD_SAL,
       CLASIFICADOR, CENTRO_COSTO
FROM SIG_DETALLE_PEDIDOS
WHERE ANO_EJE=2026 AND sec_ejec=300687
  AND TIPO_BIEN='B' AND CAST(NRO_PEDIDO AS INT)=10
ORDER BY SECUENCIA;

PRINT '';
PRINT '=== 13.8 Puente pedido 010/B → PAAC ===';
SELECT DISTINCT cmn.SEC_CUA_MOD_SAL, cmn.NRO_CONSOLID,
       pc.FECHA_CONS, pc.NRO_EST_MDO, pc.NRO_CERTIFICA,
       pc.VALOR_PLAN
FROM SIG_DETALLE_PEDIDOS dp
INNER JOIN SIG_CUADRO_MODIFICADO_CMN cmn
    ON cmn.SEC_EJEC=dp.sec_ejec AND cmn.ANNO_EJEC=dp.ANO_EJE
   AND cmn.SEC_CUA_MOD_SAL=dp.SEC_CUA_MOD_SAL
   AND cmn.TIPO_BIEN=dp.TIPO_BIEN
LEFT JOIN SIG_PAAC_CONSOLIDADO pc
    ON pc.ANO_EJE=cmn.ANNO_EJEC AND pc.SEC_EJEC=cmn.SEC_EJEC
   AND pc.TIPO_CONSOLID=cmn.TIPO_CONSOLID
   AND pc.NRO_CONSOLID=cmn.NRO_CONSOLID
   AND pc.TIPO_BIEN=cmn.TIPO_BIEN
WHERE dp.ANO_EJE=2026 AND dp.sec_ejec=300687
  AND dp.TIPO_BIEN='B' AND CAST(dp.NRO_PEDIDO AS INT)=10;
