-- =====================================================================
-- Sesión 5 · Script 14
-- Cerrar el ciclo pecosa del 005/B:
--   - Encontrar el movimiento (S,1) "DESPACHO AL USUARIO" con NRO_PECOSA=4
--   - Confirmar la doble naturaleza del pedido: 005/B TIPO_PEDIDO=1
--     es un PEDIDO INTERNO DE ALMACEN (no una compra),
--     y consume el stock ingresado por la orden 003/B via 010/B TIPO_PEDIDO=2.
--   - Descifrar TIPO_TRANSACCION=4 y 31 en SIG_SEGUIMIENTO.
-- =====================================================================

PRINT '=== 14.1 SIG_MOVIM_ALMACEN con NRO_PECOSA=4 (salida a usuario) ===';
SELECT SEC_ALMACEN, TIPO_MOVIMTO, TIPO_TRANSAC, NRO_MOVIMTO,
       ANO_ORDEN, NRO_ORDEN, PROVEEDOR,
       CENTRO_COSTO, RESPONSABLE,
       FECHA_MOVIMTO, FECHA_ENTRADA, MES_MOVIMTO,
       INDI_CONFOR, ESTADO_KARDEX,
       TIPO_DOCUMTO, NRO_GUIA, NRO_FACTURA,
       FECHA_REG, CUSER_ID
FROM SIG_MOVIM_ALMACEN
WHERE ANO_EJE=2026 AND SEC_EJEC=300687
  AND TIPO_BIEN='B'
  AND TIPO_MOVIMTO='S'
  AND NRO_MOVIMTO=4;

PRINT '';
PRINT '=== 14.2 SIG_DETALLE_MOVIM_ALMACEN del despacho (S,1) NRO_MOVIMTO=4 ===';
SELECT TIPO_MOVIMTO, TIPO_TRANSAC, NRO_MOVIMTO,
       SECUENCIA, SEC_DETALLE, SEC_ITEM,
       CENTRO_COSTO, CLASIFICADOR,
       GRUPO_BIEN, CLASE_BIEN, FAMILIA_BIEN, ITEM_BIEN,
       CANT_ADQUIRIDO, CANT_RECIBIDO, CANT_ATENDIDA,
       PRECIO_UNIT, VALOR_TOTAL,
       FECHA_MOVIMTO, MES_PROCESO
FROM SIG_DETALLE_MOVIM_ALMACEN
WHERE ANO_EJE=2026 AND sec_ejec=300687
  AND TIPO_BIEN='B'
  AND TIPO_MOVIMTO='S' AND TIPO_TRANSAC=1
  AND NRO_MOVIMTO=4
ORDER BY SECUENCIA, SEC_ITEM;

PRINT '';
PRINT '=== 14.3 SIG_PEDIDO_PECOSA_IMPRESION para la pecosa nro 4 ===';
SELECT * FROM SIG_PEDIDO_PECOSA_IMPRESION
WHERE ANO_EJE=2026 AND SEC_EJEC=300687
  AND TIPO_BIEN='B' AND NRO_PECOSA=4;

PRINT '';
PRINT '=== 14.4 Cabecera pedidos 005/B con FLAG_PED_PECOSA y EMPLEADO_PECOSA ===';
SELECT NRO_PEDIDO, TIPO_PEDIDO, TIPO_BIEN, ESTADO,
       FECHA_PEDIDO, CENTRO_COSTO, SEC_FUNC,
       FLAG_PED_PECOSA, EMPLEADO_PECOSA
FROM SIG_PEDIDOS
WHERE ANO_EJE=2026 AND SEC_EJEC=300687
  AND TIPO_BIEN='B' AND CAST(NRO_PEDIDO AS INT)=5;

PRINT '';
PRINT '=== 14.5 SIG_SEGUIMIENTO tipos 4 y 31 — semántica ===';
PRINT '  14.5.a) Ejemplos de TIPO_TRANSACCION=4 en 2026:';
SELECT TOP 10 TIPO_TRANSACCION, NRO_ORIGEN, NRO_PEDIDO, NRO_CONSOLID,
       NRO_TRANSACCION, TIPO_BIEN, TIPO_PEDIDO, TIPO_CONSOLID,
       CENTRO_COSTO, FECHA_TRANSACCION, ESTADO_TRANSACCION,
       CUSER_ID, FECHA_REG
FROM SIG_SEGUIMIENTO
WHERE ANO_EJE=2026 AND SEC_EJEC=300687
  AND TIPO_TRANSACCION=4;

PRINT '  14.5.b) Ejemplos de TIPO_TRANSACCION=31 en 2026:';
SELECT TOP 10 TIPO_TRANSACCION, NRO_ORIGEN, NRO_PEDIDO, NRO_CONSOLID,
       NRO_TRANSACCION, TIPO_BIEN, TIPO_PEDIDO, TIPO_CONSOLID,
       CENTRO_COSTO, FECHA_TRANSACCION, ESTADO_TRANSACCION,
       CUSER_ID, FECHA_REG
FROM SIG_SEGUIMIENTO
WHERE ANO_EJE=2026 AND SEC_EJEC=300687
  AND TIPO_TRANSACCION=31;

PRINT '  14.5.c) Semántica TIPO=4 - conteo por combinación de banderas:';
SELECT TIPO_TRANSACCION, TIPO_BIEN, TIPO_PEDIDO, TIPO_CONSOLID,
       ESTADO_TRANSACCION, COUNT(*) AS n
FROM SIG_SEGUIMIENTO
WHERE ANO_EJE=2026 AND SEC_EJEC=300687
  AND TIPO_TRANSACCION IN (4,5,7,15,26,31,33,34,35)
GROUP BY TIPO_TRANSACCION, TIPO_BIEN, TIPO_PEDIDO, TIPO_CONSOLID, ESTADO_TRANSACCION
ORDER BY TIPO_TRANSACCION, n DESC;

PRINT '';
PRINT '=== 14.6 ¿Cómo se enlaza pedido 005/B TIPO=1 al ingreso R o al orden 003/B? ===';
PRINT '  14.6.a) Movimientos I,R con NRO_MOVIMTO=4 (ingresos previos a la pecosa 4):';
SELECT TIPO_MOVIMTO, TIPO_TRANSAC, NRO_MOVIMTO, ANO_ORDEN, NRO_ORDEN,
       PROVEEDOR, FECHA_MOVIMTO, TIPO_DOCUMTO, NRO_GUIA
FROM SIG_MOVIM_ALMACEN
WHERE ANO_EJE=2026 AND SEC_EJEC=300687 AND TIPO_BIEN='B'
  AND NRO_MOVIMTO=4
ORDER BY TIPO_MOVIMTO;
