"""Aumentar longitud de etapa_f8 en inversiones

Revision ID: 1707131a8a8b
Revises: 0003_seed_auth_umbrales
Create Date: 2026-07-11 21:39:59.049933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1707131a8a8b'
down_revision: Union[str, Sequence[str], None] = '0003_seed_auth_umbrales'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inversiones', 'etapa_f8',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=150),
               existing_nullable=True,
               schema='siaf')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inversiones', 'etapa_f8',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               schema='siaf')
    # ### end Alembic commands ###
