"""Aumentar campos String en inversiones

Revision ID: 36ad7695cdfb
Revises: 1707131a8a8b
Create Date: 2026-07-11 21:41:38.453943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36ad7695cdfb'
down_revision: Union[str, Sequence[str], None] = '1707131a8a8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auditoria_accion_creado'), table_name='auditoria', schema='logs')
    op.create_index('ix_auditoria_accion_creado', 'auditoria', ['accion', 'creado_en'], unique=False, schema='logs', postgresql_ops={'creado_en': 'DESC'})
    op.drop_index(op.f('ix_auditoria_usuario_creado'), table_name='auditoria', schema='logs')
    op.create_index('ix_auditoria_usuario_creado', 'auditoria', ['usuario_id', 'creado_en'], unique=False, schema='logs', postgresql_ops={'creado_en': 'DESC'})
    op.drop_index(op.f('ix_sincronizacion_job_inicio'), table_name='sincronizacion', schema='logs')
    op.create_index('ix_sincronizacion_job_inicio', 'sincronizacion', ['job', 'inicio'], unique=False, schema='logs', postgresql_ops={'inicio': 'DESC'})
    op.alter_column('centros_costo', 'tipo_dependencia',
               existing_type=sa.CHAR(length=1),
               type_=sa.String(length=1),
               existing_nullable=True,
               schema='ref')
    op.alter_column('inversiones', 'des_modalidad',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=150),
               existing_nullable=True,
               schema='siaf')
    op.alter_column('inversiones', 'des_tipologia',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=150),
               existing_nullable=True,
               schema='siaf')
    op.alter_column('inversiones', 'funcion',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=150),
               existing_nullable=True,
               schema='siaf')
    op.alter_column('inversiones', 'programa',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=150),
               existing_nullable=True,
               schema='siaf')
    op.drop_index(op.f('ix_anotacion_entidad_creado'), table_name='anotaciones_internas', schema='sistema')
    op.create_index('ix_anotacion_entidad_creado', 'anotaciones_internas', ['entidad_tipo', 'entidad_id', 'creado_en'], unique=False, schema='sistema', postgresql_ops={'creado_en': 'DESC'})
    op.drop_index(op.f('ix_observacion_obra_creado'), table_name='observaciones_ciudadanas', schema='sistema')
    op.create_index('ix_observacion_obra_creado', 'observaciones_ciudadanas', ['codigo_unico_obra', 'creado_en'], unique=False, schema='sistema', postgresql_ops={'creado_en': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_observacion_obra_creado', table_name='observaciones_ciudadanas', schema='sistema', postgresql_ops={'creado_en': 'DESC'})
    op.create_index(op.f('ix_observacion_obra_creado'), 'observaciones_ciudadanas', ['codigo_unico_obra', sa.literal_column('creado_en DESC')], unique=False, schema='sistema')
    op.drop_index('ix_anotacion_entidad_creado', table_name='anotaciones_internas', schema='sistema', postgresql_ops={'creado_en': 'DESC'})
    op.create_index(op.f('ix_anotacion_entidad_creado'), 'anotaciones_internas', ['entidad_tipo', 'entidad_id', sa.literal_column('creado_en DESC')], unique=False, schema='sistema')
    op.alter_column('inversiones', 'programa',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True,
               schema='siaf')
    op.alter_column('inversiones', 'funcion',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True,
               schema='siaf')
    op.alter_column('inversiones', 'des_tipologia',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True,
               schema='siaf')
    op.alter_column('inversiones', 'des_modalidad',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True,
               schema='siaf')
    op.alter_column('centros_costo', 'tipo_dependencia',
               existing_type=sa.String(length=1),
               type_=sa.CHAR(length=1),
               existing_nullable=True,
               schema='ref')
    op.drop_index('ix_sincronizacion_job_inicio', table_name='sincronizacion', schema='logs', postgresql_ops={'inicio': 'DESC'})
    op.create_index(op.f('ix_sincronizacion_job_inicio'), 'sincronizacion', ['job', sa.literal_column('inicio DESC')], unique=False, schema='logs')
    op.drop_index('ix_auditoria_usuario_creado', table_name='auditoria', schema='logs', postgresql_ops={'creado_en': 'DESC'})
    op.create_index(op.f('ix_auditoria_usuario_creado'), 'auditoria', ['usuario_id', sa.literal_column('creado_en DESC')], unique=False, schema='logs')
    op.drop_index('ix_auditoria_accion_creado', table_name='auditoria', schema='logs', postgresql_ops={'creado_en': 'DESC'})
    op.create_index(op.f('ix_auditoria_accion_creado'), 'auditoria', ['accion', sa.literal_column('creado_en DESC')], unique=False, schema='logs')
    # ### end Alembic commands ###
