CREATE  PROCEDURE dbo.SP_REPORTE_SEGUIMIENTO_PAAC_MODIF
(@PN_ANIO NUMERIC, @PN_EJECUTORA NUMERIC, @PN_REPORTE NUMERIC )
AS
DECLARE @CANO_EJE numeric(4, 0)
DECLARE @CSEC_EJEC numeric(6, 0)
DECLARE @CTIPO_CONSOLID char(1)
DECLARE @CNRO_CONSOLID numeric(5, 0)
DECLARE @CTIPO_GENERACION char(1)
DECLARE @CITEM_UNICO numeric(4, 0)
DECLARE @CTIPO_PROCESO varchar(2)
DECLARE @CNOM_TIPO_PROCESO varchar(250)
DECLARE @CNOM_TIPO_PROCESO_ABREV varchar(50)
DECLARE @COBJETO varchar(2)
DECLARE @CNOM_OBJETO varchar(250)
DECLARE @CESPEC_TECNICAS varchar(100)
DECLARE @CVALOR_MONEDA  numeric(16, 2)
DECLARE @CFUENTE varchar(250)
DECLARE @ESIGLAS varchar(40)
DECLARE @ESECTOR varchar(2)
DECLARE @EPLIEGO varchar(3)
DECLARE @PNOM_PLIEGO varchar(150)
DECLARE @ENOM_EJECUTORA varchar(150)
DECLARE @ERUC_EJEC varchar(11)
DECLARE @CINSTRUMENTO varchar(100)
DECLARE @CFLAG_PAAC varchar(1)
DECLARE @CNRO_PAAC varchar(4)
DECLARE @INRO_ITEM numeric(6, 0)
DECLARE @ITIPO_BIEN varchar(1)
DECLARE @IGRUPO_BIEN varchar(2)
DECLARE @ICLASE_BIEN varchar(2)
DECLARE @IFAMILIA_BIEN varchar(4)
DECLARE @IITEM_BIEN varchar(4)
DECLARE @INOMBRE_ITEM varchar(100)
DECLARE @IUNIDAD_MEDIDA numeric(3, 0)
DECLARE @INOMBRE_UNIDAD varchar(100)
DECLARE @ICANTIDAD numeric(20, 6)
DECLARE @IVALOR_MONEDA numeric(16, 2)
DECLARE @NUM numeric(6, 0)
DECLARE @NUM_CUENTA numeric(6, 0)
DECLARE @NUM_CUENTA_DETAB numeric(6, 0)
DECLARE @LS_CADENA VARCHAR(250)
DECLARE @LS_FUENTE VARCHAR(2)
DECLARE @NUM_CUENTA_PROCESO NUMERIC(6,0)
DECLARE @NUM_CUENTA_DETA NUMERIC(6,0)
DECLARE @SSEC_ITEM NUMERIC(4,0)
DECLARE @SCOD_ESTADO VARCHAR(1)
DECLARE @SVALOR_REF numeric(16, 2)
DECLARE @SPROCESO NUMERIC(5,0)
DECLARE @SSEC_PROCESO NUMERIC(4,0)
DECLARE @SCONVOCATORIA NUMERIC(2,0)
DECLARE @SANO_PROCESO NUMERIC(4,0)
DECLARE @SNRO_PROCESO NUMERIC(5,0)
DECLARE @SSIGLAS VARCHAR(40)
DECLARE @SFLAG_PSA VARCHAR(1)
DECLARE @STEXTO_FLAG_PSA VARCHAR(10)
DECLARE @STEXTO_WNRO_PROCESO VARCHAR(250)
DECLARE @SNRO_PROCESO_SEL VARCHAR(250)
DECLARE @SESTADO VARCHAR(40)
DECLARE @SPROVEEDOR NUMERIC(4,0)
DECLARE @SNOM_PROVEEDOR VARCHAR(100)
DECLARE @SNRO_RUC VARCHAR(11)
DECLARE @SVALOR_UNIT NUMERIC(16,2)
DECLARE @SVALOR_TOTAL NUMERIC(16,2)
DECLARE @SCANTIDAD_ADJUDICADA NUMERIC(20,6)
DECLARE @NUM_PROV NUMERIC(2,0)
DECLARE @SADJUDICADO VARCHAR(1)
DECLARE @CTITULO VARCHAR(100)
DECLARE @WCUENTA_TOTAL_ITEM NUMERIC(6,0)
DECLARE @WCUENTA_TOTAL_ITEM_DESIERTO NUMERIC(6,0)
DECLARE @WCUENTA_TOTAL_ITEM_CANCELADO NUMERIC(6,0)
DECLARE @WCUENTA_TOTAL_ITEM_CONCLUIDO  NUMERIC(6,0)
DECLARE @WCUENTA_TOTAL_ITEM_PROCESO NUMERIC(6,0)
DECLARE @WCUENTA_TOTAL_ITEM_PENDIENTE NUMERIC(6,0)
DECLARE @WCUENTA_TOTAL_ITEM_BUENA_PRO_S  NUMERIC(6,0)
DECLARE @WCUENTA_TOTAL_ITEM_BUENA_PRO_N NUMERIC(6,0)
DECLARE @WCUENTA_TOTAL_ITEM_BUENA_PRO_CON_S NUMERIC(6,0)
DECLARE @WCUENTA_TOTAL_ITEM_BUENA_PRO_CON_N NUMERIC(6,0)

--CABECERA
--DATOS PRINCIPALES DEL PAAC
DECLARE CUR_PAAC CURSOR FOR
SELECT
SIG_PAAC_CONSOLIDADO.ANO_EJE AS WANO_EJE,
SIG_PAAC_CONSOLIDADO.SEC_EJEC AS WSEC_EJEC, 
SIG_PAAC_CONSOLIDADO.TIPO_CONSOLID AS WTIPO_CONSOLID,
SIG_PAAC_CONSOLIDADO.NRO_CONSOLID AS WNRO_CONSOLID,
SIG_PAAC_CONSOLIDADO.TIPO_GENERACION AS WTIPO_GENERACION,
SIG_PAAC_CONSOLIDADO.FLAG_PAAC as WFLAG_PAAC,
SIG_PAAC_CONSOLIDADO.NRO_PAAC as WNRO_PAAC,
( SELECT COUNT(*)
  FROM SIG_PAAC_ITEM
  WHERE
  SIG_PAAC_CONSOLIDADO.ANO_EJE = SIG_PAAC_ITEM.ANO_EJE AND
  SIG_PAAC_CONSOLIDADO.SEC_EJEC = SIG_PAAC_ITEM.SEC_EJEC AND
  SIG_PAAC_CONSOLIDADO.TIPO_CONSOLID =   SIG_PAAC_ITEM.TIPO_CONSOLID AND
  SIG_PAAC_CONSOLIDADO.NRO_CONSOLID =   SIG_PAAC_ITEM.NRO_CONSOLID AND
  SIG_PAAC_CONSOLIDADO.TIPO_GENERACION =   SIG_PAAC_ITEM.TIPO_GENERACION ) AS WITEM_UNICO,
SIG_PAAC_CONSOLIDADO.TIPO_PROCESO AS WTIPO_PROCESO,
(SELECT SIG_MAESTRO_PROCESO.DESCRIPCION
 FROM SIG_MAESTRO_PROCESO
 WHERE 
 SIG_MAESTRO_PROCESO.ANO_EJE = SIG_PAAC_CONSOLIDADO.ANO_EJE AND  
 SIG_MAESTRO_PROCESO.TIPO_ORGANISMO = '01'  AND  
 SIG_MAESTRO_PROCESO.CODIGO = 'TIPO_PROCESO' AND
 SIG_MAESTRO_PROCESO.CODIGO_DET = SIG_PAAC_CONSOLIDADO.TIPO_PROCESO ) AS WNOM_PROCESO,
(SELECT SIG_MAESTRO_PROCESO.DESCRIPCION_ABREVIADA
 FROM SIG_MAESTRO_PROCESO
 WHERE 
 SIG_MAESTRO_PROCESO.ANO_EJE = SIG_PAAC_CONSOLIDADO.ANO_EJE AND  
 SIG_MAESTRO_PROCESO.TIPO_ORGANISMO = '01'  AND  
 SIG_MAESTRO_PROCESO.CODIGO = 'TIPO_PROCESO' AND
 SIG_MAESTRO_PROCESO.CODIGO_DET = SIG_PAAC_CONSOLIDADO.TIPO_PROCESO ) AS WNOM_PROCESO_ABREVIADA,
SIG_PAAC_CONSOLIDADO.OBJETO AS WOBJETO,
( SELECT CODIGO_GENERAL_DET.DESCRIPCION
  FROM CODIGO_GENERAL_DET  
  WHERE 
  CODIGO_GENERAL_DET.CODIGO = 'OBJETO' AND
  CODIGO_GENERAL_DET.CODIGO_DET = SIG_PAAC_CONSOLIDADO.OBJETO ) AS WNOM_OBJETO,
SIG_PAAC_CONSOLIDADO.ESPEC_TECNICAS AS WESPEC_TECNICAS,
EJECUTORA.SIGLAS AS WSIGLAS,
EJECUTORA.SECTOR AS WSECTOR,
EJECUTORA.PLIEGO AS WPLIEGO,
PLIEGO.NOMBRE AS WNOM_PLIEGO,
EJECUTORA.NOMBRE AS WNOM_EJECUTORA,
EJECUTORA.RUC_EJEC AS WRUC_EJEC,
( SELECT SIG_PARAMETRO_EJECUTORA_ANIO.VALOR
  FROM SIG_PARAMETRO_EJECUTORA_ANIO
  WHERE 
  SIG_PARAMETRO_EJECUTORA_ANIO.ANO_EJE = SIG_PAAC_CONSOLIDADO.ANO_EJE AND
  SIG_PARAMETRO_EJECUTORA_ANIO.SEC_EJEC = SIG_PAAC_CONSOLIDADO.SEC_EJEC AND
  SIG_PARAMETRO_EJECUTORA_ANIO.COD_MAESTRO = 'INSTRUMENTO_PAAC') AS WINSTRUMENTO,
SIG_PAAC_CONSOLIDADO.VALOR_MONEDA AS WVALOR_MONEDA
FROM SIG_PAAC_CONSOLIDADO, EJECUTORA, PLIEGO
WHERE 
SIG_PAAC_CONSOLIDADO.SEC_EJEC = EJECUTORA.SEC_EJEC AND
EJECUTORA.SECTOR = PLIEGO.SECTOR AND
EJECUTORA.PLIEGO = PLIEGO.PLIEGO AND
SIG_PAAC_CONSOLIDADO.ANO_EJE = @PN_ANIO AND
SIG_PAAC_CONSOLIDADO.SEC_EJEC = @PN_EJECUTORA AND
SIG_PAAC_CONSOLIDADO.TIPO_CONSOLID = '2' AND
SIG_PAAC_CONSOLIDADO.NRO_CONSOLID > 0 AND
SIG_PAAC_CONSOLIDADO.TIPO_GENERACION = '0'
ORDER BY SIG_PAAC_CONSOLIDADO.NRO_PAAC

OPEN CUR_PAAC
FETCH CUR_PAAC INTO @CANO_EJE,@CSEC_EJEC,@CTIPO_CONSOLID,@CNRO_CONSOLID,
@CTIPO_GENERACION,@CFLAG_PAAC,@CNRO_PAAC,@CITEM_UNICO ,@CTIPO_PROCESO,
@CNOM_TIPO_PROCESO,@CNOM_TIPO_PROCESO_ABREV, @COBJETO,@CNOM_OBJETO,@CESPEC_TECNICAS,
@ESIGLAS,@ESECTOR,@EPLIEGO,@PNOM_PLIEGO ,@ENOM_EJECUTORA,
@ERUC_EJEC,@CINSTRUMENTO, @CVALOR_MONEDA

WHILE @@FETCH_STATUS = 0
BEGIN
	--CUENTA SI EXISTEN ITEMS PARA PAAC MODIFICADO SELECCIONADO
	SELECT @NUM_CUENTA = COUNT(*)
	FROM SIG_PAAC_ITEM, CATALOGO_BIEN_SERV, UNIDAD_MEDIDA
	WHERE
	SIG_PAAC_ITEM.SEC_EJEC = CATALOGO_BIEN_SERV.SEC_EJEC AND
	SIG_PAAC_ITEM.TIPO_BIEN = CATALOGO_BIEN_SERV.TIPO_BIEN AND
	SIG_PAAC_ITEM.GRUPO_BIEN = CATALOGO_BIEN_SERV.GRUPO_BIEN AND
	SIG_PAAC_ITEM.CLASE_BIEN = CATALOGO_BIEN_SERV.CLASE_BIEN AND
	SIG_PAAC_ITEM.FAMILIA_BIEN = CATALOGO_BIEN_SERV.FAMILIA_BIEN AND
	SIG_PAAC_ITEM.ITEM_BIEN = CATALOGO_BIEN_SERV.ITEM_BIEN AND
	SIG_PAAC_ITEM.UNIDAD_MEDIDA = UNIDAD_MEDIDA.UNIDAD_MEDIDA AND
	SIG_PAAC_ITEM.ANO_EJE = @CANO_EJE AND
	SIG_PAAC_ITEM.SEC_EJEC = @CSEC_EJEC AND
	SIG_PAAC_ITEM.TIPO_CONSOLID = @CTIPO_CONSOLID AND
	SIG_PAAC_ITEM.TIPO_GENERACION = @CTIPO_GENERACION and
	SIG_PAAC_ITEM.NRO_CONSOLID = @CNRO_CONSOLID
	--CUENTA SI EXISTEN ITEMS PARA PAAC MODIFICADO SELECCIONADO

	--VERIFICA VALOR DE CUENTA DE ITEM DE PAAC MODIFICADO
	IF @NUM_CUENTA IS NULL 
	BEGIN
		SELECT @NUM_CUENTA = 0 
	END
	--VERIFICA VALOR DE CUENTA DE ITEM DE PAAC MODIFICADO

	--VALIDA SI EXISTEN ITEMS EN PAAC MODIFICADOR
	IF @NUM_CUENTA > 0 
	BEGIN
		--RECUPERAR FUENTE DE FINANCIAMIENTO
		DECLARE C_FUENTE CURSOR FOR	
		SELECT DISTINCT FUENTE_FINANC
		FROM  SIG_PAAC_METAS
		WHERE 
		ANO_EJE = @CANO_EJE and
		SEC_EJEC = @CSEC_EJEC  and
		TIPO_CONSOLID = @CTIPO_CONSOLID and
		NRO_CONSOLID = @CNRO_CONSOLID and
		TIPO_GENERACION = @CTIPO_GENERACION
			 
		OPEN C_FUENTE
		FETCH C_FUENTE INTO @LS_FUENTE

		SELECT @LS_CADENA = ''
		WHILE @@FETCH_STATUS = 0
		BEGIN
			IF @LS_FUENTE IS NULL 
			BEGIN
				SELECT @LS_FUENTE = ''
			END 

			IF Rtrim(LTRIM(@LS_FUENTE)) <> '' 
			BEGIN
				IF Rtrim(LTRIM(@LS_CADENA)) <> '' 
				BEGIN
					SELECT @LS_CADENA = @LS_FUENTE + ' , '+ @LS_CADENA
				END
				ELSE
				BEGIN
					SELECT @LS_CADENA = @LS_FUENTE
				END
			END
			FETCH C_FUENTE INTO @LS_FUENTE
		END
		CLOSE C_FUENTE
		DEALLOCATE C_FUENTE
		SELECT @CFUENTE = @LS_CADENA
		--RECUPERAR FUENTE DE FINANCIAMIENTO

		--RECUPERAR DE ITEMS SEGUN PAAC MODIFICADO SELECCIONADO
		SELECT @NUM = 0

		DECLARE CUR_PAAC_ITEM CURSOR FOR
		SELECT 
		SIG_PAAC_ITEM.TIPO_BIEN AS WTIPO_BIEN,
		SIG_PAAC_ITEM.GRUPO_BIEN AS WGRUPO_BIEN,
		SIG_PAAC_ITEM.CLASE_BIEN AS WCLASE_BIEN,
		SIG_PAAC_ITEM.FAMILIA_BIEN AS WFAMILIA_BIEN,
		SIG_PAAC_ITEM.ITEM_BIEN AS WITEM_BIEN,
		CATALOGO_BIEN_SERV.NOMBRE_ITEM AS WNOM_ITEM,
		SIG_PAAC_ITEM.UNIDAD_MEDIDA AS WUNIDAD_MEDIDA,
		UNIDAD_MEDIDA.NOMBRE AS WNOM_UNIDAD,
		( CASE SIG_PAAC_ITEM.TIPO_BIEN WHEN 'B' THEN SIG_PAAC_ITEM.CANTIDAD WHEN 'S' THEN 1 ELSE 1 END ) AS WCANTIDAD,
		SIG_PAAC_ITEM.VALOR_MONEDA AS WVALOR_MONEDA
		FROM SIG_PAAC_ITEM, CATALOGO_BIEN_SERV, UNIDAD_MEDIDA
		WHERE
		SIG_PAAC_ITEM.SEC_EJEC = CATALOGO_BIEN_SERV.SEC_EJEC AND
		SIG_PAAC_ITEM.TIPO_BIEN = CATALOGO_BIEN_SERV.TIPO_BIEN AND
		SIG_PAAC_ITEM.GRUPO_BIEN = CATALOGO_BIEN_SERV.GRUPO_BIEN AND
		SIG_PAAC_ITEM.CLASE_BIEN = CATALOGO_BIEN_SERV.CLASE_BIEN AND
		SIG_PAAC_ITEM.FAMILIA_BIEN = CATALOGO_BIEN_SERV.FAMILIA_BIEN AND
		SIG_PAAC_ITEM.ITEM_BIEN = CATALOGO_BIEN_SERV.ITEM_BIEN AND
		SIG_PAAC_ITEM.UNIDAD_MEDIDA = UNIDAD_MEDIDA.UNIDAD_MEDIDA AND
		SIG_PAAC_ITEM.ANO_EJE = @CANO_EJE AND
		SIG_PAAC_ITEM.SEC_EJEC = @CSEC_EJEC AND
		SIG_PAAC_ITEM.TIPO_CONSOLID = @CTIPO_CONSOLID AND
		SIG_PAAC_ITEM.TIPO_GENERACION = @CTIPO_GENERACION and
		SIG_PAAC_ITEM.NRO_CONSOLID = @CNRO_CONSOLID
		ORDER BY 
		SIG_PAAC_ITEM.SEC_RESUMEN

		OPEN CUR_PAAC_ITEM
		FETCH CUR_PAAC_ITEM INTO @ITIPO_BIEN,@IGRUPO_BIEN,@ICLASE_BIEN,
		@IFAMILIA_BIEN,@IITEM_BIEN,@INOMBRE_ITEM ,@IUNIDAD_MEDIDA,
		@INOMBRE_UNIDAD,@ICANTIDAD,@IVALOR_MONEDA 

		WHILE @@FETCH_STATUS = 0
		BEGIN
			--SETEA CORRELATIVO DE ITEM
			SELECT @NUM = @NUM + 1

			--CONTEO SI EXISTEN DATOS DE PROCESOS DE SELECCION
			--POR CADA ITEM QUE RECUPERA
			SELECT @NUM_CUENTA_PROCESO = COUNT(*)
			FROM SIG_PROCESO_DE_SELECCION, SIG_PROCESO_SECUENCIA,
			SIG_CONVOCATORIA, SIG_CONVOCATORIA_ITEM
			WHERE 
			SIG_PROCESO_DE_SELECCION.ANO_EJE = SIG_PROCESO_SECUENCIA.ANO_EJE AND
			SIG_PROCESO_DE_SELECCION.SEC_EJEC = SIG_PROCESO_SECUENCIA.SEC_EJEC AND
			SIG_PROCESO_DE_SELECCION.TIPO_GENERACION = SIG_PROCESO_SECUENCIA.TIPO_GENERACION AND
			SIG_PROCESO_DE_SELECCION.PROCESO = SIG_PROCESO_SECUENCIA.PROCESO AND
			SIG_PROCESO_SECUENCIA.ANO_EJE = SIG_CONVOCATORIA.ANO_EJE AND
			SIG_PROCESO_SECUENCIA.SEC_EJEC = SIG_CONVOCATORIA.SEC_EJEC AND
			SIG_PROCESO_SECUENCIA.TIPO_GENERACION = SIG_CONVOCATORIA.TIPO_GENERACION AND
			SIG_PROCESO_SECUENCIA.PROCESO = SIG_CONVOCATORIA.PROCESO AND
			SIG_PROCESO_SECUENCIA.SEC_PROCESO = SIG_CONVOCATORIA.SEC_PROCESO AND
			SIG_CONVOCATORIA.ANO_EJE = SIG_CONVOCATORIA_ITEM.ANO_EJE AND
			SIG_CONVOCATORIA.SEC_EJEC = SIG_CONVOCATORIA_ITEM.SEC_EJEC AND
			SIG_CONVOCATORIA.TIPO_GENERACION = SIG_CONVOCATORIA_ITEM.TIPO_GENERACION AND
			SIG_CONVOCATORIA.PROCESO = SIG_CONVOCATORIA_ITEM.PROCESO AND
			SIG_CONVOCATORIA.SEC_PROCESO = SIG_CONVOCATORIA_ITEM.SEC_PROCESO AND
			SIG_CONVOCATORIA.CONVOCATORIA = SIG_CONVOCATORIA_ITEM.CONVOCATORIA AND
			SIG_PROCESO_DE_SELECCION.ANO_EJE = @CANO_EJE AND
			SIG_PROCESO_DE_SELECCION.SEC_EJEC = @CSEC_EJEC AND
			SIG_PROCESO_DE_SELECCION.TIPO_CONSOLID = @CTIPO_CONSOLID AND
			SIG_PROCESO_DE_SELECCION.NRO_CONSOLID = @CNRO_CONSOLID AND
			SIG_PROCESO_DE_SELECCION.TIPO_GENERACION = @CTIPO_GENERACION AND
			SIG_CONVOCATORIA_ITEM.SEC_EJEC = @CSEC_EJEC AND
			SIG_CONVOCATORIA_ITEM.TIPO_BIEN = @ITIPO_BIEN AND
			SIG_CONVOCATORIA_ITEM.GRUPO_BIEN = @IGRUPO_BIEN AND
			SIG_CONVOCATORIA_ITEM.CLASE_BIEN = @ICLASE_BIEN AND
			SIG_CONVOCATORIA_ITEM.FAMILIA_BIEN = @IFAMILIA_BIEN AND
			SIG_CONVOCATORIA_ITEM.ITEM_BIEN = @IITEM_BIEN

			IF @NUM_CUENTA_PROCESO IS NULL 
			BEGIN
				SELECT @NUM_CUENTA_PROCESO = 0 
			END
			--CONTEO SI EXISTEN DATOS DE PROCESOS DE SELECCION
			--POR CADA ITEM QUE RECUPERA

			--VALIDA SI EXISTEN ITEMS EN PAAC MODIFICADOR
			IF @NUM_CUENTA_PROCESO > 0 
			BEGIN
				--SI EXISTE CONTEO
				--HALLAR MAXIMO, CONVOCATORIA, PROCESO, SEC_PROCESO

				--RECUPERAR MAXIMO PROCESO DE SIG_CONVOCATORIA_ITEM
				SELECT @SPROCESO = MAX(SIG_CONVOCATORIA_ITEM.PROCESO)
				FROM SIG_PROCESO_DE_SELECCION, SIG_PROCESO_SECUENCIA,
				SIG_CONVOCATORIA, SIG_CONVOCATORIA_ITEM
				WHERE 
				SIG_PROCESO_DE_SELECCION.ANO_EJE = SIG_PROCESO_SECUENCIA.ANO_EJE AND
				SIG_PROCESO_DE_SELECCION.SEC_EJEC = SIG_PROCESO_SECUENCIA.SEC_EJEC AND
				SIG_PROCESO_DE_SELECCION.TIPO_GENERACION = SIG_PROCESO_SECUENCIA.TIPO_GENERACION AND
				SIG_PROCESO_DE_SELECCION.PROCESO = SIG_PROCESO_SECUENCIA.PROCESO AND
				SIG_PROCESO_SECUENCIA.ANO_EJE = SIG_CONVOCATORIA.ANO_EJE AND
				SIG_PROCESO_SECUENCIA.SEC_EJEC = SIG_CONVOCATORIA.SEC_EJEC AND
				SIG_PROCESO_SECUENCIA.TIPO_GENERACION = SIG_CONVOCATORIA.TIPO_GENERACION AND
				SIG_PROCESO_SECUENCIA.PROCESO = SIG_CONVOCATORIA.PROCESO AND
				SIG_PROCESO_SECUENCIA.SEC_PROCESO = SIG_CONVOCATORIA.SEC_PROCESO AND
				SIG_CONVOCATORIA.ANO_EJE = SIG_CONVOCATORIA_ITEM.ANO_EJE AND
				SIG_CONVOCATORIA.SEC_EJEC = SIG_CONVOCATORIA_ITEM.SEC_EJEC AND
				SIG_CONVOCATORIA.TIPO_GENERACION = SIG_CONVOCATORIA_ITEM.TIPO_GENERACION AND
				SIG_CONVOCATORIA.PROCESO = SIG_CONVOCATORIA_ITEM.PROCESO AND
				SIG_CONVOCATORIA.SEC_PROCESO = SIG_CONVOCATORIA_ITEM.SEC_PROCESO AND
				SIG_CONVOCATORIA.CONVOCATORIA = SIG_CONVOCATORIA_ITEM.CONVOCATORIA AND
				SIG_PROCESO_DE_SELECCION.ANO_EJE = @CANO_EJE AND
				SIG_PROCESO_DE_SELECCION.SEC_EJEC = @CSEC_EJEC AND
				SIG_PROCESO_DE_SELECCION.TIPO_CONSOLID = @CTIPO_CONSOLID AND
				SIG_PROCESO_DE_SELECCION.NRO_CONSOLID = @CNRO_CONSOLID AND
				SIG_PROCESO_DE_SELECCION.TIPO_GENERACION = @CTIPO_GENERACION AND
				SIG_CONVOCATORIA_ITEM.SEC_EJEC = @CSEC_EJEC AND
				SIG_CONVOCATORIA_ITEM.TIPO_BIEN = @ITIPO_BIEN AND
				SIG_CONVOCATORIA_ITEM.GRUPO_BIEN = @IGRUPO_BIEN AND
				SIG_CONVOCATORIA_ITEM.CLASE_BIEN = @ICLASE_BIEN AND
				SIG_CONVOCATORIA_ITEM.FAMILIA_BIEN = @IFAMILIA_BIEN AND
				SIG_CONVOCATORIA_ITEM.ITEM_BIEN = @IITEM_BIEN

				IF @SPROCESO IS NULL
				BEGIN
					SELECT @SPROCESO = 0
				END

				--RECUPERAR MAXIMO SEC_PROCESO DE SIG_CONVOCATORIA_ITEM
				SELECT @SSEC_PROCESO = MAX(SIG_CONVOCATORIA_ITEM.SEC_PROCESO)
				FROM SIG_PROCESO_DE_SELECCION, SIG_PROCESO_SECUENCIA,
				SIG_CONVOCATORIA, SIG_CONVOCATORIA_ITEM
				WHERE 
				SIG_PROCESO_DE_SELECCION.ANO_EJE = SIG_PROCESO_SECUENCIA.ANO_EJE AND
				SIG_PROCESO_DE_SELECCION.SEC_EJEC = SIG_PROCESO_SECUENCIA.SEC_EJEC AND
				SIG_PROCESO_DE_SELECCION.TIPO_GENERACION = SIG_PROCESO_SECUENCIA.TIPO_GENERACION AND
				SIG_PROCESO_DE_SELECCION.PROCESO = SIG_PROCESO_SECUENCIA.PROCESO AND
				SIG_PROCESO_SECUENCIA.ANO_EJE = SIG_CONVOCATORIA.ANO_EJE AND
				SIG_PROCESO_SECUENCIA.SEC_EJEC = SIG_CONVOCATORIA.SEC_EJEC AND
				SIG_PROCESO_SECUENCIA.TIPO_GENERACION = SIG_CONVOCATORIA.TIPO_GENERACION AND
				SIG_PROCESO_SECUENCIA.PROCESO = SIG_CONVOCATORIA.PROCESO AND
				SIG_PROCESO_SECUENCIA.SEC_PROCESO = SIG_CONVOCATORIA.SEC_PROCESO AND
				SIG_CONVOCATORIA.ANO_EJE = SIG_CONVOCATORIA_ITEM.ANO_EJE AND
				SIG_CONVOCATORIA.SEC_EJEC = SIG_CONVOCATORIA_ITEM.SEC_EJEC AND
				SIG_CONVOCATORIA.TIPO_GENERACION = SIG_CONVOCATORIA_ITEM.TIPO_GENERACION AND
				SIG_CONVOCATORIA.PROCESO = SIG_CONVOCATORIA_ITEM.PROCESO AND
				SIG_CONVOCATORIA.SEC_PROCESO = SIG_CONVOCATORIA_ITEM.SEC_PROCESO AND
				SIG_CONVOCATORIA.CONVOCATORIA = SIG_CONVOCATORIA_ITEM.CONVOCATORIA AND
				SIG_PROCESO_DE_SELECCION.ANO_EJE = @CANO_EJE AND
				SIG_PROCESO_DE_SELECCION.SEC_EJEC = @CSEC_EJEC AND
				SIG_PROCESO_DE_SELECCION.TIPO_CONSOLID = @CTIPO_CONSOLID AND
				SIG_PROCESO_DE_SELECCION.NRO_CONSOLID = @CNRO_CONSOLID AND
				SIG_PROCESO_DE_SELECCION.TIPO_GENERACION = @CTIPO_GENERACION AND
				SIG_CONVOCATORIA_ITEM.SEC_EJEC = @CSEC_EJEC AND
				SIG_CONVOCATORIA_ITEM.TIPO_BIEN = @ITIPO_BIEN AND
				SIG_CONVOCATORIA_ITEM.GRUPO_BIEN = @IGRUPO_BIEN AND
				SIG_CONVOCATORIA_ITEM.CLASE_BIEN = @ICLASE_BIEN AND
				SIG_CONVOCATORIA_ITEM.FAMILIA_BIEN = @IFAMILIA_BIEN AND
				SIG_CONVOCATORIA_ITEM.ITEM_BIEN = @IITEM_BIEN AND
				SIG_CONVOCATORIA_ITEM.PROCESO = @SPROCESO

				IF @SSEC_PROCESO IS NULL
				BEGIN
					SELECT @SSEC_PROCESO = 0
				END

				--RECUPERAR MAXIMO CONVOCATORIA DE SIG_CONVOCATORIA_ITEM
				SELECT @SCONVOCATORIA = MAX(SIG_CONVOCATORIA_ITEM.CONVOCATORIA)
				FROM SIG_PROCESO_DE_SELECCION, SIG_PROCESO_SECUENCIA,
				SIG_CONVOCATORIA, SIG_CONVOCATORIA_ITEM
				WHERE 
				SIG_PROCESO_DE_SELECCION.ANO_EJE = SIG_PROCESO_SECUENCIA.ANO_EJE AND
				SIG_PROCESO_DE_SELECCION.SEC_EJEC = SIG_PROCESO_SECUENCIA.SEC_EJEC AND
				SIG_PROCESO_DE_SELECCION.TIPO_GENERACION = SIG_PROCESO_SECUENCIA.TIPO_GENERACION AND
				SIG_PROCESO_DE_SELECCION.PROCESO = SIG_PROCESO_SECUENCIA.PROCESO AND
				SIG_PROCESO_SECUENCIA.ANO_EJE = SIG_CONVOCATORIA.ANO_EJE AND
				SIG_PROCESO_SECUENCIA.SEC_EJEC = SIG_CONVOCATORIA.SEC_EJEC AND
				SIG_PROCESO_SECUENCIA.TIPO_GENERACION = SIG_CONVOCATORIA.TIPO_GENERACION AND
				SIG_PROCESO_SECUENCIA.PROCESO = SIG_CONVOCATORIA.PROCESO AND
				SIG_PROCESO_SECUENCIA.SEC_PROCESO = SIG_CONVOCATORIA.SEC_PROCESO AND
				SIG_CONVOCATORIA.ANO_EJE = SIG_CONVOCATORIA_ITEM.ANO_EJE AND
				SIG_CONVOCATORIA.SEC_EJEC = SIG_CONVOCATORIA_ITEM.SEC_EJEC AND
				SIG_CONVOCATORIA.TIPO_GENERACION = SIG_CONVOCATORIA_ITEM.TIPO_GENERACION AND
				SIG_CONVOCATORIA.PROCESO = SIG_CONVOCATORIA_ITEM.PROCESO AND
				SIG_CONVOCATORIA.SEC_PROCESO = SIG_CONVOCATORIA_ITEM.SEC_PROCESO AND
				SIG_CONVOCATORIA.CONVOCATORIA = SIG_CONVOCATORIA_ITEM.CONVOCATORIA AND
				SIG_PROCESO_DE_SELECCION.ANO_EJE = @CANO_EJE AND
				SIG_PROCESO_DE_SELECCION.SEC_EJEC = @CSEC_EJEC AND
				SIG_PROCESO_DE_SELECCION.TIPO_CONSOLID = @CTIPO_CONSOLID AND
				SIG_PROCESO_DE_SELECCION.NRO_CONSOLID = @CNRO_CONSOLID AND
				SIG_PROCESO_DE_SELECCION.TIPO_GENERACION = @CTIPO_GENERACION AND
				SIG_CONVOCATORIA_ITEM.SEC_EJEC = @CSEC_EJEC AND
				SIG_CONVOCATORIA_ITEM.TIPO_BIEN = @ITIPO_BIEN AND
				SIG_CONVOCATORIA_ITEM.GRUPO_BIEN = @IGRUPO_BIEN AND
				SIG_CONVOCATORIA_ITEM.CLASE_BIEN = @ICLASE_BIEN AND
				SIG_CONVOCATORIA_ITEM.FAMILIA_BIEN = @IFAMILIA_BIEN AND
				SIG_CONVOCATORIA_ITEM.ITEM_BIEN = @IITEM_BIEN AND
				SIG_CONVOCATORIA_ITEM.PROCESO = @SPROCESO AND
				SIG_CONVOCATORIA_ITEM.SEC_PROCESO = @SSEC_PROCESO

				IF @SCONVOCATORIA IS NULL
				BEGIN
					SELECT @SCONVOCATORIA = 0
				END
				--SI EXISTE CONTEO
				--HALLAR MAXIMO, CONVOCATORIA, PROCESO, SEC_PROCESO

				--UNA VEZ RECUPERADO LOS DATOS SE RECUPERA EL NRO DE PROCESO
				SELECT @SANO_PROCESO = SIG_PROCESO_SECUENCIA.ANO_PROCESO, 
				@SNRO_PROCESO = SIG_PROCESO_SECUENCIA.NRO_PROCESO,
				@SSIGLAS = SIG_PROCESO_SECUENCIA.SIGLAS,
				@SFLAG_PSA = SIG_PROCESO_SECUENCIA.FLAG_PSA
				FROM SIG_PROCESO_SECUENCIA
				WHERE 
				SIG_PROCESO_SECUENCIA.ANO_EJE = @CANO_EJE AND
				SIG_PROCESO_SECUENCIA.SEC_EJEC = @CSEC_EJEC AND
				SIG_PROCESO_SECUENCIA.TIPO_GENERACION = @CTIPO_GENERACION AND
				SIG_PROCESO_SECUENCIA.PROCESO = @SPROCESO AND
				SIG_PROCESO_SECUENCIA.SEC_PROCESO =  @SSEC_PROCESO

				IF  @SFLAG_PSA = 'S'
				BEGIN
					SELECT  @STEXTO_FLAG_PSA = 'PSA'
				END
				ELSE
				BEGIN
					SELECT  @STEXTO_FLAG_PSA = ''
				END
			
				IF @SNRO_PROCESO IS NULL
				BEGIN
					SELECT  @STEXTO_WNRO_PROCESO = ''
				END
				ELSE
				BEGIN
					SELECT  @STEXTO_WNRO_PROCESO = RIGHT('00000' + RTRIM(LTRIM(CAST(@SNRO_PROCESO AS VARCHAR(5) ))), 5) + '-' + CAST(@SANO_PROCESO AS VARCHAR(4) ) + '-'

					IF @SSIGLAS IS NULL
					BEGIN
						IF @ESIGLAS IS NULL
						BEGIN
							SELECT  @STEXTO_WNRO_PROCESO = RTRIM(LTRIM(@STEXTO_FLAG_PSA)) + ' ' + RTRIM(LTRIM(@STEXTO_WNRO_PROCESO))
						END
						ELSE
						BEGIN
							SELECT  @STEXTO_WNRO_PROCESO = RTRIM(LTRIM(@STEXTO_FLAG_PSA)) + ' ' + RTRIM(LTRIM(@STEXTO_WNRO_PROCESO)) + RTRIM(LTRIM(@ESIGLAS))
						END
					END
					ELSE
					BEGIN
						SELECT  @STEXTO_WNRO_PROCESO = RTRIM(LTRIM(@STEXTO_FLAG_PSA)) + ' ' + RTRIM(LTRIM(@STEXTO_WNRO_PROCESO)) + RTRIM(LTRIM(@SSIGLAS))
					END
				END
				SELECT @SNRO_PROCESO_SEL = RTRIM(LTRIM(@STEXTO_WNRO_PROCESO))

				--UNA VEZ RECUPERADO LOS DATOS SE RECUPERA EL NRO DE PROCESO
				
				--UNA VEZ RECUPERADO LOS DATOS SE RECUPERA  EL NRO DE CONVOCATORIA
				--@SCONVOCATORIA
				--UNA VEZ RECUPERADO LOS DATOS SE RECUPERA  EL NRO DE CONVOCATORIA


				--SE CREA CURSOR PARA BARRER LOS ITEMS DE SIG_CONVOCATORIA_IETM
				--SE RECUPERA LOS DATOS
				--ESTADO, NRO_ITEM, VALOR REFERENCIAL
				--PRIMERO CUENTA SI EXISTE
				SELECT @NUM_CUENTA_DETA = COUNT(*)
				FROM SIG_CONVOCATORIA_ITEM
				WHERE 
				SIG_CONVOCATORIA_ITEM.ANO_EJE = @CANO_EJE AND
				SIG_CONVOCATORIA_ITEM.SEC_EJEC = @CSEC_EJEC AND
				SIG_CONVOCATORIA_ITEM.TIPO_GENERACION = @CTIPO_GENERACION AND
				SIG_CONVOCATORIA_ITEM.PROCESO = @SPROCESO AND
				SIG_CONVOCATORIA_ITEM.SEC_PROCESO = @SSEC_PROCESO AND
				SIG_CONVOCATORIA_ITEM.CONVOCATORIA = @SCONVOCATORIA AND
				EXISTS(
				SELECT 1 FROM SIG_PROPUESTA_ITEM, SIG_PROPUESTA_LOTE
				WHERE 
				SIG_PROPUESTA_ITEM.ANO_EJE = SIG_PROPUESTA_LOTE.ANO_EJE AND
				SIG_PROPUESTA_ITEM.SEC_EJEC = SIG_PROPUESTA_LOTE.SEC_EJEC AND
				SIG_PROPUESTA_ITEM.TIPO_GENERACION = SIG_PROPUESTA_LOTE.TIPO_GENERACION AND
				SIG_PROPUESTA_ITEM.PROCESO = SIG_PROPUESTA_LOTE.PROCESO AND
				SIG_PROPUESTA_ITEM.SEC_PROCESO = SIG_PROPUESTA_LOTE.SEC_PROCESO AND
				SIG_PROPUESTA_ITEM.CONVOCATORIA = SIG_PROPUESTA_LOTE.CONVOCATORIA AND
				SIG_PROPUESTA_ITEM.SEC_CONVOCATORIA = SIG_PROPUESTA_LOTE.SEC_CONVOCATORIA AND
				SIG_PROPUESTA_ITEM.NRO_LOTE = SIG_PROPUESTA_LOTE.NRO_LOTE AND
				SIG_PROPUESTA_ITEM.PROVEEDOR = SIG_PROPUESTA_LOTE.PROVEEDOR AND
				SIG_PROPUESTA_ITEM.NRO_PROPUESTA = SIG_PROPUESTA_LOTE.NRO_PROPUESTA AND
				SIG_PROPUESTA_ITEM.ANO_EJE = @CANO_EJE AND
				SIG_PROPUESTA_ITEM.SEC_EJEC = @CSEC_EJEC AND
				SIG_PROPUESTA_ITEM.TIPO_GENERACION = @CTIPO_GENERACION AND
				SIG_PROPUESTA_ITEM.PROCESO = @SPROCESO AND
				SIG_PROPUESTA_ITEM.SEC_PROCESO = @SSEC_PROCESO AND
				SIG_PROPUESTA_ITEM.CONVOCATORIA = @SCONVOCATORIA AND
				SIG_PROPUESTA_ITEM.NRO_ITEM = SIG_CONVOCATORIA_ITEM.NRO_ITEM  AND
				SIG_PROPUESTA_LOTE.ADJUDICADO = 'S' )
				--PRIMERO CUENTA SI EXISTE

				IF @NUM_CUENTA_DETA IS NULL 
				BEGIN
					SELECT @NUM_CUENTA_DETA = 0 
				END

				IF @NUM_CUENTA_DETA = 0
				--NO EXISTE
				BEGIN
	
					SELECT @NUM_CUENTA_DETAB = COUNT(*)
					FROM SIG_CONVOCATORIA_ITEM
					WHERE 
					SIG_CONVOCATORIA_ITEM.ANO_EJE = @CANO_EJE AND
					SIG_CONVOCATORIA_ITEM.SEC_EJEC = @CSEC_EJEC AND
					SIG_CONVOCATORIA_ITEM.TIPO_GENERACION = @CTIPO_GENERACION AND
					SIG_CONVOCATORIA_ITEM.PROCESO = @SPROCESO AND
					SIG_CONVOCATORIA_ITEM.SEC_PROCESO = @SSEC_PROCESO AND
					SIG_CONVOCATORIA_ITEM.CONVOCATORIA = @SCONVOCATORIA AND
					EXISTS(
					SELECT 1 FROM SIG_PROPUESTA_ITEM, SIG_PROPUESTA_LOTE
					WHERE 
					SIG_PROPUESTA_ITEM.ANO_EJE = SIG_PROPUESTA_LOTE.ANO_EJE AND
					SIG_PROPUESTA_ITEM.SEC_EJEC = SIG_PROPUESTA_LOTE.SEC_EJEC AND
					SIG_PROPUESTA_ITEM.TIPO_GENERACION = SIG_PROPUESTA_LOTE.TIPO_GENERACION AND
					SIG_PROPUESTA_ITEM.PROCESO = SIG_PROPUESTA_LOTE.PROCESO AND
					SIG_PROPUESTA_ITEM.SEC_PROCESO = SIG_PROPUESTA_LOTE.SEC_PROCESO AND
					SIG_PROPUESTA_ITEM.CONVOCATORIA = SIG_PROPUESTA_LOTE.CONVOCATORIA AND
					SIG_PROPUESTA_ITEM.SEC_CONVOCATORIA = SIG_PROPUESTA_LOTE.SEC_CONVOCATORIA AND
					SIG_PROPUESTA_ITEM.NRO_LOTE = SIG_PROPUESTA_LOTE.NRO_LOTE AND
					SIG_PROPUESTA_ITEM.PROVEEDOR = SIG_PROPUESTA_LOTE.PROVEEDOR AND
					SIG_PROPUESTA_ITEM.NRO_PROPUESTA = SIG_PROPUESTA_LOTE.NRO_PROPUESTA AND
					SIG_PROPUESTA_ITEM.ANO_EJE = @CANO_EJE AND
					SIG_PROPUESTA_ITEM.SEC_EJEC = @CSEC_EJEC AND
					SIG_PROPUESTA_ITEM.TIPO_GENERACION = @CTIPO_GENERACION AND
					SIG_PROPUESTA_ITEM.PROCESO = @SPROCESO AND
					SIG_PROPUESTA_ITEM.SEC_PROCESO = @SSEC_PROCESO AND
					SIG_PROPUESTA_ITEM.CONVOCATORIA = @SCONVOCATORIA AND
					SIG_PROPUESTA_ITEM.NRO_ITEM = SIG_CONVOCATORIA_ITEM.NRO_ITEM  AND
					( SIG_PROPUESTA_LOTE.ADJUDICADO = 'N' OR SIG_PROPUESTA_LOTE.ADJUDICADO IS NULL OR RTRIM(LTRIM(SIG_PROPUESTA_LOTE.ADJUDICADO)) = '' ) )
					--PRIMERO CUENTA SI EXISTE

					IF @NUM_CUENTA_DETAB IS NULL 
					BEGIN
						SELECT @NUM_CUENTA_DETAB = 0 
					END

					IF @NUM_CUENTA_DETAB = 0 
					BEGIN
						--INSERTA MOVIMIENTO DE ITEM
						--NO HAY DATOS DE PROCESO DE SELECCION
						--SELECT @NUM = @NUM + 1
						SELECT @SADJUDICADO = 'N'
	
						INSERT INTO TMP_SEGUIMIENTO_PAAC_MODIF
						(
						CREPORTE,CANO_EJE,CSEC_EJEC,CTIPO_CONSOLID,CNRO_CONSOLID,
						CTIPO_GENERACION,CFLAG_PAAC,CNRO_PAAC,CITEM_UNICO,CTIPO_PROCESO,
						CNOM_TIPO_PROCESO,COBJETO,CNOM_OBJETO,CESPEC_TECNICAS,
						ESIGLAS,ESECTOR,EPLIEGO,PNOM_PLIEGO,ENOM_EJECUTORA,
						ERUC_EJEC,CINSTRUMENTO,CVALOR_MONEDA,CFUENTE,
						INRO_ITEM,ITIPO_BIEN,IGRUPO_BIEN,ICLASE_BIEN,IFAMILIA_BIEN,
						IITEM_BIEN,INOMBRE_ITEM,IUNIDAD_MEDIDA,INOMBRE_UNIDAD,
						ICANTIDAD,IVALOR_MONEDA,
						SSEC_ITEM, SVALOR_REF, SESTADO, SNRO_PROCESO_SEL, SNRO_CONVOCATORIA,
						SPROVEEDOR, SNOM_PROVEEDOR, SNRO_RUC, SVALOR_UNIT, SVALOR_TOTAL,
						SCANTIDAD_ADJUDICADA, SNRO_PROV, SADJUDICADO, CNOM_TIPO_PROCESO_ABREV
						)
						VALUES
						(		
						@PN_REPORTE,@CANO_EJE,@CSEC_EJEC,@CTIPO_CONSOLID,@CNRO_CONSOLID,
						@CTIPO_GENERACION,@CFLAG_PAAC,@CNRO_PAAC, @CITEM_UNICO, @CTIPO_PROCESO,
						@CNOM_TIPO_PROCESO, @COBJETO,@CNOM_OBJETO,@CESPEC_TECNICAS,
						@ESIGLAS,@ESECTOR,@EPLIEGO,@PNOM_PLIEGO ,@ENOM_EJECUTORA,
						@ERUC_EJEC,@CINSTRUMENTO,@CVALOR_MONEDA,@CFUENTE,
						@NUM,@ITIPO_BIEN,@IGRUPO_BIEN,@ICLASE_BIEN,@IFAMILIA_BIEN,
						@IITEM_BIEN,@INOMBRE_ITEM ,@IUNIDAD_MEDIDA,@INOMBRE_UNIDAD,
						@ICANTIDAD,@IVALOR_MONEDA ,
						0, 0.00,'', '', NULL,
						NULL, '', '', 0.00,0.00,
						0, 0, @SADJUDICADO, @CNOM_TIPO_PROCESO_ABREV
						)
	
						IF @@ERROR <> 0
						BEGIN
							CLOSE CUR_PAAC_ITEM
							DEALLOCATE CUR_PAAC_ITEM
							CLOSE CUR_PAAC
							DEALLOCATE CUR_PAAC
							GOTO ERROR
						END
					END
					ELSE
					BEGIN
						--EXISTE EN PROCESO DE SELECCION
						IF @NUM_CUENTA_DETAB = 1 
						BEGIN
							--RECUPERAR DATOS DEL ESTADO Y EL VALOR DE REFERENCIA
							SELECT @SSEC_ITEM = SIG_CONVOCATORIA_ITEM.NRO_ITEM,
							@SCOD_ESTADO = SIG_CONVOCATORIA_ITEM.ESTADO ,
							@SVALOR_REF =  SIG_CONVOCATORIA_ITEM.VALOR_MONEDA
							FROM SIG_CONVOCATORIA_ITEM
							WHERE 
							SIG_CONVOCATORIA_ITEM.ANO_EJE = @CANO_EJE AND
							SIG_CONVOCATORIA_ITEM.SEC_EJEC = @CSEC_EJEC AND
							SIG_CONVOCATORIA_ITEM.TIPO_GENERACION = @CTIPO_GENERACION AND
							SIG_CONVOCATORIA_ITEM.PROCESO = @SPROCESO AND
							SIG_CONVOCATORIA_ITEM.SEC_PROCESO = @SSEC_PROCESO AND
							SIG_CONVOCATORIA_ITEM.CONVOCATORIA = @SCONVOCATORIA AND
							EXISTS(
							SELECT 1 FROM SIG_PROPUESTA_ITEM, SIG_PROPUESTA_LOTE
							WHERE 
							SIG_PROPUESTA_ITEM.ANO_EJE = SIG_PROPUESTA_LOTE.ANO_EJE AND
							SIG_PROPUESTA_ITEM.SEC_EJEC = SIG_PROPUESTA_LOTE.SEC_EJEC AND
							SIG_PROPUESTA_ITEM.TIPO_GENERACION = SIG_PROPUESTA_LOTE.TIPO_GENERACION AND
							SIG_PROPUESTA_ITEM.PROCESO = SIG_PROPUESTA_LOTE.PROCESO AND
							SIG_PROPUESTA_ITEM.SEC_PROCESO = SIG_PROPUESTA_LOTE.SEC_PROCESO AND
							SIG_PROPUESTA_ITEM.CONVOCATORIA = SIG_PROPUESTA_LOTE.CONVOCATORIA AND
							SIG_PROPUESTA_ITEM.SEC_CONVOCATORIA = SIG_PROPUESTA_LOTE.SEC_CONVOCATORIA AND
							SIG_PROPUESTA_ITEM.NRO_LOTE = SIG_PROPUESTA_LOTE.NRO_LOTE AND
							SIG_PROPUESTA_ITEM.PROVEEDOR = SIG_PROPUESTA_LOTE.PROVEEDOR AND
							SIG_PROPUESTA_ITEM.NRO_PROPUESTA = SIG_PROPUESTA_LOTE.NRO_PROPUESTA AND
							SIG_PROPUESTA_ITEM.ANO_EJE = @CANO_EJE AND
							SIG_PROPUESTA_ITEM.SEC_EJEC = @CSEC_EJEC AND
							SIG_PROPUESTA_ITEM.TIPO_GENERACION = @CTIPO_GENERACION AND
							SIG_PROPUESTA_ITEM.PROCESO = @SPROCESO AND
							SIG_PROPUESTA_ITEM.SEC_PROCESO = @SSEC_PROCESO AND
							SIG_PROPUESTA_ITEM.CONVOCATORIA = @SCONVOCATORIA AND
							SIG_PROPUESTA_ITEM.NRO_ITEM = SIG_CONVOCATORIA_ITEM.NRO_ITEM  AND
							( SIG_PROPUESTA_LOTE.ADJUDICADO = 'N' OR SIG_PROPUESTA_LOTE.ADJUDICADO IS NULL OR RTRIM(LTRIM(SIG_PROPUESTA_LOTE.ADJUDICADO)) = '' ) )
							--PRIMERO CUENTA SI EXISTE
						END
						ELSE
						BEGIN
							--RECUPERAR DATOS DEL ESTADO Y EL VALOR DE REFERENCIA
							SELECT @SSEC_ITEM = SIG_CONVOCATORIA_ITEM.NRO_ITEM,
							@SCOD_ESTADO = SIG_CONVOCATORIA_ITEM.ESTADO ,
							@SVALOR_REF =  SIG_CONVOCATORIA_ITEM.VALOR_MONEDA
							FROM SIG_CONVOCATORIA_ITEM
							WHERE 
							SIG_CONVOCATORIA_ITEM.ANO_EJE = @CANO_EJE AND
							SIG_CONVOCATORIA_ITEM.SEC_EJEC = @CSEC_EJEC AND
							SIG_CONVOCATORIA_ITEM.TIPO_GENERACION = @CTIPO_GENERACION AND
							SIG_CONVOCATORIA_ITEM.PROCESO = @SPROCESO AND
							SIG_CONVOCATORIA_ITEM.SEC_PROCESO = @SSEC_PROCESO AND
							SIG_CONVOCATORIA_ITEM.CONVOCATORIA = @SCONVOCATORIA AND
							SIG_CONVOCATORIA_ITEM.NRO_ITEM  = 
							(
							SELECT MAX(SIG_PROPUESTA_ITEM.NRO_ITEM)
							FROM SIG_PROPUESTA_ITEM, SIG_PROPUESTA_LOTE
							WHERE 
							SIG_PROPUESTA_ITEM.ANO_EJE = SIG_PROPUESTA_LOTE.ANO_EJE AND
							SIG_PROPUESTA_ITEM.SEC_EJEC = SIG_PROPUESTA_LOTE.SEC_EJEC AND
							SIG_PROPUESTA_ITEM.TIPO_GENERACION = SIG_PROPUESTA_LOTE.TIPO_GENERACION AND
							SIG_PROPUESTA_ITEM.PROCESO = SIG_PROPUESTA_LOTE.PROCESO AND
							SIG_PROPUESTA_ITEM.SEC_PROCESO = SIG_PROPUESTA_LOTE.SEC_PROCESO AND
							SIG_PROPUESTA_ITEM.CONVOCATORIA = SIG_PROPUESTA_LOTE.CONVOCATORIA AND
							SIG_PROPUESTA_ITEM.SEC_CONVOCATORIA = SIG_PROPUESTA_LOTE.SEC_CONVOCATORIA AND
							SIG_PROPUESTA_ITEM.NRO_LOTE = SIG_PROPUESTA_LOTE.NRO_LOTE AND
							SIG_PROPUESTA_ITEM.PROVEEDOR = SIG_PROPUESTA_LOTE.PROVEEDOR AND
							SIG_PROPUESTA_ITEM.NRO_PROPUESTA = SIG_PROPUESTA_LOTE.NRO_PROPUESTA AND
							SIG_PROPUESTA_ITEM.ANO_EJE = @CANO_EJE AND
							SIG_PROPUESTA_ITEM.SEC_EJEC = @CSEC_EJEC AND
							SIG_PROPUESTA_ITEM.TIPO_GENERACION = @CTIPO_GENERACION AND
							SIG_PROPUESTA_ITEM.PROCESO = @SPROCESO AND
							SIG_PROPUESTA_ITEM.SEC_PROCESO = @SSEC_PROCESO AND
							SIG_PROPUESTA_ITEM.CONVOCATORIA = @SCONVOCATORIA AND
							( SIG_PROPUESTA_LOTE.ADJUDICADO = 'N' OR SIG_PROPUESTA_LOTE.ADJUDICADO IS NULL OR RTRIM(LTRIM(SIG_PROPUESTA_LOTE.ADJUDICADO)) = '' ) )
							--PRIMERO CUENTA SI EXISTE
						END	
						--
						IF @SCOD_ESTADO = '0' 
						BEGIN
							SELECT @SESTADO = 'PENDIENTE'
						END
						IF @SCOD_ESTADO = '1' 
						BEGIN
							SELECT @SESTADO = 'PROCESO'
						END
						IF @SCOD_ESTADO = '2' 
						BEGIN
							SELECT @SESTADO = 'CANCELADO'
						END
						IF @SCOD_ESTADO = '3' 
						BEGIN
							SELECT @SESTADO = 'BUENAPRO'
						END

						IF @SCOD_ESTADO = '4' 
						BEGIN
							SELECT @SESTADO = 'BUENAPRO CONSENTIDA'
						END

						IF @SCOD_ESTADO = '5' 
						BEGIN
							SELECT @SESTADO = 'DESIERTO'
						END

						IF ( @SCOD_ESTADO IS NULL OR RTRIM(LTRIM(@SCOD_ESTADO)) = '') AND  @SCOD_ESTADO <> '5' AND  @SCOD_ESTADO = '4' AND  @SCOD_ESTADO <> '3' AND  @SCOD_ESTADO <> '2' AND  @SCOD_ESTADO <> '1' AND  @SCOD_ESTADO <> '0' 
						BEGIN
							SELECT @SESTADO = 'NO DEFINIDO'
						END


						--POR CADA REGISTRO SE RECUPERAN DATOS DE 
						--PROVEEDOR, RUC, VALOR ADJUDICADO
						--SELECT @NUM = @NUM + 1

						SELECT @NUM_PROV = 0

						--INSERTA MOVIMIENTO DE ITEM
						--HAY DATOS DE PROCESO DE SELECCION
						--SELECT @NUM_PROV = @NUM_PROV + 1
						SELECT @SADJUDICADO = 'N'

						INSERT INTO TMP_SEGUIMIENTO_PAAC_MODIF
						(
						CREPORTE,CANO_EJE,CSEC_EJEC,CTIPO_CONSOLID,CNRO_CONSOLID,
						CTIPO_GENERACION,CFLAG_PAAC,CNRO_PAAC,CITEM_UNICO,CTIPO_PROCESO,
						CNOM_TIPO_PROCESO,COBJETO,CNOM_OBJETO,CESPEC_TECNICAS,
						ESIGLAS,ESECTOR,EPLIEGO,PNOM_PLIEGO,ENOM_EJECUTORA,
						ERUC_EJEC,CINSTRUMENTO,CVALOR_MONEDA,CFUENTE,
						INRO_ITEM,ITIPO_BIEN,IGRUPO_BIEN,ICLASE_BIEN,IFAMILIA_BIEN,
						IITEM_BIEN,INOMBRE_ITEM,IUNIDAD_MEDIDA,INOMBRE_UNIDAD,
						ICANTIDAD,IVALOR_MONEDA,
						SSEC_ITEM, SVALOR_REF, SESTADO, SNRO_PROCESO_SEL, SNRO_CONVOCATORIA,
						SPROVEEDOR, SNOM_PROVEEDOR, SNRO_RUC, SVALOR_UNIT, SVALOR_TOTAL,
						SCANTIDAD_ADJUDICADA, SNRO_PROV, SADJUDICADO, CNOM_TIPO_PROCESO_ABREV
						)
						VALUES
						(		
						@PN_REPORTE,@CANO_EJE,@CSEC_EJEC,@CTIPO_CONSOLID,@CNRO_CONSOLID,
						@CTIPO_GENERACION,@CFLAG_PAAC,@CNRO_PAAC, @CITEM_UNICO, @CTIPO_PROCESO,
						@CNOM_TIPO_PROCESO, @COBJETO,@CNOM_OBJETO,@CESPEC_TECNICAS,
						@ESIGLAS,@ESECTOR,@EPLIEGO,@PNOM_PLIEGO ,@ENOM_EJECUTORA,
						@ERUC_EJEC,@CINSTRUMENTO,@CVALOR_MONEDA,@CFUENTE,
						@NUM,@ITIPO_BIEN,@IGRUPO_BIEN,@ICLASE_BIEN,@IFAMILIA_BIEN,
						@IITEM_BIEN,@INOMBRE_ITEM ,@IUNIDAD_MEDIDA,@INOMBRE_UNIDAD,
						@ICANTIDAD,@IVALOR_MONEDA ,
						@SSEC_ITEM, @SVALOR_REF,@SESTADO, @SNRO_PROCESO_SEL, @SCONVOCATORIA,
						'', '', '', 0.00,0.00,
						0.00, @NUM_PROV, @SADJUDICADO, @CNOM_TIPO_PROCESO_ABREV
						)
	
						IF @@ERROR <> 0
						BEGIN
							CLOSE CUR_PAAC_ITEM
							DEALLOCATE CUR_PAAC_ITEM
							CLOSE CUR_PAAC
							DEALLOCATE CUR_PAAC
							GOTO ERROR
						END

					END
				END
				ELSE
				--EXISTE
				BEGIN

					IF @NUM_CUENTA_DETA = 1
					BEGIN
						--RECUPERAR DATOS DEL ESTADO Y EL VALOR DE REFERENCIA
						SELECT @SSEC_ITEM = SIG_CONVOCATORIA_ITEM.NRO_ITEM,
						@SCOD_ESTADO = SIG_CONVOCATORIA_ITEM.ESTADO ,
						@SVALOR_REF =  SIG_CONVOCATORIA_ITEM.VALOR_MONEDA
						FROM SIG_CONVOCATORIA_ITEM
						WHERE 
						SIG_CONVOCATORIA_ITEM.ANO_EJE = @CANO_EJE AND
						SIG_CONVOCATORIA_ITEM.SEC_EJEC = @CSEC_EJEC AND
						SIG_CONVOCATORIA_ITEM.TIPO_GENERACION = @CTIPO_GENERACION AND
						SIG_CONVOCATORIA_ITEM.PROCESO = @SPROCESO AND
						SIG_CONVOCATORIA_ITEM.SEC_PROCESO = @SSEC_PROCESO AND
						SIG_CONVOCATORIA_ITEM.CONVOCATORIA = @SCONVOCATORIA AND
						EXISTS(
						SELECT 1 FROM SIG_PROPUESTA_ITEM, SIG_PROPUESTA_LOTE
						WHERE 
						SIG_PROPUESTA_ITEM.ANO_EJE = SIG_PROPUESTA_LOTE.ANO_EJE AND
						SIG_PROPUESTA_ITEM.SEC_EJEC = SIG_PROPUESTA_LOTE.SEC_EJEC AND
						SIG_PROPUESTA_ITEM.TIPO_GENERACION = SIG_PROPUESTA_LOTE.TIPO_GENERACION AND
						SIG_PROPUESTA_ITEM.PROCESO = SIG_PROPUESTA_LOTE.PROCESO AND
						SIG_PROPUESTA_ITEM.SEC_PROCESO = SIG_PROPUESTA_LOTE.SEC_PROCESO AND
						SIG_PROPUESTA_ITEM.CONVOCATORIA = SIG_PROPUESTA_LOTE.CONVOCATORIA AND
						SIG_PROPUESTA_ITEM.SEC_CONVOCATORIA = SIG_PROPUESTA_LOTE.SEC_CONVOCATORIA AND
						SIG_PROPUESTA_ITEM.NRO_LOTE = SIG_PROPUESTA_LOTE.NRO_LOTE AND
						SIG_PROPUESTA_ITEM.PROVEEDOR = SIG_PROPUESTA_LOTE.PROVEEDOR AND
						SIG_PROPUESTA_ITEM.NRO_PROPUESTA = SIG_PROPUESTA_LOTE.NRO_PROPUESTA AND
						SIG_PROPUESTA_ITEM.ANO_EJE = @CANO_EJE AND
						SIG_PROPUESTA_ITEM.SEC_EJEC = @CSEC_EJEC AND
						SIG_PROPUESTA_ITEM.TIPO_GENERACION = @CTIPO_GENERACION AND
						SIG_PROPUESTA_ITEM.PROCESO = @SPROCESO AND
						SIG_PROPUESTA_ITEM.SEC_PROCESO = @SSEC_PROCESO AND
						SIG_PROPUESTA_ITEM.CONVOCATORIA = @SCONVOCATORIA AND
						SIG_PROPUESTA_ITEM.NRO_ITEM = SIG_CONVOCATORIA_ITEM.NRO_ITEM  AND
						SIG_PROPUESTA_LOTE.ADJUDICADO = 'S' )
						--PRIMERO CUENTA SI EXISTE

					END
					ELSE
					BEGIN
						--RECUPERAR DATOS DEL ESTADO Y EL VALOR DE REFERENCIA
						SELECT @SSEC_ITEM = SIG_CONVOCATORIA_ITEM.NRO_ITEM,
						@SCOD_ESTADO = SIG_CONVOCATORIA_ITEM.ESTADO ,
						@SVALOR_REF =  SIG_CONVOCATORIA_ITEM.VALOR_MONEDA
						FROM SIG_CONVOCATORIA_ITEM
						WHERE 
						SIG_CONVOCATORIA_ITEM.ANO_EJE = @CANO_EJE AND
						SIG_CONVOCATORIA_ITEM.SEC_EJEC = @CSEC_EJEC AND
						SIG_CONVOCATORIA_ITEM.TIPO_GENERACION = @CTIPO_GENERACION AND
						SIG_CONVOCATORIA_ITEM.PROCESO = @SPROCESO AND
						SIG_CONVOCATORIA_ITEM.SEC_PROCESO = @SSEC_PROCESO AND
						SIG_CONVOCATORIA_ITEM.CONVOCATORIA = @SCONVOCATORIA AND
						SIG_CONVOCATORIA_ITEM.NRO_ITEM  = 
						(
						SELECT MAX(SIG_PROPUESTA_ITEM.NRO_ITEM)
						FROM SIG_PROPUESTA_ITEM, SIG_PROPUESTA_LOTE
						WHERE 
						SIG_PROPUESTA_ITEM.ANO_EJE = SIG_PROPUESTA_LOTE.ANO_EJE AND
						SIG_PROPUESTA_ITEM.SEC_EJEC = SIG_PROPUESTA_LOTE.SEC_EJEC AND
						SIG_PROPUESTA_ITEM.TIPO_GENERACION = SIG_PROPUESTA_LOTE.TIPO_GENERACION AND
						SIG_PROPUESTA_ITEM.PROCESO = SIG_PROPUESTA_LOTE.PROCESO AND
						SIG_PROPUESTA_ITEM.SEC_PROCESO = SIG_PROPUESTA_LOTE.SEC_PROCESO AND
						SIG_PROPUESTA_ITEM.CONVOCATORIA = SIG_PROPUESTA_LOTE.CONVOCATORIA AND
						SIG_PROPUESTA_ITEM.SEC_CONVOCATORIA = SIG_PROPUESTA_LOTE.SEC_CONVOCATORIA AND
						SIG_PROPUESTA_ITEM.NRO_LOTE = SIG_PROPUESTA_LOTE.NRO_LOTE AND
						SIG_PROPUESTA_ITEM.PROVEEDOR = SIG_PROPUESTA_LOTE.PROVEEDOR AND
						SIG_PROPUESTA_ITEM.NRO_PROPUESTA = SIG_PROPUESTA_LOTE.NRO_PROPUESTA AND
						SIG_PROPUESTA_ITEM.ANO_EJE = @CANO_EJE AND
						SIG_PROPUESTA_ITEM.SEC_EJEC = @CSEC_EJEC AND
						SIG_PROPUESTA_ITEM.TIPO_GENERACION = @CTIPO_GENERACION AND
						SIG_PROPUESTA_ITEM.PROCESO = @SPROCESO AND
						SIG_PROPUESTA_ITEM.SEC_PROCESO = @SSEC_PROCESO AND
						SIG_PROPUESTA_ITEM.CONVOCATORIA = @SCONVOCATORIA AND
						SIG_PROPUESTA_LOTE.ADJUDICADO = 'S' )
						--PRIMERO CUENTA SI EXISTE
					END

					IF @SCOD_ESTADO = '0' 
					BEGIN
						SELECT @SESTADO = 'PENDIENTE'
					END
					IF @SCOD_ESTADO = '1' 
					BEGIN
						SELECT @SESTADO = 'PROCESO'
					END
					IF @SCOD_ESTADO = '2' 
					BEGIN
						SELECT @SESTADO = 'CANCELADO'
					END
					IF @SCOD_ESTADO = '3' 
					BEGIN
						SELECT @SESTADO = 'BUENAPRO'
					END
					IF @SCOD_ESTADO = '4' 
					BEGIN
						SELECT @SESTADO = 'BUENAPRO CONSENTIDA'
					END
					IF @SCOD_ESTADO = '5' 
					BEGIN
						SELECT @SESTADO = 'DESIERTO'
					END
					IF ( @SCOD_ESTADO IS NULL OR RTRIM(LTRIM(@SCOD_ESTADO)) = '') AND  @SCOD_ESTADO <> '5' AND  @SCOD_ESTADO = '4' AND  @SCOD_ESTADO <> '3' AND  @SCOD_ESTADO <> '2' AND  @SCOD_ESTADO <> '1' AND  @SCOD_ESTADO <> '0' 
					BEGIN
						SELECT @SESTADO = 'NO DEFINIDO'
					END

					--POR CADA REGISTRO SE RECUPERAN DATOS DE 
					--PROVEEDOR, RUC, VALOR ADJUDICADO
					--SELECT @NUM = @NUM + 1

					DECLARE CUR_PAAC_ITEM_PROCESO CURSOR FOR
					SELECT SIG_PROPUESTA_ITEM.PROVEEDOR AS WPROVEEDOR,
					( SELECT SIG_CONTRATISTAS.NOMBRE_PROV
					FROM SIG_CONTRATISTAS
					WHERE SIG_CONTRATISTAS.PROVEEDOR = SIG_PROPUESTA_ITEM.PROVEEDOR ) AS WNOM_PROVEEDOR,
					( SELECT SIG_CONTRATISTAS.NRO_RUC
					FROM SIG_CONTRATISTAS
					WHERE SIG_CONTRATISTAS.PROVEEDOR = SIG_PROPUESTA_ITEM.PROVEEDOR ) AS WNRO_RUC_PROVEEDOR,
					SIG_PROPUESTA_ITEM.PRECIO_MONEDA AS WPRECIO_MONEDA,
					SIG_PROPUESTA_ITEM.VALOR_MONEDA AS WVALOR_MONEDA,
					SIG_PROPUESTA_ITEM.CANTIDAD_ADJUDICA AS WCANTIDAD_ADJUDICADA
					FROM SIG_PROPUESTA_ITEM, SIG_PROPUESTA_LOTE
					WHERE 
					SIG_PROPUESTA_ITEM.ANO_EJE = SIG_PROPUESTA_LOTE.ANO_EJE AND
					SIG_PROPUESTA_ITEM.SEC_EJEC = SIG_PROPUESTA_LOTE.SEC_EJEC AND
					SIG_PROPUESTA_ITEM.TIPO_GENERACION = SIG_PROPUESTA_LOTE.TIPO_GENERACION AND
					SIG_PROPUESTA_ITEM.PROCESO = SIG_PROPUESTA_LOTE.PROCESO AND
					SIG_PROPUESTA_ITEM.SEC_PROCESO = SIG_PROPUESTA_LOTE.SEC_PROCESO AND
					SIG_PROPUESTA_ITEM.CONVOCATORIA = SIG_PROPUESTA_LOTE.CONVOCATORIA AND
					SIG_PROPUESTA_ITEM.SEC_CONVOCATORIA = SIG_PROPUESTA_LOTE.SEC_CONVOCATORIA AND
					SIG_PROPUESTA_ITEM.NRO_LOTE = SIG_PROPUESTA_LOTE.NRO_LOTE AND
					SIG_PROPUESTA_ITEM.PROVEEDOR = SIG_PROPUESTA_LOTE.PROVEEDOR AND
					SIG_PROPUESTA_ITEM.NRO_PROPUESTA = SIG_PROPUESTA_LOTE.NRO_PROPUESTA AND
					SIG_PROPUESTA_ITEM.ANO_EJE = @CANO_EJE AND
					SIG_PROPUESTA_ITEM.SEC_EJEC = @CSEC_EJEC AND
					SIG_PROPUESTA_ITEM.TIPO_GENERACION = @CTIPO_GENERACION AND
					SIG_PROPUESTA_ITEM.PROCESO = @SPROCESO AND
					SIG_PROPUESTA_ITEM.SEC_PROCESO = @SSEC_PROCESO AND
					SIG_PROPUESTA_ITEM.CONVOCATORIA = @SCONVOCATORIA AND
					SIG_PROPUESTA_ITEM.NRO_ITEM = @SSEC_ITEM AND
					SIG_PROPUESTA_LOTE.ADJUDICADO = 'S'

					OPEN CUR_PAAC_ITEM_PROCESO
					FETCH CUR_PAAC_ITEM_PROCESO INTO @SPROVEEDOR, @SNOM_PROVEEDOR,
					@SNRO_RUC, @SVALOR_UNIT, @SVALOR_TOTAL, @SCANTIDAD_ADJUDICADA

					SELECT @NUM_PROV = 0

					WHILE @@FETCH_STATUS = 0
					BEGIN
						--INSERTA MOVIMIENTO DE ITEM
						--HAY DATOS DE PROCESO DE SELECCION
						SELECT @NUM_PROV = @NUM_PROV + 1
						SELECT @SADJUDICADO = 'S'

						INSERT INTO TMP_SEGUIMIENTO_PAAC_MODIF
						(
						CREPORTE,CANO_EJE,CSEC_EJEC,CTIPO_CONSOLID,CNRO_CONSOLID,
						CTIPO_GENERACION,CFLAG_PAAC,CNRO_PAAC,CITEM_UNICO,CTIPO_PROCESO,
						CNOM_TIPO_PROCESO,COBJETO,CNOM_OBJETO,CESPEC_TECNICAS,
						ESIGLAS,ESECTOR,EPLIEGO,PNOM_PLIEGO,ENOM_EJECUTORA,
						ERUC_EJEC,CINSTRUMENTO,CVALOR_MONEDA,CFUENTE,
						INRO_ITEM,ITIPO_BIEN,IGRUPO_BIEN,ICLASE_BIEN,IFAMILIA_BIEN,
						IITEM_BIEN,INOMBRE_ITEM,IUNIDAD_MEDIDA,INOMBRE_UNIDAD,
						ICANTIDAD,IVALOR_MONEDA,
						SSEC_ITEM, SVALOR_REF, SESTADO, SNRO_PROCESO_SEL, SNRO_CONVOCATORIA,
						SPROVEEDOR, SNOM_PROVEEDOR, SNRO_RUC, SVALOR_UNIT, SVALOR_TOTAL,
						SCANTIDAD_ADJUDICADA, SNRO_PROV, SADJUDICADO, CNOM_TIPO_PROCESO_ABREV
						)
						VALUES
						(		
						@PN_REPORTE,@CANO_EJE,@CSEC_EJEC,@CTIPO_CONSOLID,@CNRO_CONSOLID,
						@CTIPO_GENERACION,@CFLAG_PAAC,@CNRO_PAAC, @CITEM_UNICO, @CTIPO_PROCESO,
						@CNOM_TIPO_PROCESO, @COBJETO,@CNOM_OBJETO,@CESPEC_TECNICAS,
						@ESIGLAS,@ESECTOR,@EPLIEGO,@PNOM_PLIEGO ,@ENOM_EJECUTORA,
						@ERUC_EJEC,@CINSTRUMENTO,@CVALOR_MONEDA,@CFUENTE,
						@NUM,@ITIPO_BIEN,@IGRUPO_BIEN,@ICLASE_BIEN,@IFAMILIA_BIEN,
						@IITEM_BIEN,@INOMBRE_ITEM ,@IUNIDAD_MEDIDA,@INOMBRE_UNIDAD,
						@ICANTIDAD,@IVALOR_MONEDA ,
						@SSEC_ITEM, @SVALOR_REF,@SESTADO, @SNRO_PROCESO_SEL, @SCONVOCATORIA,
						@SPROVEEDOR, @SNOM_PROVEEDOR, @SNRO_RUC, @SVALOR_UNIT,@SVALOR_TOTAL,
						@SCANTIDAD_ADJUDICADA, @NUM_PROV, @SADJUDICADO, @CNOM_TIPO_PROCESO_ABREV
						)
	
						IF @@ERROR <> 0
						BEGIN
							CLOSE CUR_PAAC_ITEM_PROCESO
							DEALLOCATE CUR_PAAC_ITEM_PROCESO
							CLOSE CUR_PAAC_ITEM
							DEALLOCATE CUR_PAAC_ITEM
							CLOSE CUR_PAAC
							DEALLOCATE CUR_PAAC
							GOTO ERROR
						END

						FETCH CUR_PAAC_ITEM_PROCESO INTO @SPROVEEDOR, @SNOM_PROVEEDOR,
						@SNRO_RUC, @SVALOR_UNIT, @SVALOR_TOTAL, @SCANTIDAD_ADJUDICADA
					END
					CLOSE CUR_PAAC_ITEM_PROCESO
					DEALLOCATE CUR_PAAC_ITEM_PROCESO

				END
			END
			ELSE			
			BEGIN
				--INSERTA MOVIMIENTO DE ITEM
				--NO HAY DATOS DE PROCESO DE SELECCION
				--SELECT @NUM = @NUM + 1
				SELECT @SADJUDICADO = 'N'

				INSERT INTO TMP_SEGUIMIENTO_PAAC_MODIF
				(
				CREPORTE,CANO_EJE,CSEC_EJEC,CTIPO_CONSOLID,CNRO_CONSOLID,
				CTIPO_GENERACION,CFLAG_PAAC,CNRO_PAAC,CITEM_UNICO,CTIPO_PROCESO,
				CNOM_TIPO_PROCESO,COBJETO,CNOM_OBJETO,CESPEC_TECNICAS,
				ESIGLAS,ESECTOR,EPLIEGO,PNOM_PLIEGO,ENOM_EJECUTORA,
				ERUC_EJEC,CINSTRUMENTO,CVALOR_MONEDA,CFUENTE,
				INRO_ITEM,ITIPO_BIEN,IGRUPO_BIEN,ICLASE_BIEN,IFAMILIA_BIEN,
				IITEM_BIEN,INOMBRE_ITEM,IUNIDAD_MEDIDA,INOMBRE_UNIDAD,
				ICANTIDAD,IVALOR_MONEDA,
				SSEC_ITEM, SVALOR_REF, SESTADO, SNRO_PROCESO_SEL, SNRO_CONVOCATORIA,
				SPROVEEDOR, SNOM_PROVEEDOR, SNRO_RUC, SVALOR_UNIT, SVALOR_TOTAL,
				SCANTIDAD_ADJUDICADA, SNRO_PROV, SADJUDICADO, CNOM_TIPO_PROCESO_ABREV
				)
				VALUES
				(		
				@PN_REPORTE,@CANO_EJE,@CSEC_EJEC,@CTIPO_CONSOLID,@CNRO_CONSOLID,
				@CTIPO_GENERACION,@CFLAG_PAAC,@CNRO_PAAC, @CITEM_UNICO, @CTIPO_PROCESO,
				@CNOM_TIPO_PROCESO, @COBJETO,@CNOM_OBJETO,@CESPEC_TECNICAS,
				@ESIGLAS,@ESECTOR,@EPLIEGO,@PNOM_PLIEGO ,@ENOM_EJECUTORA,
				@ERUC_EJEC,@CINSTRUMENTO,@CVALOR_MONEDA,@CFUENTE,
				@NUM,@ITIPO_BIEN,@IGRUPO_BIEN,@ICLASE_BIEN,@IFAMILIA_BIEN,
				@IITEM_BIEN,@INOMBRE_ITEM ,@IUNIDAD_MEDIDA,@INOMBRE_UNIDAD,
				@ICANTIDAD,@IVALOR_MONEDA ,
				0, 0.00,'', '', NULL,
				NULL, '', '', 0.00,0.00,
				0, 0, @SADJUDICADO, @CNOM_TIPO_PROCESO_ABREV
				)

				IF @@ERROR <> 0
				BEGIN
					CLOSE CUR_PAAC_ITEM
					DEALLOCATE CUR_PAAC_ITEM
					CLOSE CUR_PAAC
					DEALLOCATE CUR_PAAC
					GOTO ERROR
				END
			END

			FETCH CUR_PAAC_ITEM INTO @ITIPO_BIEN,@IGRUPO_BIEN,@ICLASE_BIEN,
			@IFAMILIA_BIEN,@IITEM_BIEN,@INOMBRE_ITEM ,@IUNIDAD_MEDIDA,
			@INOMBRE_UNIDAD,@ICANTIDAD,@IVALOR_MONEDA 
		END
		CLOSE CUR_PAAC_ITEM
		DEALLOCATE CUR_PAAC_ITEM
	END

	--ASIGNAR DESCRIPCION DE ESTADO EN CABECERA
	--

	SELECT @CTITULO = ' '

	SELECT @WCUENTA_TOTAL_ITEM = COUNT(*)
	FROM TMP_SEGUIMIENTO_PAAC_MODIF
	WHERE 
	CREPORTE = @PN_REPORTE AND
	CANO_EJE = @CANO_EJE AND
	CSEC_EJEC = @CSEC_EJEC AND
	CTIPO_CONSOLID = @CTIPO_CONSOLID AND
	CNRO_CONSOLID = @CNRO_CONSOLID AND
	CTIPO_GENERACION = @CTIPO_GENERACION
	
	IF @WCUENTA_TOTAL_ITEM IS NULL
	BEGIN
		SELECT @WCUENTA_TOTAL_ITEM = 0 
	END

	SELECT @WCUENTA_TOTAL_ITEM_DESIERTO = COUNT(*)
	FROM TMP_SEGUIMIENTO_PAAC_MODIF
	WHERE 
	CREPORTE = @PN_REPORTE AND
	CANO_EJE = @CANO_EJE AND
	CSEC_EJEC = @CSEC_EJEC AND
	CTIPO_CONSOLID = @CTIPO_CONSOLID AND
	CNRO_CONSOLID = @CNRO_CONSOLID AND
	CTIPO_GENERACION = @CTIPO_GENERACION AND
	SESTADO = 'DESIERTO'

	IF @WCUENTA_TOTAL_ITEM_DESIERTO IS NULL
	BEGIN
		SELECT @WCUENTA_TOTAL_ITEM_DESIERTO = 0 
	END

	SELECT @WCUENTA_TOTAL_ITEM_CANCELADO = COUNT(*)
	FROM TMP_SEGUIMIENTO_PAAC_MODIF
	WHERE 
	CREPORTE = @PN_REPORTE AND
	CANO_EJE = @CANO_EJE AND
	CSEC_EJEC = @CSEC_EJEC AND
	CTIPO_CONSOLID = @CTIPO_CONSOLID AND
	CNRO_CONSOLID = @CNRO_CONSOLID AND
	CTIPO_GENERACION = @CTIPO_GENERACION AND
	SESTADO = 'CANCELADO'

	IF @WCUENTA_TOTAL_ITEM_CANCELADO IS NULL
	BEGIN
		SELECT @WCUENTA_TOTAL_ITEM_CANCELADO = 0 
	END

	SELECT @WCUENTA_TOTAL_ITEM_CONCLUIDO = COUNT(*)
	FROM TMP_SEGUIMIENTO_PAAC_MODIF
	WHERE 
	CREPORTE = @PN_REPORTE AND
	CANO_EJE = @CANO_EJE AND
	CSEC_EJEC = @CSEC_EJEC AND
	CTIPO_CONSOLID = @CTIPO_CONSOLID AND
	CNRO_CONSOLID = @CNRO_CONSOLID AND
	CTIPO_GENERACION = @CTIPO_GENERACION AND
	SESTADO = 'CONCLUIDO'

	IF @WCUENTA_TOTAL_ITEM_CONCLUIDO IS NULL
	BEGIN
		SELECT @WCUENTA_TOTAL_ITEM_CONCLUIDO = 0 
	END

	SELECT @WCUENTA_TOTAL_ITEM_PROCESO = COUNT(*)
	FROM TMP_SEGUIMIENTO_PAAC_MODIF
	WHERE 
	CREPORTE = @PN_REPORTE AND
	CANO_EJE = @CANO_EJE AND
	CSEC_EJEC = @CSEC_EJEC AND
	CTIPO_CONSOLID = @CTIPO_CONSOLID AND
	CNRO_CONSOLID = @CNRO_CONSOLID AND
	CTIPO_GENERACION = @CTIPO_GENERACION AND
	SESTADO = 'PROCESO'

	IF @WCUENTA_TOTAL_ITEM_PROCESO IS NULL
	BEGIN
		SELECT @WCUENTA_TOTAL_ITEM_PROCESO = 0 
	END

	SELECT @WCUENTA_TOTAL_ITEM_PENDIENTE = COUNT(*)
	FROM TMP_SEGUIMIENTO_PAAC_MODIF
	WHERE 
	CREPORTE = @PN_REPORTE AND
	CANO_EJE = @CANO_EJE AND
	CSEC_EJEC = @CSEC_EJEC AND
	CTIPO_CONSOLID = @CTIPO_CONSOLID AND
	CNRO_CONSOLID = @CNRO_CONSOLID AND
	CTIPO_GENERACION = @CTIPO_GENERACION AND
	SESTADO = 'PENDIENTE'

	IF @WCUENTA_TOTAL_ITEM_PENDIENTE IS NULL
	BEGIN
		SELECT @WCUENTA_TOTAL_ITEM_PENDIENTE = 0 
	END



	IF @WCUENTA_TOTAL_ITEM = @WCUENTA_TOTAL_ITEM_DESIERTO AND @WCUENTA_TOTAL_ITEM > 0 
	BEGIN
		SELECT @CTITULO = 'DESIERTO'
	END

	IF @WCUENTA_TOTAL_ITEM = @WCUENTA_TOTAL_ITEM_CANCELADO AND @WCUENTA_TOTAL_ITEM > 0 
	BEGIN
		SELECT @CTITULO = 'CANCELADO'
	END

	IF @WCUENTA_TOTAL_ITEM = @WCUENTA_TOTAL_ITEM_CONCLUIDO AND @WCUENTA_TOTAL_ITEM > 0 
	BEGIN
		SELECT @CTITULO = 'ADJUDICACION TOTAL'
	END


	IF @WCUENTA_TOTAL_ITEM = @WCUENTA_TOTAL_ITEM_PROCESO AND @WCUENTA_TOTAL_ITEM > 0 
	BEGIN
		SELECT @CTITULO = 'PROCESO'
	END

	IF @WCUENTA_TOTAL_ITEM = @WCUENTA_TOTAL_ITEM_PENDIENTE AND @WCUENTA_TOTAL_ITEM > 0 
	BEGIN
		SELECT @CTITULO = 'PENDIENTE'
	END


	IF @WCUENTA_TOTAL_ITEM <> @WCUENTA_TOTAL_ITEM_CONCLUIDO AND @WCUENTA_TOTAL_ITEM > 0 AND @WCUENTA_TOTAL_ITEM_CONCLUIDO > 0
	BEGIN
		SELECT @CTITULO = 'ADJUDICACION PARCIAL'
	END

	IF @WCUENTA_TOTAL_ITEM <> @WCUENTA_TOTAL_ITEM_PROCESO AND @WCUENTA_TOTAL_ITEM > 0 AND @WCUENTA_TOTAL_ITEM_PROCESO > 0
	BEGIN
		SELECT @CTITULO = 'PROCESO'
	END

	IF @WCUENTA_TOTAL_ITEM <> @WCUENTA_TOTAL_ITEM_PENDIENTE AND @WCUENTA_TOTAL_ITEM > 0 AND @WCUENTA_TOTAL_ITEM_PENDIENTE > 0
	BEGIN
		SELECT @CTITULO = 'PROCESO'
	END

	SELECT @WCUENTA_TOTAL_ITEM_BUENA_PRO_S = COUNT(*)
	FROM TMP_SEGUIMIENTO_PAAC_MODIF
	WHERE 
	CREPORTE = @PN_REPORTE AND
	CANO_EJE = @CANO_EJE AND
	CSEC_EJEC = @CSEC_EJEC AND
	CTIPO_CONSOLID = @CTIPO_CONSOLID AND
	CNRO_CONSOLID = @CNRO_CONSOLID AND
	CTIPO_GENERACION = @CTIPO_GENERACION AND
	SESTADO = 'BUENAPRO'AND
	SADJUDICADO = 'S'

	IF @WCUENTA_TOTAL_ITEM_BUENA_PRO_S IS NULL
	BEGIN
		SELECT @WCUENTA_TOTAL_ITEM_BUENA_PRO_S = 0 
	END

	IF @WCUENTA_TOTAL_ITEM > 0 AND @WCUENTA_TOTAL_ITEM_BUENA_PRO_S > 0
	BEGIN
		SELECT @CTITULO = 'CONCLUIDO'
	END


	SELECT @WCUENTA_TOTAL_ITEM_BUENA_PRO_N = COUNT(*)
	FROM TMP_SEGUIMIENTO_PAAC_MODIF
	WHERE 
	CREPORTE = @PN_REPORTE AND
	CANO_EJE = @CANO_EJE AND
	CSEC_EJEC = @CSEC_EJEC AND
	CTIPO_CONSOLID = @CTIPO_CONSOLID AND
	CNRO_CONSOLID = @CNRO_CONSOLID AND
	CTIPO_GENERACION = @CTIPO_GENERACION AND
	SESTADO = 'BUENAPRO'AND
	SADJUDICADO = 'N'

	IF @WCUENTA_TOTAL_ITEM_BUENA_PRO_N IS NULL
	BEGIN
		SELECT @WCUENTA_TOTAL_ITEM_BUENA_PRO_N = 0 
	END

	IF @WCUENTA_TOTAL_ITEM > 0 AND @WCUENTA_TOTAL_ITEM_BUENA_PRO_N > 0
	BEGIN
		SELECT @CTITULO = 'PROCESO'
	END


	SELECT @WCUENTA_TOTAL_ITEM_BUENA_PRO_CON_S = COUNT(*)
	FROM TMP_SEGUIMIENTO_PAAC_MODIF
	WHERE 
	CREPORTE = @PN_REPORTE AND
	CANO_EJE = @CANO_EJE AND
	CSEC_EJEC = @CSEC_EJEC AND
	CTIPO_CONSOLID = @CTIPO_CONSOLID AND
	CNRO_CONSOLID = @CNRO_CONSOLID AND
	CTIPO_GENERACION = @CTIPO_GENERACION AND
	SESTADO = 'BUENAPRO CONSENTIDA'AND
	SADJUDICADO = 'S'

	IF @WCUENTA_TOTAL_ITEM_BUENA_PRO_CON_S IS NULL
	BEGIN
		SELECT @WCUENTA_TOTAL_ITEM_BUENA_PRO_CON_S = 0 
	END

	IF @WCUENTA_TOTAL_ITEM > 0 AND @WCUENTA_TOTAL_ITEM_BUENA_PRO_CON_S > 0
	BEGIN
		SELECT @CTITULO = 'CONCLUIDO'
	END


	SELECT @WCUENTA_TOTAL_ITEM_BUENA_PRO_CON_N = COUNT(*)
	FROM TMP_SEGUIMIENTO_PAAC_MODIF
	WHERE 
	CREPORTE = @PN_REPORTE AND
	CANO_EJE = @CANO_EJE AND
	CSEC_EJEC = @CSEC_EJEC AND
	CTIPO_CONSOLID = @CTIPO_CONSOLID AND
	CNRO_CONSOLID = @CNRO_CONSOLID AND
	CTIPO_GENERACION = @CTIPO_GENERACION AND
	SESTADO = 'BUENAPRO CONSENTIDA'AND
	SADJUDICADO = 'N'

	IF @WCUENTA_TOTAL_ITEM_BUENA_PRO_CON_N IS NULL
	BEGIN
		SELECT @WCUENTA_TOTAL_ITEM_BUENA_PRO_CON_N = 0 
	END

	IF @WCUENTA_TOTAL_ITEM > 0 AND @WCUENTA_TOTAL_ITEM_BUENA_PRO_CON_N > 0
	BEGIN
		SELECT @CTITULO = 'PROCESO'
	END

	UPDATE TMP_SEGUIMIENTO_PAAC_MODIF
	SET CTITULO = @CTITULO
	WHERE
	CREPORTE = @PN_REPORTE AND
	CANO_EJE = @CANO_EJE AND
	CSEC_EJEC = @CSEC_EJEC AND
	CTIPO_CONSOLID = @CTIPO_CONSOLID AND
	CNRO_CONSOLID = @CNRO_CONSOLID AND
	CTIPO_GENERACION = @CTIPO_GENERACION 

	--
	--ASIGNAR DESCRIPCION DE ESTADO EN CABECERA

	FETCH CUR_PAAC INTO @CANO_EJE,@CSEC_EJEC,@CTIPO_CONSOLID,@CNRO_CONSOLID,
	@CTIPO_GENERACION,@CFLAG_PAAC,@CNRO_PAAC,@CITEM_UNICO ,@CTIPO_PROCESO,
	@CNOM_TIPO_PROCESO,@CNOM_TIPO_PROCESO_ABREV, @COBJETO,@CNOM_OBJETO,@CESPEC_TECNICAS,
	@ESIGLAS,@ESECTOR,@EPLIEGO,@PNOM_PLIEGO ,@ENOM_EJECUTORA,
	@ERUC_EJEC,@CINSTRUMENTO, @CVALOR_MONEDA

END

CLOSE CUR_PAAC
DEALLOCATE CUR_PAAC

RETURN 0
 
ERROR:
   RETURN 1;

-- /                                                                                                       






