CREATE PROCEDURE DBO.SP_SI_CARGA_EJEC_PEDIDO
    @P_ANO_EJE   	NUMERIC(4,0),
    @P_SEC_EJEC  	NUMERIC(6,0),
    @fecha_carga_inicio VARCHAR(10),
    @fecha_carga_fin 	VARCHAR(10),
    @usuario_n		varchar(30),
    @O_ERR_NUM   	NUMERIC(6,0) OUTPUT,
    @O_ERR_MSG   	VARCHAR(255) OUTPUT
AS
/******************************************************************************/
/*Descripción  : Inserta resumen de EJECUCIÓN de gastos por ejecutora         */
/*               en tablas finales SI_PEDIDO, SI_PEDIDO_DETA                  */
/*Input        : Todos los IN                                                 */
/*Output       : Todos los OUT                                                */
/*Creación     : 20/FEB/2009 - Sandro Martínez L. (En base a la version       */
/*               para Oracle, desarrollado por Nery Arroyo)                   */
/******************************************************************************/
DECLARE @fecha_carga_inicio_1         DATETIME
DECLARE @fecha_carga_fin_1            DATETIME   

DECLARE @LN_ID_SI_PEDIDO            NUMERIC(10,0)
DECLARE @LN_ID_SI_PEDIDO_DETA       NUMERIC(10,0)
DECLARE @LC_TIPO_BIEN               VARCHAR(1)
DECLARE @LC_TIPO_PEDIDO             CHAR(1)
DECLARE @LC_NRO_PEDIDO              CHAR(5)
DECLARE @LN_SEC_FUNC                NUMERIC(4,0)
DECLARE @LC_FINALIDAD               CHAR(5)
DECLARE @LC_D_FINALIDAD             VARCHAR(250)
DECLARE @LC_META                    VARCHAR(5)
DECLARE @LC_UNIDAD_MEDIDA_META      NUMERIC(3,0)
DECLARE @LC_D_UNIDAD_MEDIDA_META    VARCHAR(100)
DECLARE @LC_ITEM_CATALOGO           VARCHAR(20)
DECLARE @LC_NOMBRE_ITEM             VARCHAR(100)
DECLARE @LC_D_UNIDAD_MEDIDA_ITEM_BS VARCHAR(100)
DECLARE @LS_CENTRO_COSTO            VARCHAR(15)
DECLARE @LS_D_CENTRO_COSTO          VARCHAR(100)
DECLARE @LD_FECHA_PEDIDO            DATETIME
DECLARE @LD_FECHA_PECOSA            DATETIME
DECLARE @LI_MES_PEDIDO              INTEGER 
DECLARE @LS_MOTIVO_PEDIDO           VARCHAR(3000)
DECLARE @LS_EMPLEADO                VARCHAR(15)
DECLARE @LS_D_EMPLEADO              VARCHAR(100)
DECLARE @LC_TIPO_USO                CHAR(1)
DECLARE @LC_ESTADO                  CHAR(1)
DECLARE @LC_GRUPO_BIEN              CHAR(2)
DECLARE @LC_CLASE_BIEN              CHAR(2)
DECLARE @LC_FAMILIA_BIEN            CHAR(4)
DECLARE @LC_ITEM_BIEN               CHAR(4)
DECLARE @LN_UNIDAD_MEDIDA           NUMERIC(3,0)
DECLARE @LN_CANT_SOLICITADA         NUMERIC(20,6)
DECLARE @LN_CANT_APROBADA           NUMERIC(20,6)
DECLARE @LN_CANT_ATENDIDA           NUMERIC(20,6)
DECLARE @LN_@PRECIO_UNIT            NUMERIC(16,6)
DECLARE @LN_@VALOR_TOTAL            NUMERIC(16,2)
DECLARE @LC_ESTADO_PED              CHAR(1)
DECLARE @LS_CLASIFICADOR            VARCHAR(20)
DECLARE @LN_NRO_ORDEN               NUMERIC(7,0)
DECLARE @LN_NRO_CUADRO              NUMERIC(6,0)
DECLARE @LN_NRO_PECOSA              NUMERIC(5,0)

BEGIN  
    /*CAMBIA A TIPO DATE A LAS VARIABLES RECIBIDAS, PARA EL RANGO DE FECHAS */
    SET @fecha_carga_inicio_1 = Convert(DATETIME, @fecha_carga_inicio, 101)
    SET @fecha_carga_fin_1    = Convert(DATETIME, @fecha_carga_fin, 101)    

    /*ELIMINA DATA*/
    DELETE FROM SI_PEDIDO_DETA
    DELETE FROM SI_PEDIDO
      
    /*CORRELATIVO DE PEDIDO*/
    SELECT @LN_ID_SI_PEDIDO = MAX(SIP.ID_SI_PEDIDO) 
    FROM SI_PEDIDO SIP
    WHERE SIP.ANO_EJE=@P_ANO_EJE 
      AND SIP.SEC_EJEC=@P_SEC_EJEC

    IF @LN_ID_SI_PEDIDO IS NULL
      SET @LN_ID_SI_PEDIDO = 0

    /*CARGA DE PEDIDOS*/
    DECLARE C_1 CURSOR FOR
      SELECT P.TIPO_PEDIDO, 
             P.TIPO_BIEN, 
             P.NRO_PEDIDO, 
             P.CENTRO_COSTO,
             P.FECHA_PEDIDO, 
             P.MES_PEDIDO, 
             P.MOTIVO_PEDIDO, 
             P.SEC_FUNC, 
             P.EMPLEADO, 
             P.TIPO_USO, 
             P.ESTADO
      FROM SIG_PEDIDOS P 
      WHERE P.ANO_EJE = @P_ANO_EJE 
        AND P.SEC_EJEC = @P_SEC_EJEC
       AND (P.FECHA_PEDIDO >= @fecha_carga_inicio_1 
        AND P.FECHA_PEDIDO <= @fecha_carga_fin_1)

    OPEN C_1
    FETCH NEXT FROM C_1 
    INTO @LC_TIPO_PEDIDO, @LC_TIPO_BIEN, @LC_NRO_PEDIDO, 
	 @LS_CENTRO_COSTO, @LD_FECHA_PEDIDO, @LI_MES_PEDIDO, 
	 @LS_MOTIVO_PEDIDO, @LN_SEC_FUNC, @LS_EMPLEADO, 
	 @LC_TIPO_USO, @LC_ESTADO

    WHILE @@FETCH_STATUS = 0
    BEGIN

        /*CAMPOS DE META SEGUN AÑO, EJECUTORA Y SEC_FUNC*/
        SELECT @LC_META = META, 
               @LC_UNIDAD_MEDIDA_META = UNIDAD_MEDIDA,
               @LC_FINALIDAD = FINALIDAD
         FROM META
        WHERE ANO_EJE  = @P_ANO_EJE 
          AND SEC_EJEC = @P_SEC_EJEC
          AND SEC_FUNC = @LN_SEC_FUNC

         /*DESCRIPCIÓN DE UNIDAD DE MEDIDA DE META*/
        SELECT @LC_D_UNIDAD_MEDIDA_META = NOMBRE 
          FROM UNIDAD_MEDIDA
         WHERE UNIDAD_MEDIDA = @LC_UNIDAD_MEDIDA_META

         /*DESCRIPCIÓN DE FINALIDAD DE META*/
        SELECT @LC_D_FINALIDAD = NOMBRE
          FROM FINALIDAD
         WHERE ANO_EJE   = @P_ANO_EJE 
           AND FINALIDAD = @LC_FINALIDAD

         /*DESCRIPCIÓN DE CENTRO DE COSTO*/
        SELECT @LS_D_CENTRO_COSTO = NOMBRE_DEPEND
          FROM SIG_CENTRO_COSTO
         WHERE ANO_EJE   = @P_ANO_EJE 
           AND SEC_EJEC  = @P_SEC_EJEC
           AND CENTRO_COSTO = @LS_CENTRO_COSTO

         /*DESCRIPCIÓN DE CENTRO DE COSTO*/
        SELECT @LS_D_EMPLEADO = apellido_paterno + ' ' + apellido_materno + '' + nombres
          FROM SIG_PERSONAL
         WHERE SEC_EJEC  = @P_SEC_EJEC
           AND EMPLEADO = @LS_EMPLEADO

        SET @LN_ID_SI_PEDIDO = @LN_ID_SI_PEDIDO + 1

        INSERT INTO SI_PEDIDO
        (ANO_EJE, SEC_EJEC, ID_SI_PEDIDO, TIPO_PEDIDO, TIPO_BIEN,
         NRO_PEDIDO, CENTRO_COSTO, FECHA_PEDIDO, MES_PEDIDO, MOTIVO_PEDIDO,
         SEC_FUNC, FINALIDAD, D_FINALIDAD, META, UNIDAD_MEDIDA_META, 
	 D_UNIDAD_MEDIDA_META, EMPLEADO, TIPO_USO, ESTADO, D_CENTRO_COSTO, 
	 D_EMPLEADO, FECHA_CARGA_INICIO, FECHA_CARGA_FIN, 
	 FECHA_ENVIO, USUARIO_ENVIO)

        VALUES (@P_ANO_EJE, @P_SEC_EJEC, @LN_ID_SI_PEDIDO, 
	@LC_TIPO_PEDIDO, @LC_TIPO_BIEN, @LC_NRO_PEDIDO, @LS_CENTRO_COSTO, 
	@LD_FECHA_PEDIDO, @LI_MES_PEDIDO, @LS_MOTIVO_PEDIDO,
        @LN_SEC_FUNC, @LC_FINALIDAD, @LC_D_FINALIDAD, @LC_META, 
	@LC_UNIDAD_MEDIDA_META, @LC_D_UNIDAD_MEDIDA_META,
        @LS_EMPLEADO, @LC_TIPO_USO, @LC_ESTADO, @LS_D_CENTRO_COSTO, 
	@LS_D_EMPLEADO, @fecha_carga_inicio_1, @fecha_carga_fin_1,
        getdate(), @usuario_n) 

        /*CURSOR DE DETALLE_ORDEN*/   
        DECLARE C_2 CURSOR FOR
             SELECT GRUPO_BIEN,
                    CLASE_BIEN,
                    FAMILIA_BIEN,
                    ITEM_BIEN,
                    UNIDAD_MEDIDA,
                    CANT_SOLICITADA,
                    CANT_APROBADA,
                    CANT_ATENDIDA,
                    PRECIO_UNIT,
                    VALOR_TOTAL,
                    ESTADO_PED,
                    CLASIFICADOR,
                    NRO_ORDEN,
                    NRO_CUADRO,
                    NRO_PECOSA,
                    FECHA_PECOSA
            FROM SIG_DETALLE_PEDIDOS 
            WHERE ANO_EJE     = @P_ANO_EJE 
              AND SEC_EJEC    = @P_SEC_EJEC 
              AND TIPO_BIEN   = @LC_TIPO_BIEN
              AND TIPO_PEDIDO = @LC_TIPO_PEDIDO 
              AND NRO_PEDIDO  = @LC_NRO_PEDIDO

        OPEN C_2
        FETCH NEXT FROM C_2 
        INTO @LC_GRUPO_BIEN, @LC_CLASE_BIEN, @LC_FAMILIA_BIEN, 
	     @LC_ITEM_BIEN, @LN_UNIDAD_MEDIDA, @LN_CANT_SOLICITADA, 
	     @LN_CANT_APROBADA, @LN_CANT_ATENDIDA, @LN_@PRECIO_UNIT, 
             @LN_@VALOR_TOTAL, @LC_ESTADO_PED, @LS_CLASIFICADOR, 
	     @LN_NRO_ORDEN, @LN_NRO_CUADRO, @LN_NRO_PECOSA, 
	     @LD_FECHA_PECOSA

        WHILE @@FETCH_STATUS = 0
        BEGIN
            SET @LC_ITEM_CATALOGO = @LC_GRUPO_BIEN + @LC_CLASE_BIEN + @LC_FAMILIA_BIEN + @LC_ITEM_BIEN

            /*DESCRIPCIÓN DE ITEM CATÁLOGO B/S*/
   SELECT @LC_NOMBRE_ITEM = CAT.NOMBRE_ITEM
            FROM CATALOGO_BIEN_SERV_ORIGINAL CAT
            WHERE CAT.TIPO_BIEN    = @LC_TIPO_BIEN
              AND CAT.GRUPO_BIEN   = @LC_GRUPO_BIEN
              AND CAT.CLASE_BIEN   = @LC_CLASE_BIEN
              AND CAT.FAMILIA_BIEN = @LC_FAMILIA_BIEN
              AND CAT.ITEM_BIEN    = @LC_ITEM_BIEN 

            /*DESCRIPCIÓN DE UNIDAD DE MEDIDA DE ITEM CATÁLOGO B/S*/
            SELECT @LC_D_UNIDAD_MEDIDA_ITEM_BS = M.NOMBRE
            FROM UNIDAD_MEDIDA M
            WHERE M.UNIDAD_MEDIDA = @LN_UNIDAD_MEDIDA

            /*MAXIMO SECUENCIAL EN SI_PEDIDO_DETA*/
            SELECT @LN_ID_SI_PEDIDO_DETA = MAX(SIPD.ID_SI_PEDIDO_DETA)
            FROM SI_PEDIDO_DETA SIPD
            WHERE SIPD.ANO_EJE      = @P_ANO_EJE 
              AND SIPD.SEC_EJEC     = @P_SEC_EJEC
              AND SIPD.ID_SI_PEDIDO = @LN_ID_SI_PEDIDO

            IF @LN_ID_SI_PEDIDO_DETA IS NULL
                SET @LN_ID_SI_PEDIDO_DETA = 0

            SET @LN_ID_SI_PEDIDO_DETA = @LN_ID_SI_PEDIDO_DETA + 1
                          
            INSERT INTO SI_PEDIDO_DETA
            (ANO_EJE, SEC_EJEC, ID_SI_PEDIDO, ID_SI_PEDIDO_DETA,
            ITEM_CATALOGO, D_ITEM_CATALOGO, UNIDAD_MEDIDA_ITEM_BS, 
	    D_UNIDAD_MEDIDA_ITEM_BS, CLASIFICADOR, CANT_SOLICITADA, 
	    PRECIO_UNIT, VALOR_TOTAL, NRO_ORDEN, NRO_CUADRO, ESTADO_PED, 
	    CANT_APROBADA, CANT_ATENDIDA, NRO_PECOSA, FECHA_PECOSA, 
	    FECHA_CARGA_INICIO, FECHA_CARGA_FIN, FECHA_ENVIO, USUARIO_ENVIO)

            VALUES(@P_ANO_EJE, @P_SEC_EJEC, @LN_ID_SI_PEDIDO, @LN_ID_SI_PEDIDO_DETA,
            @LC_ITEM_CATALOGO, @LC_NOMBRE_ITEM, @LN_UNIDAD_MEDIDA, 
	    @LC_D_UNIDAD_MEDIDA_ITEM_BS, @LS_CLASIFICADOR, @LN_CANT_SOLICITADA, 
	    @LN_@PRECIO_UNIT, @LN_@VALOR_TOTAL, @LN_NRO_ORDEN, @LN_NRO_CUADRO, 
	    @LC_ESTADO_PED, @LN_CANT_APROBADA, @LN_CANT_ATENDIDA, 
            @LN_NRO_PECOSA, @LD_FECHA_PECOSA, @fecha_carga_inicio_1, 
	    @fecha_carga_fin_1, getdate(), @usuario_n)
             
            FETCH NEXT FROM C_2 
            INTO @LC_GRUPO_BIEN, @LC_CLASE_BIEN, @LC_FAMILIA_BIEN, 
		     @LC_ITEM_BIEN, @LN_UNIDAD_MEDIDA, @LN_CANT_SOLICITADA, 
		     @LN_CANT_APROBADA, @LN_CANT_ATENDIDA, @LN_@PRECIO_UNIT, 
                     @LN_@VALOR_TOTAL, @LC_ESTADO_PED, @LS_CLASIFICADOR, 
		     @LN_NRO_ORDEN, @LN_NRO_CUADRO, @LN_NRO_PECOSA, 
		     @LD_FECHA_PECOSA
         END
         CLOSE C_2
         DEALLOCATE C_2

         FETCH NEXT FROM C_1
         INTO     @LC_TIPO_PEDIDO, @LC_TIPO_BIEN, 
		  @LC_NRO_PEDIDO, @LS_CENTRO_COSTO, @LD_FECHA_PEDIDO, 
                  @LI_MES_PEDIDO, @LS_MOTIVO_PEDIDO, @LN_SEC_FUNC, 
		  @LS_EMPLEADO, @LC_TIPO_USO, @LC_ESTADO
     END
     CLOSE C_1
     DEALLOCATE C_1
END
