CREATE PROCEDURE SP_SI_TRANSMISION_ORDEN
@P_ANO_EJE numeric(4, 0), @P_SEC_EJEC numeric(6, 0), @O_ERR_NUM numeric(6, 0) OUTPUT, @O_ERR_MSG varchar(255) OUTPUT
WITH EXEC AS CALLER
AS
BEGIN
 	
 	IF OBJECT_ID ('dbo.TMP_SIG_ORDEN') IS NOT NULL
	DROP TABLE dbo.TMP_SIG_ORDEN

	truncate TABLE dbo.SI_TRANS_ORDEN
 	
 	
	 SELECT dsd.sector,
		   dsd.SECTOR + ' - ' + RTRIM(S.NOMBRE) NOM_SECTOR,
		   dsd.pliego PLIEGO,
		   RTRIM(DSD.pliego + ' - ' + P.nombre) NOM_PLIEGO,
		   A.SEC_EJEC,
		   CONVERT(VARCHAR, EJC.sec_ejec) + ' - ' + EJC.nombre NOM_EJECUTORA,
		   A.MES_CALEND MES_ORDEN,
		   A.NRO_ORDEN,
		   A.FECHA_ORDEN,
		   A.FECHA_CONTRATO,
		   A.TIPO_PROCESO,
		   A.NRO_PROC_SEL,
		   B.NRO_RUC PROVEEDOR_NRO_RUC,
		   dbo.f_elimina_tabs(B.NOMBRE_PROV) D_PROVEEDOR,
		   A.TIPO_BIEN,
		   OI.GRUPO_BIEN,
		   OI.CLASE_BIEN,
		   OI.FAMILIA_BIEN,
		   OI.ITEM_BIEN,
		   OI.CANT_ITEM,
		   OI.PREC_UNIT_MONEDA,
		   A.MONEDA,
		   OI.PREC_TOT_SOLES,
		   OI.UNIDAD_MEDIDA,
		   A.FECHA_RECEPCION,
		   A.PLAZO_ENTREGA,
		   sma.FECHA_CONFIRMA,
		   EESS.CATEGORIA,
		  CASE  OIP.FUENTE_FINANC
			 WHEN '00' THEN '00 - RECURSOS ORDINARIOS'
			 WHEN '09' THEN '09 - RECURSOS DIRECTAMENTE RECAUDADOS'
   		   END FUENTE_FINANC_NOM,
		   SUBSTRING(OIP.CLASIFICADOR, 1, 3) GENERICA,
		   SUBSTRING(OIP.CLASIFICADOR, 1, 6) SUB_GENERICA1,
		   SUBSTRING(OIP.CLASIFICADOR, 1, 9) SUB_GENERICA2,
		   SUBSTRING(OIP.CLASIFICADOR, 1, 12) ESPECIFICA1,
		   OIP.CLASIFICADOR ESPECIFICA2,
		   SCC.CENTRO_COSTO,
		   SCC.CENTRO_COSTO + ' - ' + SCC.ABREVIADO_DEPEND NOM_CENTRO_COSTO,
		   COALESCE(EESS.COD_OGEI, 0) PTO_ATEN,
		  (COALESCE(EESS.COD_OGEI,'') +' - '+ COALESCE(EESS.DESC_ESTABLEC,'') )PTO_ATEN_NOMBRE,
		   LTRIM(RTRIM(CA.NOMBRE_CORTO)) nom_categoria,
		   EESS.SECTOR_AMBITO,
		   OIP.SEC_FUNC,		 
		   ( SELECT TE.ID_SUB_FINALIDAD
			   FROM SIG_TAREA_ESTRATEGICO  TE
		     WHERE  TE.ANO_EJE= SCA.ANO_EJE AND 
				    TE.SEC_EJEC = SCA.SEC_EJEC AND 
					TE.TIPO_TAREA =  SCA.TIPO_TAREA AND
					TE.NIVEL_TAREA = sca.nivel_tarea AND 
					TE.TAREA_GENERAL = sca.tarea_general ) ID_SUB_FINALIDAD
	INTO TMP_SIG_ORDEN
	FROM   SIG_ORDEN_ADQUISICION A
		   JOIN SIG_CUADRO_ADQUISICION sca
				ON  (
						sca.ano_eje = a.ANO_EJE
						AND sca.SEC_EJEC = a.SEC_EJEC
						AND sca.TIPO_BIEN = a.TIPO_BIEN
						AND sca.SEC_CUADRO = a.SEC_CUADRO
						AND SCA.NRO_ORDEN = A.NRO_ORDEN
					)
		   JOIN SIG_ORDEN_ITEM_PPTO OIP
				ON  (
						A.ANO_EJE = OIP.ANO_EJE
						AND A.SEC_EJEC = OIP.SEC_EJEC
						AND A.NRO_ORDEN = OIP.NRO_ORDEN
						AND A.TIPO_BIEN = OIP.TIPO_BIEN
						AND A.TIPO_PPTO = OIP.TIPO_PPTO
					)
		   JOIN SIG_ORDEN_ITEM OI
				ON  (
						OIP.ANO_EJE = OI.ANO_EJE
						AND OIP.SEC_EJEC = OI.SEC_EJEC
						AND OIP.NRO_ORDEN = OI.NRO_ORDEN
						AND OIP.TIPO_BIEN = OI.TIPO_BIEN
						AND OIP.SEC_ITEM = OI.SEC_ITEM
					)
		   LEFT OUTER JOIN SIG_CONTRATISTAS B
				ON  (B.PROVEEDOR = A.PROVEEDOR)
		   LEFT OUTER  JOIN SIG_CENTRO_COSTO SCC
				ON  (
						SCC.ANO_EJE = A.ANO_EJE
						AND SCC.SEC_EJEC = A.sec_ejec
						AND SCC.CENTRO_COSTO = SCA.centro_costo
					)
		   JOIN SIG_SEDES DSD
				ON  (DSD.SEDE = SCC.SEDE AND DSD.pliego = SCC.pliego)
		   LEFT OUTER JOIN SIG_PPR_SEDE CSD
				ON  (
						CSD.ANO_EJE = SCC.ANO_EJE
						AND CSD.SEC_EJEC = SCC.SEC_EJEC
						AND CSD.PLIEGO = SCC.PLIEGO
						AND CSD.SEDE = SCC.SEDE
					)
		   LEFT OUTER JOIN SIG_PPR_ESTABLECIMIENTO EESS
				ON  (
						EESS.ANO_EJE = CSD.ANO_EJE
						AND EESS.SEC_EJEC = CSD.SEC_EJEC
						AND EESS.COD_ESTABLEC = CSD.COD_ESTABLEC
					)
		   LEFT OUTER JOIN SIG_PPR_CATEGORIA CA
				ON  (
						CA.ANO_EJE = CSD.ANO_EJE
						AND CA.SECTOR_AMBITO = '01'
						AND CA.CATEGORIA = EESS.CATEGORIA
					)
		   JOIN sector s
				ON  (S.SECTOR = DSD.sector)
		   JOIN pliego p
				ON  (P.PLIEGO = DSD.pliego AND P.sector = DSD.sector)
		   JOIN ejecutora EJC
				ON  (EJC.SEC_EJEC = A.SEC_EJEC)
		   LEFT OUTER JOIN SIG_MOVIM_ALMACEN sma
				ON ( 
        			SMA.SEC_EJEC = A.SEC_EJEC AND
        			SMA.ANO_EJE = A.ANO_EJE AND
        			SMA.ALMACEN = A.ALMACEN AND
        			SMA.SEC_ALMACEN = A.SEC_ALMACEN  AND
        			SMA.TIPO_PPTO = A.TIPO_PPTO AND
        			SMA.NRO_ORDEN = A.NRO_ORDEN          		
				   )    
	WHERE  A.ANO_EJE =@P_ANO_EJE AND -- 2013       AND --@P_ANO_EJE AND
		   A.SEC_EJEC = @P_SEC_EJEC --870                                                      
	
	
	--2. REGISTRA LA INFORMACION EN TABLA FISICA
	
	INSERT INTO SI_TRANS_ORDEN 
	(	ANO_EJE,		  SECTOR,			NOM_SECTOR,		PLIEGO,				NOM_PLIEGO,		SEC_EJEC,		NOM_EJECUTORA,	
		MES_ORDEN,		  NRO_ORDEN,		FECHA_ORDEN,	FECHA_CONTRATO,		TIPO_PROCESO,	NRO_PROC_SEL,	PROVEEDOR_NRO_RUC,	
		D_PROVEEDOR,  	  TIPO_BIEN,		GRUPO_BIEN,		CLASE_BIEN,			FAMILIA_BIEN,	ITEM_BIEN,		CANTIDAD_ITEM,
		PRECIO_UNITARIO,  MONEDA,			MONTO_SOLES,	UNIDAD_MEDIDA_ORDEN,FECHA_RECEPCION,PLAZO_ENTREGA,	FECHA_INTERNAMIENTO,
		FUENTE_FINANCIAMIENTO,GENERICA,	SUB_GENERICA1,		SUB_GENERICA2,	ESPECIFICA1,	ESPECIFICA2,
		CENTRO_COSTO,	  NOM_CENTRO_COSTO,	PTO_ATEN,		PTO_ATEN_NOMBRE,	PTO_ATEN_CATEGORIA,SECTOR_AMBITO, SEC_FUNC ,
		ID_SUB_FINALIDAD)
	SELECT 
		@P_ANO_EJE,		  sector ,			NOM_SECTOR,		PLIEGO,			NOM_PLIEGO,			SEC_EJEC,		NOM_EJECUTORA,	
		MES_ORDEN,		  NRO_ORDEN,		FECHA_ORDEN,	FECHA_CONTRATO,	TIPO_PROCESO,		NRO_PROC_SEL,	PROVEEDOR_NRO_RUC,	
		D_PROVEEDOR,	  TIPO_BIEN,		GRUPO_BIEN,		CLASE_BIEN,		FAMILIA_BIEN,		ITEM_BIEN,		CANT_ITEM,	
		PREC_UNIT_MONEDA, MONEDA,			PREC_TOT_SOLES,	UNIDAD_MEDIDA,	FECHA_RECEPCION,	PLAZO_ENTREGA,	FECHA_CONFIRMA,
		FUENTE_FINANC_NOM,	GENERICA,		SUB_GENERICA1,	SUB_GENERICA2,		ESPECIFICA1,	ESPECIFICA2,
		CENTRO_COSTO,	  NOM_CENTRO_COSTO,	PTO_ATEN,		PTO_ATEN_NOMBRE,	nom_categoria,		SECTOR_AMBITO 	,SEC_FUNC,
		ID_SUB_FINALIDAD	
	 from  TMP_SIG_ORDEN
						
/**3. Unidad medida - Catálogo**/		 
	UPDATE SI_TRANS_ORDEN
	SET    UNIDAD_MEDIDA_ITEM_BS = (
									   SELECT unidad_medida
									   FROM   catalogo_bien_serv c
									   WHERE  c.SEC_EJEC = SI_TRANS_ORDEN.sec_ejec
											  AND c.TIPO_BIEN = SI_TRANS_ORDEN.TIPO_BIEN
											  AND c.GRUPO_BIEN = SI_TRANS_ORDEN.GRUPO_BIEN
											  AND c.CLASE_BIEN = SI_TRANS_ORDEN.CLASE_BIEN
											  AND c.FAMILIA_BIEN = SI_TRANS_ORDEN.FAMILIA_BIEN
											  AND c.ITEM_BIEN = SI_TRANS_ORDEN.ITEM_BIEN
								   )
	WHERE  ANO_EJE = @P_ANO_EJE AND --2013  AND --
		   SEC_EJEC = @P_SEC_EJEC --1264 --
       
  UPDATE SI_TRANS_ORDEN
	SET    D_UNIDAD_MEDIDA_ITEM_BS = (
									   SELECT NOMBRE 
									   FROM   unidad_medida c
									   WHERE  C.UNIDAD_MEDIDA = SI_TRANS_ORDEN.UNIDAD_MEDIDA_ITEM_BS AND
											  C.ESTADO = 'A'
								   )
	WHERE  ANO_EJE = @P_ANO_EJE AND 
		   SEC_EJEC = @P_SEC_EJEC     

/**4.GRUPO**/	
	UPDATE 	SI_TRANS_ORDEN
	SET GRUPO_NOMBRE= TIPO_BIEN+GRUPO_BIEN+' - '+(	SELECT nombre_grupo 
						FROM grupo_bien_serv
						WHERE tipo_bien= SI_TRANS_ORDEN.TIPO_BIEN AND grupo_bien=SI_TRANS_ORDEN.GRUPO_BIEN AND
						ESTADO ='A') 	
	   
	WHERE
	ano_eje=@P_ANO_EJE AND
	SEC_EJEC=@P_SEC_EJEC 


/**5.CLASE**/	
	UPDATE 	SI_TRANS_ORDEN
	SET CLASE_NOMBRE =TIPO_BIEN+GRUPO_BIEN+ CLASE_BIEN+' - '+(	SELECT nombre_clase 
						FROM clase_bien_serv
						WHERE tipo_bien= SI_TRANS_ORDEN.TIPO_BIEN AND 
						grupo_bien=SI_TRANS_ORDEN.grupo_bien AND
						clase_bien= SI_TRANS_ORDEN.CLASE_BIEN AND
						ESTADO ='A') 	
	   
	WHERE
	ano_eje  =@P_ANO_EJE AND
	SEC_EJEC =@P_SEC_EJEC 


/**6. FAMILIA**/	
	UPDATE 	SI_TRANS_ORDEN
	SET FAMILIA_NOMBRE=TIPO_BIEN+GRUPO_BIEN+ CLASE_BIEN+ FAMILIA_BIEN+' - '+(	SELECT nombre_fam 
																				FROM familia_bien_serv
																				WHERE	tipo_bien= SI_TRANS_ORDEN.TIPO_BIEN AND 
																						grupo_bien=SI_TRANS_ORDEN.grupo_bien 
																						AND clase_bien= SI_TRANS_ORDEN.CLASE_BIEN AND 
																						familia_bien=SI_TRANS_ORDEN.FAMILIA_BIEN AND
																						ESTADO ='A') 	
	   
	WHERE
	ano_eje=@P_ANO_EJE AND
	SEC_EJEC=@P_SEC_EJEC 

/**7. ITEM**/	
	UPDATE 	SI_TRANS_ORDEN
	SET ITEM_NOMBRE= SUBSTRING(TIPO_BIEN+GRUPO_BIEN+ CLASE_BIEN+ FAMILIA_BIEN+ITEM_BIEN+' - '+(	SELECT NOMBRE_ITEM 
																						FROM CATALOGO_BIEN_SERV
																						WHERE 
																							SEC_EJEC= SI_TRANS_ORDEN.SEC_EJEC AND
																						tipo_bien= SI_TRANS_ORDEN.TIPO_BIEN AND 
																						grupo_bien=SI_TRANS_ORDEN.grupo_bien 
																						AND clase_bien= SI_TRANS_ORDEN.CLASE_BIEN AND 
																						familia_bien=SI_TRANS_ORDEN.FAMILIA_BIEN 
																						AND ITEM_BIEN= SI_TRANS_ORDEN.ITEM_BIEN AND					
																						ESTADO ='A'), 1, 150) 	
	WHERE
	ano_eje=@P_ANO_EJE AND
	SEC_EJEC=@P_SEC_EJEC    
       
       
 /**8. PROGRAMA PPTO**/	
	UPDATE SI_TRANS_ORDEN
	SET PROGRAMA_PPTO = (SELECT M.ESTRATEGIA_NACIONAL
							FROM META M
							WHERE M.ANO_EJE= SI_TRANS_ORDEN.ano_eje AND 
							M.SEC_EJEC= SI_TRANS_ORDEN.SEC_EJEC AND
							M.SEC_FUNC= SI_TRANS_ORDEN.sec_func ) 
	WHERE  
	ano_eje=@P_ANO_EJE AND
	SEC_EJEC=@P_SEC_EJEC 


/**9 Nombre PROGRAMA PPTO**/

	UPDATE SI_TRANS_ORDEN
	SET PROGRAMA_NOMBRE  = PROGRAMA_PPTO+' - '+(SELECT enn.NOMBRE
												FROM 
												ESTRATEGIA_NACIONAL_NOMBRE enn
												WHERE enn.ANO_EJE= SI_TRANS_ORDEN.ano_eje AND
												enn.ESTRATEGIA_NACIONAL= SI_TRANS_ORDEN.PROGRAMA_PPTO AND
												enn.ESTADO='A') 
	WHERE  
	ano_eje  = @P_ANO_EJE AND
	SEC_EJEC = @P_SEC_EJEC AND 
	PROGRAMA_PPTO NOT IN ('9001','9002')


	UPDATE SI_TRANS_ORDEN
	SET PROGRAMA_NOMBRE = '0000 - SIN PROGRAMA PRESUPUESTAL'
	WHERE  
	ano_eje=@P_ANO_EJE AND
	SEC_EJEC=@P_SEC_EJEC AND
	PROGRAMA_PPTO  IN ('9001','9002')


/**10. Producto**/
	UPDATE SI_TRANS_ORDEN
	SET PRODUCTO = (SELECT smp.ACT_PROY
							FROM meta smp 
							WHERE smp.ANO_EJE= SI_TRANS_ORDEN.ano_eje AND 
							smp.SEC_EJEC= SI_TRANS_ORDEN.SEC_EJEC AND
							smp.SEC_FUNC= SI_TRANS_ORDEN.sec_func ) 
	WHERE  
	ano_eje = @P_ANO_EJE AND
	SEC_EJEC= @P_SEC_EJEC 
	
/**11. Producto Nombre**/	
	UPDATE SI_TRANS_ORDEN
	SET PRODUCTO_NOMBRE = PRODUCTO+' - '+(  SELECT NOMBRE 
											FROM Act_Proy_Nombre  
											WHERE ANO_EJE= SI_TRANS_ORDEN.ano_eje AND 
												  act_proy= SI_TRANS_ORDEN.PRODUCTO   AND 
												  estado= 'A'											
											) 
	WHERE  
	ano_eje =@P_ANO_EJE AND
	SEC_EJEC=@P_SEC_EJEC  AND 
	PRODUCTO NOT IN ('3999999')

	UPDATE SI_TRANS_ORDEN
	SET PRODUCTO_NOMBRE = '000000 - SIN PRODUCTO'
	WHERE  
	ano_eje=@P_ANO_EJE AND
	SEC_EJEC=@P_SEC_EJEC AND 
	PRODUCTO  IN ('3999999')
 	       
 /**12. SubProducto**/	   
 UPDATE SI_TRANS_ORDEN
 SET SUBPRODUCTO = ( SELECT SUB.SUB_FINALIDAD FROM SIG_SUB_FINALIDAD SUB 
                      WHERE SUB.ANO_EJE = SI_TRANS_ORDEN.ANO_EJE AND
							SUB.ID_SUB_FINALIDAD = SI_TRANS_ORDEN.ID_SUB_FINALIDAD  AND
							SUB.ESTADO = 'A' )
 WHERE ano_eje = @P_ANO_EJE
	   AND SEC_EJEC = @P_SEC_EJEC AND
	   ID_SUB_FINALIDAD IS NOT NULL  	
					
 UPDATE SI_TRANS_ORDEN
 SET SUBPRODUCTO = '0000000'
 WHERE ano_eje = @P_ANO_EJE
	   AND SEC_EJEC = @P_SEC_EJEC AND
	   ID_SUB_FINALIDAD IS NULL  					
					
  /**13. SUBPRODUCTO NOMBRE**/
  UPDATE SI_TRANS_ORDEN
 SET SUBPRODUCTO_NOMBRE = SUBPRODUCTO + ' - '+( SELECT SUB.NOMBRE FROM SIG_SUB_FINALIDAD SUB 
												  WHERE SUB.ANO_EJE = SI_TRANS_ORDEN.ANO_EJE AND
														SUB.ID_SUB_FINALIDAD = SI_TRANS_ORDEN.ID_SUB_FINALIDAD  AND
														SUB.ESTADO = 'A' )
 WHERE 	ano_eje = @P_ANO_EJE
	     AND SEC_EJEC = @P_SEC_EJEC
	     AND ID_SUB_FINALIDAD IS NOT NULL    
 
  UPDATE SI_TRANS_ORDEN
 SET SUBPRODUCTO_NOMBRE = '0000000 - SIN PRODUCTO'
 WHERE 	ano_eje = @P_ANO_EJE
	     AND SEC_EJEC = @P_SEC_EJEC
	     AND ID_SUB_FINALIDAD IS NULL    

 /**14. Genérica**/
	 UPDATE SI_TRANS_ORDEN
	 SET    NOM_GENERICA = GENERICA + ' - ' + (
	            SELECT nombre_clasif
	            FROM   SIG_CLASIFICADOR_GASTO
	            WHERE  ANO_EJE = @P_ANO_EJE
	                   AND CLASIFICADOR = GENERICA + '. 0  0. 0  0'
	                   AND estado = 'A'
	        )
	 WHERE  ano_eje = @P_ANO_EJE
	        AND SEC_EJEC = @P_SEC_EJEC  

/**15.SUB_GENERICA1**/
	UPDATE SI_TRANS_ORDEN
	SET NOM_SUB_GENERICA1= SUB_GENERICA1 +' - '+ (
		SELECT nombre_clasif FROM SIG_CLASIFICADOR_GASTO WHERE ANO_EJE= @P_ANO_EJE 
		AND CLASIFICADOR =SUB_GENERICA1+'  0. 0  0' AND
		estado='A')
	WHERE
	ano_eje=@P_ANO_EJE AND
	SEC_EJEC=@P_SEC_EJEC
	
/**16.SUB_GENERICA2**/
	UPDATE SI_TRANS_ORDEN
	SET NOM_SUB_GENERICA2= SUB_GENERICA2 +' - '+ (
													SELECT nombre_clasif FROM SIG_CLASIFICADOR_GASTO WHERE ANO_EJE= @P_ANO_EJE 
													AND CLASIFICADOR =SUB_GENERICA2+'. 0  0' AND
													estado='A')
	WHERE
	ano_eje=@P_ANO_EJE AND
	SEC_EJEC=@P_SEC_EJEC

/**17.ESPECIFICA1**/
	UPDATE SI_TRANS_ORDEN
	SET NOM_ESPECIFICA1= ESPECIFICA1 +' - '+ (
		SELECT nombre_clasif FROM SIG_CLASIFICADOR_GASTO WHERE ANO_EJE= @P_ANO_EJE 
		AND CLASIFICADOR =ESPECIFICA1+'  0' AND
		estado='A')
	WHERE
	ano_eje=@P_ANO_EJE AND
	SEC_EJEC=@P_SEC_EJEC  

/**18.ESPECIFICA2**/
	UPDATE SI_TRANS_ORDEN
	SET NOM_ESPECIFICA2= ESPECIFICA2 +' - '+ (
		SELECT nombre_clasif FROM SIG_CLASIFICADOR_GASTO WHERE ANO_EJE= @P_ANO_EJE 
		AND CLASIFICADOR =ESPECIFICA2 AND
		estado='A')
	 WHERE
	ano_eje=@P_ANO_EJE AND
	SEC_EJEC=@P_SEC_EJEC 
 
/** CATEGORIA_PPTAL**/
	UPDATE SI_TRANS_ORDEN
	SET CATEGORIA_PPTO = 'ACCIONES (SIN PROGRAMA)'
  WHERE  
	ano_eje=@P_ANO_EJE AND
	SEC_EJEC=@P_SEC_EJEC  AND
	programa_ppto= '9001'  
	

	UPDATE SI_TRANS_ORDEN
	SET CATEGORIA_PPTO = 'ASIGNACIONES (SIN PROGRAMA)'
	WHERE  
	ano_eje=@P_ANO_EJE AND
	SEC_EJEC=@P_SEC_EJEC  AND
	programa_ppto= '9002'

	UPDATE SI_TRANS_ORDEN
	SET CATEGORIA_PPTO = 'CON PROGRAMA'
	WHERE  
	ano_eje=@P_ANO_EJE AND
	SEC_EJEC=@P_SEC_EJEC  AND
	programa_ppto NOT IN ('9001','9002') 

END

