CREATE VIEW V_SEGUNDO_REPORTE_VW_DETA_ORD
AS
SELECT D.ANO_EJE,D.SEC_EJEC,D.NRO_CERTIFICA,A1.TIPO_BIEN,D.TIPO_PPTO,
A1.NRO_ORDEN, R.FUENTE_FINANC, F.COD_NIVEL1, F.COD_NIVEL2,R.CLASIFICADOR,
COUNT(*) CUENTA, SUM(COALESCE(R.VALOR_SOLES,0)) TOTAL
FROM SIG_CERTIFICACION_FASE A1, SIG_ORDEN_ADQUISICION D, SIG_ORDEN_SECUENCIA S, 
SIG_ORDEN_PRESUPUESTO R,SIG_CLASIFICADOR_GASTO F
WHERE 
A1.ANO_EJE = D.ANO_EJE AND A1.SEC_EJEC = D.SEC_EJEC AND
A1.NRO_CERTIFICA = D.NRO_CERTIFICA AND 
A1.SEC_FASE = 2 AND 
A1.TIPO_BIEN = D.TIPO_BIEN AND D.TIPO_PPTO = 1 AND
(
(COALESCE(A1.NRO_CONSOLID,0) > 0  AND COALESCE(A1.NRO_CONTRATO,0) = 0 AND COALESCE(A1.NRO_ORDEN,0) >0 and A1.TIPO_BIEN='B') OR
(COALESCE(A1.NRO_CONSOLID,0) > 0  AND COALESCE(A1.NRO_CONTRATO,0) = 0 AND COALESCE(A1.NRO_ORDEN,0) >0 and A1.TIPO_BIEN='S') OR
(COALESCE(A1.NRO_CONSOLID,0) > 0  AND COALESCE(A1.NRO_CONTRATO,0) = 0 AND COALESCE(A1.NRO_ORDEN,0) >0 and A1.TIPO_BIEN='V')
) AND
(COALESCE(A1.NRO_ORDEN,0) = COALESCE(D.NRO_ORDEN,0) AND COALESCE(A1.NRO_ORDEN,0) > 0 ) AND
D.ANO_EJE = S.ANO_EJE AND
D.SEC_EJEC = S.SEC_EJEC AND
D.TIPO_PPTO = S.TIPO_PPTO AND
D.TIPO_BIEN = S.TIPO_BIEN AND
D.NRO_ORDEN = S.NRO_ORDEN AND
R.ANO_EJE = S.ANO_EJE AND
R.SEC_EJEC = S.SEC_EJEC AND
R.TIPO_PPTO = S.TIPO_PPTO AND
R.TIPO_BIEN = S.TIPO_BIEN AND
R.NRO_ORDEN = S.NRO_ORDEN AND
R.SEC_ORDEN = S.SEC_ORDEN AND
F.ANO_EJE = R.ANO_EJE AND
F.CLASIFICADOR = R.CLASIFICADOR
GROUP BY 
D.ANO_EJE,D.SEC_EJEC,D.NRO_CERTIFICA,A1.TIPO_BIEN,D.TIPO_PPTO,A1.NRO_ORDEN, R.FUENTE_FINANC,F.COD_NIVEL1, F.COD_NIVEL2,R.CLASIFICADOR

