CREATE  VIEW  V_PRIMER_REPORTE_VW_DETA_DOCW 
AS 
SELECT  A.ANO_EJE, A.SEC_EJEC,A.NRO_CERTIFICA, A.NRO_CONSOLID,
C.FUENTE_FINANC, E.COD_NIVEL1,  
E.COD_NIVEL2, D.SEC_FUNC, D.CLASIFICADOR, 
SUM( 
CASE WHEN B.SEC_OPERA = 1 THEN COALESCE(D.VALOR_SOLES,0) 
WHEN B.SEC_OPERA = 2 THEN COALESCE(D.VALOR_SOLES,0) 
WHEN B.SEC_OPERA = 3 THEN (-1) * COALESCE(D.VALOR_SOLES,0) 
WHEN B.SEC_OPERA = 4 THEN (-1) * COALESCE(D.VALOR_SOLES,0) 
END)TOTAL 
FROM SIG_CERTIFICACION X, SIG_CERTIFICACION_FASE A, 
SIG_CERTIFICACION_OPERACION B, SIG_CERTIFICACION_OPER_FUENTE C, 
SIG_CERTIFICACION_PPTO D, SIG_CLASIFICADOR_GASTO E 
WHERE  
A.ANO_EJE = X.ANO_EJE AND A.SEC_EJEC = X.SEC_EJEC AND  
A.NRO_CERTIFICA = X.NRO_CERTIFICA AND 

A.ANO_EJE = B.ANO_EJE AND A.SEC_EJEC = B.SEC_EJEC AND  
A.NRO_CERTIFICA = B.NRO_CERTIFICA AND A.SECUENCIA_FASE = B.SECUENCIA_FASE AND 

C.ANO_EJE = B.ANO_EJE AND C.SEC_EJEC = B.SEC_EJEC AND C.NRO_CERTIFICA = B.NRO_CERTIFICA AND 
C.SECUENCIA_FASE = B.SECUENCIA_FASE AND C.SECUENCIA_OPERA = B.SECUENCIA_OPERA AND 

C.ANO_EJE = D.ANO_EJE AND C.SEC_EJEC = D.SEC_EJEC AND C.NRO_CERTIFICA = D.NRO_CERTIFICA AND 
C.SECUENCIA_FASE = D.SECUENCIA_FASE AND C.SECUENCIA_OPERA = D.SECUENCIA_OPERA AND 
C.SECUENCIA_DET = D.SECUENCIA_DET AND 

E.ANO_EJE = D.ANO_EJE AND
E.CLASIFICADOR = D.CLASIFICADOR AND 
A.SEC_FASE = 2 AND COALESCE(A.NRO_CONSOLID, 0) > 0
GROUP BY A.ANO_EJE, A.SEC_EJEC,A.NRO_CERTIFICA,A.NRO_CONSOLID,
C.FUENTE_FINANC, E.COD_NIVEL1,E.COD_NIVEL2, D.SEC_FUNC, D.CLASIFICADOR 

