CREATE VIEW  V_PRIMER_REPORTE_VW_DETA_DOC 
AS 
SELECT  
M.ANO_EJE, M.SEC_EJEC,A1.NRO_CONSOLID, X1.NRO_CERTIFICA, X1.COD_CERTIFICA, X1.NRO_CERTIFICA_SIAF, 
M.FUENTE_FINANC, M.COD_NIVEL1, M.COD_NIVEL2, M.CLASIFICADOR ,  
SUM(COALESCE(M.TOTAL,0)) - SUM(COALESCE(R.TOTAL,0)) TOTAL ,
SUM(COALESCE(M.TOTAL,0)) TOTAL_CP ,
SUM(COALESCE(R.TOTAL,0)) TOTAL_CA
FROM  
SIG_CERTIFICACION X1, SIG_CERTIFICACION_FASE A1,
V_PRIMER_REPORTE_VW_DETA_DOCM M LEFT JOIN V_PRIMER_REPORTE_VW_DETA_DOCW R ON
R.ANO_EJE = M.ANO_EJE AND  
R.SEC_EJEC = M.SEC_EJEC AND 
R.NRO_CERTIFICA = M.NRO_CERTIFICA AND 
R.NRO_CONSOLID = M.NRO_CONSOLID AND 
R.FUENTE_FINANC = M.FUENTE_FINANC AND 
R.COD_NIVEL1 = M.COD_NIVEL1 AND 
R.COD_NIVEL2 = M.COD_NIVEL2 AND
R.SEC_FUNC = M.SEC_FUNC AND
R.CLASIFICADOR = M.CLASIFICADOR
WHERE 
A1.ANO_EJE = X1.ANO_EJE AND A1.SEC_EJEC = X1.SEC_EJEC AND
A1.NRO_CERTIFICA = X1.NRO_CERTIFICA AND
 
M.ANO_EJE = X1.ANO_EJE AND M.SEC_EJEC = X1.SEC_EJEC AND 
M.NRO_CERTIFICA = X1.NRO_CERTIFICA AND 

A1.SEC_FASE = 1 

GROUP BY  
M.ANO_EJE, M.SEC_EJEC,A1.NRO_CONSOLID, X1.NRO_CERTIFICA, X1.COD_CERTIFICA, X1.NRO_CERTIFICA_SIAF, 
M.FUENTE_FINANC, M.COD_NIVEL1, M.COD_NIVEL2, M.CLASIFICADOR  

