CREATE VIEW  V_PRIMER_REPORTE_VW_DETA_DOCM 
AS 
SELECT  
X1.ANO_EJE, X1.SEC_EJEC,X1.NRO_CERTIFICA, A1.NRO_CONSOLID,
C1.FUENTE_FINANC, R.COD_NIVEL1, R.COD_NIVEL2, D1.SEC_FUNC, D1.CLASIFICADOR ,  
SUM( 
CASE WHEN B1.SEC_OPERA = 1 THEN COALESCE(D1.VALOR_SOLES,0) 
WHEN B1.SEC_OPERA = 2 THEN COALESCE(D1.VALOR_SOLES,0) 
WHEN B1.SEC_OPERA = 3 THEN (-1) * COALESCE(D1.VALOR_SOLES,0) 
WHEN B1.SEC_OPERA = 4 THEN (-1) * COALESCE(D1.VALOR_SOLES,0) 
END) TOTAL 
FROM  SIG_CERTIFICACION X1, SIG_CERTIFICACION_FASE A1, 
SIG_CERTIFICACION_OPERACION B1, SIG_CERTIFICACION_OPER_FUENTE C1, 
SIG_CERTIFICACION_PPTO D1, SIG_CLASIFICADOR_GASTO R
WHERE  
A1.ANO_EJE = X1.ANO_EJE AND A1.SEC_EJEC = X1.SEC_EJEC AND 
A1.NRO_CERTIFICA = X1.NRO_CERTIFICA AND 

A1.ANO_EJE = B1.ANO_EJE AND A1.SEC_EJEC = B1.SEC_EJEC AND 
A1.NRO_CERTIFICA = B1.NRO_CERTIFICA AND A1.SECUENCIA_FASE = B1.SECUENCIA_FASE AND 

C1.ANO_EJE = B1.ANO_EJE AND C1.SEC_EJEC = B1.SEC_EJEC AND C1.NRO_CERTIFICA = B1.NRO_CERTIFICA AND 
C1.SECUENCIA_FASE = B1.SECUENCIA_FASE AND C1.SECUENCIA_OPERA = B1.SECUENCIA_OPERA AND 

C1.ANO_EJE = D1.ANO_EJE AND C1.SEC_EJEC = D1.SEC_EJEC AND 
C1.NRO_CERTIFICA = D1.NRO_CERTIFICA AND C1.SECUENCIA_FASE = D1.SECUENCIA_FASE AND 
C1.SECUENCIA_OPERA = D1.SECUENCIA_OPERA AND C1.SECUENCIA_DET = D1.SECUENCIA_DET AND 

R.ANO_EJE = D1.ANO_EJE AND  
R.CLASIFICADOR = D1.CLASIFICADOR AND 

A1.SEC_FASE = 1 AND COALESCE(A1.NRO_CONTRATO, 0) = 0
GROUP BY  
X1.ANO_EJE, X1.SEC_EJEC,X1.NRO_CERTIFICA, A1.NRO_CONSOLID,
C1.FUENTE_FINANC, R.COD_NIVEL1, R.COD_NIVEL2, D1.SEC_FUNC, D1.CLASIFICADOR 

